### ISSUE TITLE
Microcontrollers unbreakable and duplicating

### ISSUE THREAD

**Issue by mandrewpowers** [MightyPirates/OpenComputers#2130] opened 2016-11-13 23:58 UTC
Every time I place a microcontroller the server throws up a bunch of errors and the item in my inventory isn't used up. When I try to break the block it doesn't actually get removed even in creative.

Here are the errors
```java
[15:56:04] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[15:56:29] [Server thread/INFO]: [TehBigA: Set own game mode to Creative Mode]
[15:56:30] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[15:56:31] [Server thread/ERROR] [FML]: A TileEntity type li.cil.oc.common.tileentity.Microcontroller has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.ArrayIndexOutOfBoundsException
[15:56:31] [Server thread/ERROR] [FML]: A TileEntity type li.cil.oc.common.tileentity.Microcontroller has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.ArrayIndexOutOfBoundsException
[15:56:31] [Server thread/ERROR] [FML]: A TileEntity type li.cil.oc.common.tileentity.Microcontroller has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.ArrayIndexOutOfBoundsException
[15:56:31] [Server thread/ERROR] [FML]: A TileEntity type li.cil.oc.common.tileentity.Microcontroller has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.ArrayIndexOutOfBoundsException
[15:56:31] [Server thread/ERROR] [FML]: A TileEntity type li.cil.oc.common.tileentity.Microcontroller has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.ArrayIndexOutOfBoundsException
[15:56:31] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[15:56:32] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

**Comment by Vexatos** [comment] 2016-12-11 11:30
Which version of Minecraft and OpenComputers are you using?

**Comment by MaHuJa** [comment] 2016-12-20 03:14
I saw this in mc1.10 using a previous version, but with 1.6.1.6 it is not happening anymore.

**Comment by MaHuJa** [comment] 2017-01-02 09:34
Scratch that. Seeing it again now. It appears to have something to do with the block it's placed into, whether its neighbors or its previous history (i.e. that this happens when breaking a MC rather than placing it)

After it happened, I noticed the "phantom block" would still remain after being mined. Trying a exu2 block breaker (autominer?) to break it yields the following crash log:
http://pastebin.com/hxF2pykG

Full client log, 2.8MB
https://dl.dropboxusercontent.com/u/16193576/minecraft/fml-client-latest.log
will not be available forever; once it says this post is over a month old, check the second line is exactly
[06:28:18] [main/INFO] [FML/]: Forge Mod Loader version 12.18.3.2185 for Minecraft 1.10.2 loading

OpenComputers-MC1.10.2-1.6.1.6.jar

**Comment by nepcore** [comment] 2017-01-11 15:41
I have the same or at least a very similar problem and I figured out what causes it for me
It happens whenever I place a MC adjacent to an Item Conduit from EnderIO
Since it does not happen with Hoppers I guess it might be something about how adjacent inventories are handled by the Item Conduit
I guess that other mods might do something like the Item Conduit as well and could cause the same problem

Also, here is a paste of the important part of my log
http://pastebin.com/KWvGq8y0

**Comment by MaHuJa** [comment] 2017-01-13 05:27
>adjacent to an Item Conduit from EnderIO

Confirmed; this is what I'm seeing too.

**Comment by MOXFan** [comment] 2017-01-13 06:20
I've observed this also, complete with EnderIO conduits (item and redstone)
nearby.  Rebooting the server allowed the block to be broken as usual.

**Comment by Vectrobe** [comment] 2017-02-17 07:36
I've found this is guaranteed to occur when placed next to/in front of a mekanism universal cable, this is with a basic tier1 m.c. with a tier 1 redstone card and basic level logic.

And as suggested above, restarting the "server" (in this case the full client) completely is the only way to recover from it, the broken tileentity persists if you simply reload the world.

**Comment by payonel** [comment] 2018-02-20 09:14
I cannot repro this. tried MANY variations of placing blocks and different ender io conduits
I know things have been fixed for the enderio and the microcontrollers, that was months ago and this bug is over a year old
closing as no repro, please retest with latest builds

**Closed as completed by payonel** 2018-02-20 09:14 UTC
