### ISSUE TITLE
Server rack extension boards

### ISSUE THREAD

**Issue by magik6k** [MightyPirates/OpenComputers#1323] opened 2015-07-23 17:02 UTC
Just a loose idea.
Extension board would be a thing that is put into a server slot in server rack and extends server rack functionality.
Proposed extension boards:
- Switch board - would have regular switch UI, used to upgrade rack internal switch. Putting more than one to rack would allow to create switches for high load networks
- Firewall board - like T2 server but with 2 'special' network cards used to filter traffic. All data that hits the server rack would be received by this board and it would decide what to do with it. probably limited to one per rack.
- Router board - like T3 server, or more expensive, with 4(or at least 2) network cards and space for linked/wireless card, limited to one per rack.
- RAID board - raid on a board
- Disk drive - disk drive board
- Micro controller board - dunno why but it could have some LED's it would use to indicate things
- Battery board - To keep servers running in case of power fail

With some API it would be possible to implement things like tape drive board and other cool stuff

**Comment by Kubuxu** [comment] 2015-07-23 17:04
I'd love to see uC board and also general API (tapedrives in rack as backups would be awesome).

**Comment by Vexatos** [comment] 2015-07-23 17:30
Would be cool if it rendered differently than actual servers in the rack, if it rendered at all.
RAID board sounds pretty bad to me as you could just use RAID blocks. Same for the disk drive and Battery. If the Battery becomes a think, it should only have a small buffer (maybe 500).

**Comment by LizzyTrickster** [comment] 2015-07-23 17:40
For the Battery Board, perhaps make it act solely as a _backup_? So it charges up when the normal stuff gets power but it's power doesn't get drained by any device in the network so long as there is still energy in it and only powers the servers in the rack and nothing else.
1. So you have a fully powered network, the battery board charges.
2. No more power is being put into the network and it slowly drains out, battery board is in idle state.
3. power in the rest of the network is completely gone, battery board kicks in and keeps the server(s) powered till it dies and also sends an event (battery_powering, battery_idle, battery_charged) to any and all servers it's powering.
4. when the network has sufficient power for the server to run, triggers power_active event

as for the rest of the stuff, they all seem cool :D

**Comment by magik6k** [comment] 2015-07-23 17:45
For the rendering part, custom color and led placement seems to be enough, so switch board would blink when it is processing data, uC would have control over it, etc.

And yeah, I second battery ideas

**Comment by fnuecke** [comment] 2015-07-23 18:46
This... general idea seems so obvious I wonder why it's not a thing already :P
I'll have a look into how much work such an API would be, hopefully not too much. Some first thoughts:
- Switch: multiple of those could be... tricky. Maybe by designating them to different sides? In principle I like the idea of having those as a faster "bridge" than the built-in forwarding in the rack.
- Firewall: Hrm, maybe as a simplified server with 2 built-in network cards? And can be connected to two sides?
- Router: kind of like a t2 firewall? I wonder if this could be... generalized somehow. Maybe prebuild them using an assembler? Picking the sides could be kinda meh then, though... dunno.
- Raid: eh, I suppose, why not.
- Disk drive: maybe with multiple floppy slots?
- MCU: actually, maybe these could be the basis for the firewall/router? Not that they'd have enough slots for 4 network cards tho... hrm.
- Battery: UPS like? Not sure how well this could be done given OC's limited power handling, but one way or another probably doable, yeah.

Additional remarks:
- In general, the API would probably have to allow components to pick which sides they connect to (e.g. servers as-is, switches to two or multiple sides, etc).
- I agreed boards could (should?) have their own GUIs in general; should be easy enough by taking the click position (already used for binding remote terminals after all).
- Access Point board: maybe for 1.6 and moving the whole remote terminal logic into that?
- Power Distributor board: also for 1.6, with that we could then remove all "built-in" magic functionality from the rack, and handle everything via boards.

**Comment by Kubuxu** [comment] 2015-07-23 19:30
Stupid idea: If server's GUI is to be open make it look pulled out of the rack.

If opening GUI were to stop server from running some safety mechanism like whacking it with Scrench make it pulled out and GUI accessible.

**Comment by magik6k** [comment] 2015-07-23 19:33
Maybe in-GUI rack cabling, you get 4 'rails' to which you connect things, like:

```
Server->|  |  |  |  Top
Server->|  |<-|--|--Bottom
     \--|--|->|  |  Back 
RAID----|--|->|  |  Front
Router->|<-|--|--|--Left
    \\--|->|  |  |<-Right
     \--|--|--|->| 
        L  W  R  W
        A  A  A  A
        N  N  I  N
           1  D  2
```

**Comment by XeonSquared** [comment] 2015-07-24 16:11
Oh man, I'm loving these ideas.
Perhaps the router/firewall could be a MCU board with x network cards plus maybe space for one more card? I'm totally for stuff like that though, and if it has LEDs you could use it to find a specific rack, too.
Also, tape drive board would be awesome, I could finally make stuff more compact :D
The whole idea is awesome, really. But I do rather like microcontrollers :D

**Comment by LizzyTrickster** [comment] 2015-07-24 16:13
Another idea (potentially): Should the Chassis Switches (switch boards) make the current built in switch non-functional? So if your rack has a switch board in it it does all the stuff the internal one did which would potentially prevent any loops from happening.

Also mergeable server racks (limit of 2?), say if you have 2 racks on top of each other and facing the same way, their textures will seem like it's a multi-block and can allow for more extensions

**Comment by fnuecke** [comment] 2015-07-24 16:13
Hmm, _if_ in 1.6 access point boards were to take the role of the remote terminal handling, then I suppose the GUI of the rack as it exists now would be completely redundant and each server could have its own GUI. Not sure if that would even have to stop it. I mean, it would make sense, agreed, but eh :P

Rails: interesting idea. Did take me a moment to understand that diagram, though, but a decent GUI might remedy that.

**Comment by LizzyTrickster** [comment] 2015-07-24 16:16
> Stupid idea: If server's GUI is to be open make it look pulled out of the rack.

Maybe have a button in the server's gui to turn it off and put it into 'maintenance mode' which makes it look halfway in the case, and only then you can modify components (disks excluded)?

**Comment by fnuecke** [comment] 2015-07-24 16:19
> So if your rack has a switch board in it it does all the stuff the internal one did which would potentially prevent any loops from happening.

See last point in my first reply; ideally the built-in switching (and power distribution etc) could go out of the window entirely.

> Also mergeable server racks (limit of 2?)

Ehh... I kinda don't like coding multiblock stuff, but if it's just changing up the renderer a bit to check for a rack below/above... maybe.

**Comment by magik6k** [comment] 2015-07-24 19:44
I don't see router/firewall as MCU, mainly because eeprom is WAY to small to handle logic that would be required for anything useful.

**Comment by Kubuxu** [comment] 2015-07-24 20:12
@magik6k IIRC you couldn't fit your network driver in it.

**Comment by Shuudoushi** [comment] 2015-07-24 23:06
I didn't want to add this to just here, as it would be kinda hard to close it, but here  #1329

**Comment by fnuecke** [comment] 2015-07-25 15:18
While doodling on a mockup of a new GUI, I've been thinking this over a bit more. For one, I'd like to do this in one go, so it'll be 1.6 because it'll break existing builds that depend on the racks' built-in switching + power distribution.

Now to give some context to the following part, current mockup (totally non-final).
![rack-mockup](https://cloud.githubusercontent.com/assets/514903/8890032/f77bf244-32f0-11e5-94cc-54a0ad224c1b.png)

For two, wrt. firewall/router thinger, my idea for an interface of a rack mountable would allow specifying the number of connections and nodes for those connections, i.e. something along these lines:

```
interface RackMountable extends ManagedEnvironment {
  int numNodes();
  Node node(int index);
}
```

Now this will introduce a more complex way of connecting stuff in slots anyway, meaning servers could also take advantage of this. I'm thinking servers would have one exposed node by default, the "main" line, which is what's currently there, and then one more node per network card, which would be an "indirect" line, i.e. only forwarding network messages. This should allow building firewalls/switches by using servers as they are now, I'd think? There'd basically be an interface for environments to "request" such additional nodes, that way stuff like the spoofing card from Computronics could also work like that in a server.
As for the GUI representation, to avoid this getting too confusing, a tooltip when hovering a connection line should do nicely I'd say.

**Comment by magik6k** [comment] 2015-07-25 15:45
Yup, nodes per network card seem to be good idea, one wouldn't have to implement routers/firewalls. Power distribution should be at least partly covered by the case itself, possibly by built in power distributor merging power from all lines.

About rack merging: rack could share their rails if one is on top of another. I don't think custom rendering would be required here, but it would be a nice feature.

**Comment by Kubuxu** [comment] 2015-07-25 16:07
@magik6k they have top/bottom in common and I think it would be enough.

If power distribution was to be not default I think at least one additional slot for server/module would be useful. Then you would put special power distributor inside and connect whatever lines you would like.

Also connections in front seem a bit counteractive for me, you usually shouldn't cover the front of a rack. My idea is to forbid connections in front of a rack and change Front bus to Internal.

**Comment by fnuecke** [comment] 2015-07-25 16:40
Yeah, the front line is a derp :P Ignore that one.

**Comment by makkarpov** [comment] 2015-07-25 16:44
I think that using whole slot for just one upgrade is too expensive. Look at the switches at real life - you can put (not install, but physically place) 10-14 of them in standard 1U slot. Maybe there's should be some 'component container' that will hold all those stuff?

**Comment by LizzyTrickster** [comment] 2015-07-25 17:00
> I think that using whole slot for just one upgrade is too expensive. Look at the switches at real life - you can put (not install, but physically place) 10-14 of them in standard 1U slot. Maybe there's should be some 'component container' that will hold all those stuff?

What size switches have you seen? High performance Chassis Switches usually take up about the space of 2-3 servers (height wise).

Though for OC I guess a normal 1U switch would be enough of a comparison

**Comment by makkarpov** [comment] 2015-07-25 17:04
Those switches can also handle a great amount of packets, so it's not the case. Also 1U switches are usually thin and does not occupy full unit space. Again, with this amount of upgrades there should be place for servers too :D

**Comment by magik6k** [comment] 2015-07-25 18:52
Take in account that currently upgradeable OC switch occupies 1 cubic meter. Also if Sangar agrees on rack stacking I proposed, it won't hurt that much.

**Comment by makkarpov** [comment] 2015-07-25 18:54
> Take in account that currently upgradeable OC switch occupies 1 cubic meter.

Currently microcontrollers occupy same 1 cubic meter.

> Also if Sangar agrees on rack stacking I proposed, it won't hurt that much.

Yes, if stacked racks would share connection lines, then component container will be redundant.

**Comment by Kubuxu** [comment] 2015-07-25 19:16
As I said when you stack racks logical is that top/bottom will be shared, the only problem I see it is limited to two blocks high (but this should be enough)

With front being `internal` rail you can do almost anything.
Place switch and power distributor and battery in lower rack, transfer packets and power via top bus. On top place a server with entry server connected to bottom and internal and backed connected only to internal.
EDIT: Hmm, internal will also need power. 4 slots is a bit limited with this concept.

**Comment by makkarpov** [comment] 2015-07-25 19:19
How it means that racks can't share all lines, not just one?

**Comment by Kubuxu** [comment] 2015-07-25 19:21
Should it magically merge sides of two rack on top of each other?
Rails are sides of racks.

**Comment by makkarpov** [comment] 2015-07-25 19:25
Rails are _connected_ to sides of racks, but visually they are horizontal lines. If they were a vertical lines, then connection between vertically stacked racks would look ok.

**Comment by magik6k** [comment] 2015-07-25 19:30
+1

**Comment by Kubuxu** [comment] 2015-07-25 19:38
Solution would be to allow rails to be configured in two variants. Separate (as in sample GUI) and symmetric in which you could merge top and bottom or left and right. This would allow stacking upwards.

If all rails were shared it would mean that you have very limited number of outputs of server and also rails.

With one rail shared between racks (top/bottom) and one internal you can do anything. Biggest benefit is that you can even branch into sides to connect something like NAS which wouldn't be possible if all rails were shared.

**Comment by Shuudoushi** [comment] 2015-07-25 21:48
How about making three '1/3' slots dedicated to upgrades like the switch rack and power rack ect.?

Also would it be possible to have a 'monitor/keyboard' rack and a component bus rack?

The monitor/keyboard rack would be like a t1 or t2 monitor and a built in keyboard (more useful for things like network servers where a dedicated monitor setup would be slightly useless), but take up a full rack slot.

The component bus rack would be one of the 1/3 racks and give you 3 more component buses, and maybe require a t1 CPU and some extra RAM or something on-board, this would be VERY useful for stuff like the floppy rack if floppy drives do get converted over to components (#1144).

**Comment by Shuudoushi** [comment] 2015-07-25 22:10
Oh, and to make it worth it to upgrade to a power rack, make it so that the built in power dis of the case/rack is enough to power just what is in the rack, but if you have a stacked rack (if they work the way I and other people think/hope they work), it would fall short and you would get 'not enough energy' messages or something.

**Comment by magik6k** [comment] 2015-08-24 14:12
As an addition to node per network card, the component buses should expose own nodes too. this would allow creating shared subnetworks of components, such as disk dives, etc. Connecting 2 buses to 1 rail would double the component capacity.

**Comment by makkarpov** [comment] 2015-08-24 14:19
Also, component buses can be made switchable so server can adjust amount of visible components. If they would be switchable, they also should refuse to switch on if it will lead to component limit hard error.

**Comment by fnuecke** [comment] 2015-10-11 10:25
Thinking about this some more, and in particular taking the limitations of OC's networking implementation into account here's what I'm now planning. If you think I'm overlooking something, let me know.
- 5 buses, one for each connectable side.
- Each board can have exactly one "main" connection, to either a bus, or nothing.
  - This avoids "bridging" buses (internally, anyway) and makes it easier to visualize.
- Boards can have 3 (main limitation being visualizing it in the GUI tbh) "sub" connections to any bus (the main one being pointless).
  - This is intended e.g. for network cards in servers, to allow connecting to multiple sides.
  - Technically this would use a 'sniffer' node to catch all network messages coming from the address of the sub connection and relay that to the bus it is connected to.
  - Potential annoyance: broadcasts would also arrive on the main bus. But that's an acceptable limitation IMHO.

**Comment by fnuecke** [comment] 2015-11-01 13:49
Allright, did some more mocking-up. Think this'll be close-ish to what I'll eventually try to implement.

![rack-rework](https://cloud.githubusercontent.com/assets/514903/10869189/5e2e70f8-80a7-11e5-88b4-939a12a0d9c5.png)

The 'cells' on the buses when hovered should show a tooltip with what they correspond to in the respective server on that row. Clicking them will toggle the connection.

The button with the relay icon can be used to enable/disable automatic routing of network messages between sides (similar to the internal/external modes now). Dumbing this down a bit because it was primarily confusing. When disabled the lines between the big boxes won't be rendered to indicate the separation / that no network messages will be relayed.

In general: thick lines = direct connection (i.e. including component access), thin lines = network access (i.e. only network messages will be forwarded).

The dice numbers are just there for color-blind people.

**Comment by Shuudoushi** [comment] 2015-11-01 19:38
Looks pretty good, can't wait to play with it once it's live :P

**Comment by fnuecke** [comment] 2015-11-15 21:27
[Current state](https://www.youtube.com/watch?v=OH7sCSN8AxA). Not sure how many of the suggested other types I'll actually implement for 1.6, but at least servers and terminal servers (for remote terminals) are pretty much done (not sure I even want to keep the range setting).

**Comment by payonel** [comment] 2017-12-04 13:59
This feature request inspired some great additions - most of this request was implemented. We'll handle adding other blade types separately (without this github ticket)

**Closed as completed by payonel** 2017-12-04 13:59 UTC
