### ISSUE TITLE
External lua component API performance issues with Extreme Reactors

### ISSUE THREAD

**Issue by brisingraerowing** [MightyPirates/OpenComputers#2632] opened 2017-11-17 19:43 UTC
~~With OC 1.7.x, if a mod uses Environment / Callback Annotation-based Lua method callbacks, each time one of those methods is called, a one tick delay occurs. This appears to have not been the case with OC 1.6.x. This was noticed with XyFreak's BRGC program, and further testing revealed the above information.~~

BRGC (and possibly other programs) need to update state frequently to make sure that things keep working, and this delay makes such programs unusable. Considering that mods that use a lookup table (like Mekanism / Draconic Evolution) are unaffected, ~~this seems to be a bug introduced in the 1.7.x line~~.

UPDATE: This issue has been found to occur with 1.6.1.6 as well. From the thread, this may be an issue with the capability based Environment provider system.

[Start of discussion on oc.cil.li](https://oc.cil.li/index.php?/topic/918-big-reactors-grid-control/&do=findComment&comment=6551)

**Comment by Tahakk** [comment] 2018-01-20 13:36
bump

**Comment by ArcanoxDragon** [comment] 2018-01-22 04:14
A status on this would be nice...my server has lots of players with loaded chunks, meaning each overworld tick is nearly 50ms. Having the computers have to yield for 50ms _each_ API call means it's essentially unusable.

**Comment by Gavote** [comment] 2018-01-25 17:21
What briman said!

**Comment by skyem123** [comment] 2018-01-25 18:07
Something that will make this issue easier to test and fix would be to know what is the absolute minimum needed to actually encounter this? Just MC + Forge + OC + BRGC?
Sadly I think the person who knows how the yucky internals of cross mod interaction work is busy, and will be for quite a while (real life is no fun).

**Comment by Gavote** [comment] 2018-01-25 20:11
If you need more experimental data, please check out https://oc.cil.li/index.php?/topic/918-big-reactors-grid-control/

**Comment by Tahakk** [comment] 2018-01-26 08:43
[Link](https://oc.cil.li/index.php?/topic/918-big-reactors-grid-control/&page=14&tab=comments#comment-6551) for start of conversation is at start of this GitHub issue

**Comment by payonel** [comment] 2018-01-26 09:30
First of all, the computers are not meant to be realtime machines.
Secondly, os.sleep(.5) (and computer.pullSignal(.5) for that matter) will yield for at least .5 seconds, not exactly .5 seconds.
Thirdly, a single machine lua thread is given is limit to the number of direct api calls it can make before it must "play nice" and further execution is postponed. This is a balance choice so that player machines don't starve servers of their tick time. Eventually, ticks will be missed. The closest you can get is to make an api call, sleep for 0 seconds until os.time() advances
Fourth - if someone finds time wasted in reflection or other forms of dispatch and would like to recommend a PR to improve, I would be happy to review it.

**Comment by ArcanoxDragon** [comment] 2018-01-26 15:34
I don't think this is an issue about computers not being "realtime" or having throttling...it makes sense that the computer should only have a certain amount of "CPU cycles" per tick, especially since other hardware restrictions such as RAM and storage space are simulated.

The issue is that ever since a recent OC version (the BRGC thread has some information on which OC versions are affected), API calls to certain mods' APIs yield for _*excessively long*_ times.

If BRGC is running as a service with one reactor and one turbine, it takes upwards of 5 seconds (sometimes 10) to type _*each individual character*_ into the shell. This means that typing "reboot" can take literally nearly a minute.

Several other reactor control programs are affected as well, however BRGC has the most API calls due to its heavily optimized calibrations and live-tuning of grid setups, so it is affected the most.

**Comment by payonel** [comment] 2018-01-26 15:48
First of all, if you are sleeping ( `os.sleep` ) in a service, that is going to block your shell. Use threads instead if you want to sleep without blocking other coroutines http://ocdoc.cil.li/api:thread
Second of all, the list of versions seems to point to a regression in ER from version ER 0.4.5.30 to ER 0.4.5.41

**Comment by ArcanoxDragon** [comment] 2018-01-26 15:54
The change that caused this bug was due to a deprecation of a certain method of callback registration on OC's part. One of the OC devs recommended to ZeroNoRyouki that Extreme Reactors should stop using this method of registration and start using capability-based registration instead, which is the change that started causing this bug.

It's not an issue with the BRGC program sleeping on the main thread because the same BRGC version works fine on one version of ER and not another.

**Comment by payonel** [comment] 2018-01-26 16:00
As a side note to this discussion, if you `os.sleep` in an rc service or event listen handler, it WILL block the main shell. Threads are required to use sleep and NOT block other coroutines

**Comment by payonel** [comment] 2018-01-26 16:03
What method was deprecated?
What method is ER using now?
Can ER use the old method that ran faster?

**Comment by skyem123** [comment] 2018-01-26 16:04
It is interesting that the behaviour changes depending on how the API is implemented on the mod...

**Comment by ArcanoxDragon** [comment] 2018-01-26 16:23
I can't find the exact post where Zero mentioned being told which method to use, but apparently ER and Computronics both use an `Environment` with `@Callback(...)` on the API methods Java-side, whereas Mekanism (and likely DE) uses an `Environment` that implements an `invoke(...)` method instead of using the `@Callback` annotation.

Apparently according to the discussion on the BRGC thread, `@Callback` isn't definitely the problem, although if that's the only difference between ER/Computronics and Mekanism/DE, I would have to guess that the delay is caused by some part of the implementation of the `@Callback` annotation (potentially method lookup via reflection...reflection in Java is painfully slow).

**Comment by Vexatos** [comment] 2018-01-26 16:36
That has absolutely nothing to do with it. How many times a method can be executed per tick is determined by the parameters in the `@Callback` annotation, i.e. whatever the mod author wants it to be. You're given quite a bit of control regarding the execution limits of your callbacks.

**Comment by ArcanoxDragon** [comment] 2018-01-26 16:40
Unless the reflection used to look up the correct `@Callback` method is what is causing the delay

**Comment by Vexatos** [comment] 2018-01-26 16:42
Remember that literally every component in OpenComputers and Computronics uses `@Callback`, including things like GPUs. Reflection has a reputation for being slow, and yes, it is obviously slower than direct calls, but it isn't nearly slow enough to make any sort of impact here.

**Comment by Vexatos** [comment] 2018-01-26 16:45
I am quite sure that the issue isn't caused by OpenComputers but instead introduced on the side of ER during the port from `ManagedPeripheral` over to `@Callback`s, even though I am not sure why that was done since it has nothing to do with OC having deprecated the `Environment` tile interface. Unless you want to make use of the advanced level of control provided by the parameters inside `@Callback`, there shouldn't have been any need to change that.

**Comment by Vexatos** [comment] 2018-01-26 17:00
I just checked the latest version of ER, it does indeed seem like they use the `@Callback` annotation without any parameters, meaning every method will take an entire tick to execute. They either need to make their callbacks `direct` as specified in the javadoc, or go back to using `ManagedPeripheral` like BigReactors used to do.

**Comment by ArcanoxDragon** [comment] 2018-01-26 17:02
I believe ManagedPeripheral is what Zero was told not to use, but this is extremely helpful information. I could probably make a PR for ER tonight unless @ZeroNoRyouki has time to fix it soon.

**Comment by Vexatos** [comment] 2018-01-26 17:03
ManagedPeripheral basically replaces the `@Callback` system with something very similar to ComputerCraft's `IPeripheral`, for those who like using it. It lacks all the advanced and fine-grained control that `@Callback` parameters allow (e.g. you cannot add component documentation, or change the execution speed), but all calls are direct, i.e. do not take the whole tick, _by default_.

**Comment by Vexatos** [comment] 2018-01-26 17:05
ManagedPeripheral basically replaces the `@Callback` system with something very similar to ComputerCraft's `IPeripheral`, for those who would like to have an easier time supporting both mods. It lacks all the advanced and fine-grained control that `@Callback` parameters allow (e.g. you cannot add component documentation, or change the execution speed), but all calls are direct _by default_, i.e. do not take the whole tick. An alternative (and perhaps better option) would be to stick to the `@Callback` system but make calls `direct` in the annotation parameters. Please refer to the OC API's javadoc on both `ManagedPeripheral` and `Callback` for this.

**Comment by Vexatos** [comment] 2018-01-26 17:09
Closing this since I am reasonably confident this has nothing to do with OC's side of things.

**Closed as completed by Vexatos** 2018-01-26 17:09 UTC

**Comment by ZeroNoRyouki** [comment] 2018-01-26 18:11
What I was asked to do was to move away from SimpleComponent (see #2371). I would have gladly avoided it

If ManagedPeripheral is indeed invoked "directly" by default (the class javadoc does not mention it) there may be a bunch of mods getting called from outside the server thread without knowing it... (like ER used to be before the switch from SimpleComponent)

**Comment by Vexatos** [comment] 2018-01-26 18:13
As mentioned, `ManagedPeripheral` is meant for mods who already have ComputerCraft integration. `IPeripheral`'s methods are always called in a separate thread, and have always been, so mods using `ManagedPeripheral` should have already made their calls thread-safe anyway. It might still be a good idea to document it more explicitly.

**Comment by ZeroNoRyouki** [comment] 2018-01-26 18:50
Eh.. I'm looking at code right now that was never thread-safe....

**Comment by Vexatos** [comment] 2018-01-26 18:52
Then you might just have been lucky with both ComputerCraft _and_ OpenComputers executing their calls in a separate thread without causing any issues.

**Comment by ZeroNoRyouki** [comment] 2018-01-26 18:56
Me and every player since 1.7.10. Or was it different then?
