### ISSUE TITLE
Computers won't boot

### ISSUE THREAD

**Issue by mainrs** [MightyPirates/OpenComputers#2711] opened 2017-12-31 14:03 UTC
I have tried all tiers out but I acnnot start any of the computers that I build. I made several screenshots of the setup that I use. Would be nice if you guys could help me out :smile:

![2017-12-31_15 00 32](https://user-images.githubusercontent.com/5113257/34462070-9956c082-ee3b-11e7-99b1-5e284ccb0a1d.png)
![2017-12-31_15 00 36](https://user-images.githubusercontent.com/5113257/34462071-9b238134-ee3b-11e7-8b54-933e852976a0.png)
![2017-12-31_15 00 39](https://user-images.githubusercontent.com/5113257/34462072-9c862cde-ee3b-11e7-8686-55eb138be891.png)
![2017-12-31_15 00 46](https://user-images.githubusercontent.com/5113257/34462073-9e3db038-ee3b-11e7-8f4f-98c59d192202.png)
![2017-12-31_15 00 52](https://user-images.githubusercontent.com/5113257/34462074-9f93cb34-ee3b-11e7-84c7-0bcaf05f8e39.png)
![2017-12-31_15 00 58](https://user-images.githubusercontent.com/5113257/34462075-a19fdca6-ee3b-11e7-86ed-ff2c60790f44.png)

Every time I hover over the on button, the tooltip states that I should check with the analyzer tool. But the analyzer just outputs basic information and does not display any error messages in the chat (image above).
![2017-12-31_15 01 05](https://user-images.githubusercontent.com/5113257/34462084-c091b814-ee3b-11e7-9f4e-6f989dbe712e.png)

**Edit:** Changed the RAM sticks to Tier 1 from Tier 1.5, still without any results.

**Comment by payonel** [comment] 2017-12-31 15:24
what oc version?
looks like you're doing everything right, I do apologize for the inconvenience, but I think this is a duplicate of #2695

**Closed as completed by payonel** 2017-12-31 15:24 UTC

**Comment by mainrs** [comment] 2017-12-31 15:42
@payonel I am running on Forge 2566 and this is still happening. So it is not within the range of 2577-2581  specified by @GerritVK. Not sure if this information helps though. I will try 2573 as specified in the other thread.

**Comment by payonel** [comment] 2017-12-31 15:43
@SirWindfield more importantly, try our "Fix" build also linked

**Comment by payonel** [comment] 2017-12-31 15:45
http://ci.cil.li/job/OpenComputers-MC1.12/
build 46 (or after when that comes)

**Comment by SirWindfield** [comment] 2017-12-31 15:48
Nice, will try it out!

**Comment by mainrs** [comment] 2017-12-31 16:42
Looks like it boots up now.

**Comment by mainrs** [comment] 2017-12-31 16:47
Don't want to open up another issue for this.

I couldn't find any information on the event pull api. I put a motion sensor next to the tier 3 computer and booted it up. Calling `components` lists the sensor. Running the following hangs the computer though: `lua` followed by `=event.pull("motion")`. If I remeber correctly, this should print the result of the pull method. But even when passing the sensor, nothing happens. Ctrl+D doesnt work and I need to shutdown the pc using the button.
I have tested all sides of the sensor. None worked. The sensor is attached directly to the computer. I also tried it once with just cables.

**Comment by payonel** [comment] 2017-12-31 16:59
^d closes the input stream (for things using standard input streams), and `dmesg` doesn't care about that. It specifically waits for ^c (it says that too when it starts up)

we are discussing improvements for our docs, one such improvement that would help you in this regard would be to group signal info with the respective components. sad thing is you are pulling the correct event, but I haven't been able to prove my fixes merging back up to 1.12 yet (i'm actually working on that right now) -- so I believe 1.12 suffers from a motion_sensor bug that i've fixed on 1.10 that hasn't been merged up yet

should be merged and pushed soon (seriously, i should be done today ... i think normally it is against tradition to commit to that sort of thing :) )

**Comment by mainrs** [comment] 2017-12-31 17:02
Ah ok. I was wondering what the heck was  going on. Started a 1.10 instance and it worked perfectly there haha :smile: Thanks for your work! Will the new build be avaiable from the CI side too?

**Comment by payonel** [comment] 2017-12-31 17:17
btw....i talked about `dmesg` in my response and you aren't using that at all, you were just calling `event.pull`, sorry, I was distracted with something else and didn't think through what you what you were saying.

^c sends a interrupt event, what we call a soft interrupt. It doesn't kill anything except things specifically waiting for the "interrupted" signal and then care to shutdown themselves (`dmesg` does this)

the event dispatch sub system will throw an exception if you are holding control+shift+c, also known as a hard interrupt. This would have worked in your case. Note that if you have code that isn't dieing and is NOT ever yielding to the event sub system (e.g. via `event.pull` or `os.sleep`, etc) then you'll not observe an exception for a hard interrupt (also, said system would probably soon die to failing to yield in the allowed time [5s default])

As for the CI side: that is actually the originating source of our builds.

**Comment by mainrs** [comment] 2017-12-31 17:45
Thanks for the reply! Got it. I tried ctrl+c but that didn't work either. The hard interrupt did the trick.
