### ISSUE TITLE
[Suggestion]: Floppy drive component calls.

### ISSUE THREAD

**Issue by Shuudoushi** [MightyPirates/OpenComputers#1329] opened 2015-07-24 23:06 UTC
Being able to eject the floppy via an OS (i.e. remotely) would help in things like #1323 for the floppy rack. Being able to remotely eject the floppies could also help speed up installs by auto-ejecting the floppy after install is complete.

**Comment by magik6k** [comment] 2015-07-24 23:10
I vote for adding force parameter, max force would cause 0.5 heart damage to player if he/she is hit by floppy

**Comment by Shuudoushi** [comment] 2015-07-24 23:14
YES! And also maybe auto placing into chest/inv if close enough (and low enough force :3).

**Comment by Inari-Whitebear** [comment] 2015-07-24 23:30
Haha force parameter sounds great

**Comment by dgelessus** [comment] 2015-07-25 00:00
May the force be with you. *shoots floppy*

**Comment by gjgfuj** [comment] 2015-07-25 02:20
There was already an issue for this. It's coming in oc1.6.

**Comment by Shuudoushi** [comment] 2015-07-25 02:21
Hmmm, perhaps I just didn't have the right search term...

**Comment by fnuecke** [comment] 2015-07-25 08:05
Yeah, duplicate of #1144, including the ejection velocity ;-)

**Closed as completed by fnuecke** 2015-07-25 08:05 UTC
