### ISSUE TITLE
Charger Crashes

### ISSUE THREAD

**Issue by thiakil** [MightyPirates/OpenComputers#2066] opened 2016-09-23 15:23 UTC
1:
[crash-2016-09-23_23.07.58-server.txt](https://github.com/MightyPirates/OpenComputers/files/490016/crash-2016-09-23_23.07.58-server.txt)
Placed charger, placed redstone torch next to it as shown, server crashed.
![2016-09-23_23 16 41](https://cloud.githubusercontent.com/assets/1788847/18791054/d0afc526-81e3-11e6-8e87-acb2f26c4f00.png)

2:
Placed drone in front of charger, server crashed again
[crash-2016-09-23_23.10.44-server.txt](https://github.com/MightyPirates/OpenComputers/files/490024/crash-2016-09-23_23.10.44-server.txt)

OC version: 51085de828258f42b564a63ed82ece99be022ec2 (compiled by me to get the drone placement fix, no modifications)
Forge: 12.18.1.2084

NB: both times starting the server up worked fine to get back in, only happens on placements

**Comment by Vexatos** [comment] 2016-11-14 18:05
Can you still reproduce this issue using the latest OC release (1.6.1)?

**Comment by Vexatos** [comment] 2016-12-29 12:02
Closing this for lack of a response. I will re-open this if this turns out to still be an issue.

**Closed as completed by Vexatos** 2016-12-29 12:02 UTC
