### ISSUE TITLE
Excessive power drain

### ISSUE THREAD

**Issue by tehscott** [MightyPirates/OpenComputers#664] opened 2014-11-12 02:57 UTC
Using OC 1.4.0.5-beta.2:

I have a Resonant Energy Cell which connects to a Tier 1 Computer Case via RedNet Energy Cable. If I connect the case directly to the energy cell (no Converter), it drains huge amounts of power (as much as the cell is set to put out) per tick, even with the case turned off. If add a Power Converter, no power drain when it is off and a normal drain when it is on.

**Comment by magik6k** [comment] 2014-11-12 06:56
Duplicate of #663

**Comment by fnuecke** [comment] 2014-11-12 09:56
Yep, sounds very much like a duplicate. Please try the latest dev build which should fix that.

**Closed as completed by fnuecke** 2014-11-12 09:56 UTC
