### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by The-Fireplace** [MightyPirates/OpenComputers#987] opened 2015-03-30 21:38 UTC
I don't know if this is entirely your fault or a conflict with another mod, but it pointed to OpenComputers first, so here is a crash report I got when I tried to kill a sheep:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  TransformerLoader (OpenComputers-MC1.8-1.5.4.9-universal.jar)
  CCCDeobfPlugin (unknown)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.34-universal.jar)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.88-universal.jar)
  ItemPatchingLoader (ItemPhysic Full 1.1.4 mc1.8.jar)
  NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  LoadingPlugin (VersionChecker-1.2.1.jar)
  keysoverhaul (KeyBindingsOverhaul-LATEST-1.8.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 3/30/15 4:31 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at li.cil.oc.util.BlockPosition$.apply(BlockPosition.scala:52)
    at li.cil.oc.client.renderer.HighlightRenderer$.onDrawBlockHighlight(HighlightRenderer.scala:34)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_33_HighlightRenderer$_onDrawBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:271)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1321)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1207)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1032)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1048)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at li.cil.oc.util.BlockPosition$.apply(BlockPosition.scala:52)
    at li.cil.oc.client.renderer.HighlightRenderer$.onDrawBlockHighlight(HighlightRenderer.scala:34)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_33_HighlightRenderer$_onDrawBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:271)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1321)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1207)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['The_Fireplace'/163, l='MpServer', x=258.93, y=67.00, z=247.85]]
    Chunk stats: MultiplayerChunkCache: 270, 270
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: 240.00,64.00,252.00 - World: (240,64,252), Chunk: (at 0,4,12 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 1562 game time, 1562 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 71 total; [EntitySheep['Sheep'/40, l='MpServer', x=250.34, y=66.00, z=229.75], EntitySheep['Sheep'/41, l='MpServer', x=259.09, y=67.00, z=243.16], EntitySheep['Sheep'/42, l='MpServer', x=246.13, y=66.00, z=238.25], EntitySheep['Sheep'/43, l='MpServer', x=265.91, y=67.00, z=253.00], EntitySheep['Sheep'/44, l='MpServer', x=239.50, y=64.00, z=253.75], EntitySheep['Sheep'/45, l='MpServer', x=262.16, y=67.00, z=247.34], EntitySheep['Sheep'/46, l='MpServer', x=253.50, y=64.00, z=262.81], EntitySheep['Sheep'/47, l='MpServer', x=246.56, y=64.00, z=257.63], EntityItem['item.tile.flower2.houstonia'/56, l='MpServer', x=262.84, y=19.00, z=196.94], EntityItem['item.tile.flower2.houstonia'/57, l='MpServer', x=261.56, y=19.00, z=195.75], EntityChicken['Chicken'/58, l='MpServer', x=278.38, y=73.00, z=327.50], EntityChicken['Chicken'/59, l='MpServer', x=267.50, y=73.00, z=325.50], EntityChicken['Chicken'/60, l='MpServer', x=277.25, y=73.00, z=327.50], EntityChicken['Chicken'/61, l='MpServer', x=272.50, y=70.00, z=324.50], EntityCreeper['Creeper'/6213, l='MpServer', x=337.50, y=48.00, z=293.50], EntitySkeleton['Skeleton'/6215, l='MpServer', x=225.50, y=26.00, z=235.50], EntityCow['Cow'/74, l='MpServer', x=281.78, y=63.00, z=306.78], EntityCow['Cow'/75, l='MpServer', x=281.19, y=64.00, z=313.59], EntitySheep['Sheep'/91, l='MpServer', x=303.50, y=67.00, z=191.50], EntitySheep['Sheep'/92, l='MpServer', x=307.81, y=67.00, z=194.69], EntitySheep['Sheep'/93, l='MpServer', x=312.91, y=67.00, z=201.03], EntitySheep['Sheep'/94, l='MpServer', x=303.16, y=67.00, z=194.81], EntityChicken['Chicken'/100, l='MpServer', x=336.50, y=72.00, z=273.50], EntityChicken['Chicken'/101, l='MpServer', x=334.53, y=72.00, z=283.34], EntityChicken['Chicken'/102, l='MpServer', x=336.50, y=72.00, z=274.50], EntityRabbit['Rabbit'/103, l='MpServer', x=329.50, y=65.00, z=323.50], EntityRabbit['Rabbit'/104, l='MpServer', x=330.47, y=69.00, z=318.81], EntityRabbit['Rabbit'/105, l='MpServer', x=329.34, y=64.00, z=326.34], EntityEnderman['Enderman'/6359, l='MpServer', x=265.56, y=11.00, z=259.47], EntityBat['Bat'/8407, l='MpServer', x=201.84, y=27.00, z=189.75], EntityCreeper['Creeper'/6360, l='MpServer', x=273.00, y=11.00, z=255.41], EntityBat['Bat'/8408, l='MpServer', x=211.22, y=27.19, z=208.84], EntityCreeper['Creeper'/6361, l='MpServer', x=270.59, y=11.00, z=259.00], EntityBat['Bat'/8409, l='MpServer', x=197.31, y=27.28, z=174.41], EntityZombie['Zombie'/6362, l='MpServer', x=271.50, y=11.00, z=255.50], EntityBat['Bat'/8413, l='MpServer', x=198.56, y=26.02, z=176.25], EntityBat['Bat'/8414, l='MpServer', x=255.75, y=24.00, z=273.25], EntityBat['Bat'/8416, l='MpServer', x=266.16, y=27.69, z=267.13], EntityBat['Bat'/8418, l='MpServer', x=241.03, y=15.09, z=280.88], EntityBat['Bat'/8419, l='MpServer', x=237.44, y=16.10, z=279.25], EntityZombie['Zombie'/8441, l='MpServer', x=204.34, y=22.00, z=302.34], EntityCreeper['Creeper'/8480, l='MpServer', x=266.69, y=11.00, z=259.50], EntityCreeper['Creeper'/8481, l='MpServer', x=267.59, y=11.00, z=259.50], EntityZombie['Zombie'/8482, l='MpServer', x=268.50, y=11.00, z=259.50], EntityZombie['Zombie'/8507, l='MpServer', x=176.66, y=22.00, z=269.69], EntityPlayerSP['The_Fireplace'/163, l='MpServer', x=258.93, y=67.00, z=247.85], EntityCreeper['Creeper'/385, l='MpServer', x=257.50, y=31.00, z=249.50], EntitySkeleton['Skeleton'/388, l='MpServer', x=307.50, y=14.00, z=311.50], EntitySkeleton['Skeleton'/438, l='MpServer', x=201.50, y=33.00, z=179.50], EntityBat['Bat'/487, l='MpServer', x=228.01, y=18.16, z=272.57], EntityZombie['Zombie'/8852, l='MpServer', x=186.50, y=21.00, z=282.50], EntityCreeper['Creeper'/8854, l='MpServer', x=227.50, y=42.00, z=174.50], EntityZombie['Zombie'/6928, l='MpServer', x=329.72, y=21.00, z=303.16], EntitySpider['Spider'/6930, l='MpServer', x=338.50, y=22.00, z=298.50], EntityBat['Bat'/6978, l='MpServer', x=308.25, y=11.00, z=275.44], EntitySkeleton['Skeleton'/7161, l='MpServer', x=179.50, y=21.00, z=269.50], EntityZombie['Zombie'/7174, l='MpServer', x=294.50, y=10.00, z=279.50], EntitySpider['Spider'/7233, l='MpServer', x=195.50, y=37.00, z=169.50], EntitySpider['Spider'/7234, l='MpServer', x=191.50, y=37.00, z=168.50], EntityZombie['Zombie'/1118, l='MpServer', x=332.50, y=60.00, z=287.50], EntitySkeleton['Skeleton'/7455, l='MpServer', x=175.50, y=23.00, z=183.50], EntitySpider['Spider'/7488, l='MpServer', x=269.50, y=27.00, z=261.50], EntitySpider['Spider'/7489, l='MpServer', x=267.50, y=27.00, z=264.50], EntityZombie['Zombie'/7743, l='MpServer', x=177.50, y=22.00, z=268.50], EntityZombie['Zombie'/7744, l='MpServer', x=178.34, y=21.00, z=270.06], EntitySkeleton['Skeleton'/1604, l='MpServer', x=192.50, y=28.00, z=181.50], EntityZombie['Zombie'/1616, l='MpServer', x=212.50, y=25.00, z=277.50], EntityCreeper['Creeper'/1625, l='MpServer', x=266.44, y=33.00, z=214.41], EntityZombie['Zombie'/1648, l='MpServer', x=336.50, y=26.00, z=279.50], EntityZombie['Zombie'/1715, l='MpServer', x=210.50, y=20.00, z=180.91], EntityBat['Bat'/6026, l='MpServer', x=275.00, y=20.00, z=189.84]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2488)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:374)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 193483448 bytes (184 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.10 FML v8.0.42.1338 Minecraft Forge 11.14.1.1338 32 mods loaded, 32 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{8.0.42.1338} [Forge Mod Loader](forge-1.8-11.14.1.1338.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{11.14.1.1338} [Minecraft Forge](forge-1.8-11.14.1.1338.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.5.34} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.5.88} [Not Enough Items](NotEnoughItems-1.8-1.0.5.88-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    itemphysic{1.1.2} [ItemPhysic](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    securitycraft{v1.7.3} [SecurityCraft]([1.8] SecurityCraft 1.7.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    basemetals{1.2.1} [Base Metals](basemetals-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    info.varden.chatlog{2.1.1.43} [ChatLog](ChatLog-1.8-v2.1.1.43.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    lootablebodies{1.1.2} [DrCyano's Lootable Bodies](CyanosLootableBodies-1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    VersionChecker{1.2.1} [Version Checker](VersionChecker-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    fireplacecore{2.1.4.0} [Fireplace Core](Fireplace Core 2.1.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    clayspawn{2.0.2.0} [Fire's Clay Spawn](Fire's Clay Spawn 2.0.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    glass_shards{1.3.1} [Glass Shards](glass_shards_mc1.8-1.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    hopperducts{1.4.5} [Hopper Ducts](hopperducts-mc1.8-1.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IngameAccountSwitcher{1.8-r1} [In-Game Account Switcher](IngameAccountSwitcher-1.8-r1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    keysoverhaul{1.0} [Key Bindings Overhaul](KeyBindingsOverhaul-LATEST-1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LavaBoat{2.1.0} [LavaBoat](LavaBoat-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mobrebirth{2.1.0.4} [Mob Rebirth](Mob Rebirth 2.1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    moreclienttweaks{2.0.0.3} [More Client Tweaks](More Client Tweaks 2.0.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    antiswear{2.0.0.3} [More Client Tweaks - AntiSwear Module](More Client Tweaks 2.0.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    neotech{1.5} [NeoTech](NeoTech-1.8-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    netheressence{2.0.0.1} [Nether Essence](Nether Essence 2.0.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers{1.5.4.9} [OpenComputers](OpenComputers-MC1.8-1.5.4.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    parachutemod{1.8.0} [Parachute Mod](parachutemod-1.8.0-3.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PigManure{1.0.1} [Pig Manure](pig-manure-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    progressiveautomation{1.6.4} [Progressive Automation](ProgressiveAutomation-1.8-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    shipwrecks_winslow{1.6.3} [Shipwrecks!](shipwrecks_winslow-1.8.0-1.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SlimevoidLib{3.0.0.4-beta-1.8} [Slimevoid Library](SlimevoidLibrary-3.0.0.4-beta-1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WirelessRedstone{2.0.0.1-alpha-1.8} [Wireless Redstone](WirelessRedstoneCore-2.0.0.1-alpha-1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    XaeroMinimap{1.3.9} [Xaero's Minimap](xaeros_minimap_v1.3.9_1.8_Forge.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
TransformerLoader (OpenComputers-MC1.8-1.5.4.9-universal.jar)
  li.cil.oc.common.asm.ClassTransformer
CCCDeobfPlugin (unknown)

CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.34-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
NEICorePlugin (NotEnoughItems-1.8-1.0.5.88-universal.jar)
  codechicken.nei.asm.NEITransformer
ItemPatchingLoader (ItemPhysic Full 1.1.4 mc1.8.jar)
  com.creativemd.itemphysic.ItemTransformer
NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  net.fybertech.nwr.NowWithRendering
LoadingPlugin (VersionChecker-1.2.1.jar)

keysoverhaul (KeyBindingsOverhaul-LATEST-1.8.jar)
  code.elix_x.coremods.keysoverhaul.core.KeysOverhaulTransformer
    Launched Version: 1.8-Forge11.14.1.1338
    LWJGL: 2.9.1
    OpenGL: GeForce GT 620/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.88, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
```

**Comment by fnuecke** [comment] 2015-03-30 21:41
Duplicate of... too lazy to look up the numbers. Anyway, get the latest dev build from [Jenkins](http://ci.cil.li).

**Closed as completed by fnuecke** 2015-03-30 21:41 UTC
