### ISSUE TITLE
Errors running the class transformer

### ISSUE THREAD

**Issue by The7thTinkerer** [MightyPirates/OpenComputers#2114] opened 2016-10-29 09:47 UTC
I've recently started playing Hermitpack and I encountered this error every time I try and log into a server. I would really appreciate some help.

http://paste.feed-the-beast.com/view/4d156e3d
[4d156e3d.txt](https://github.com/MightyPirates/OpenComputers/files/559868/4d156e3d.txt)

Thanks,
7th

**Comment by mdinnocenzo** [comment] 2016-10-30 05:11
Adding another one to the pot.  I run my own HermitPack server on Ubuntu Server, changes are easy if need to test.  Did find this in the log:

The API OpenComputersAPI|Event from source /home/dino/minecraft/Hermit/mods/OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar is loaded from an incompatible classloader. THIS WILL NOT WORK!

[fml-server-latest.log.txt](https://github.com/MightyPirates/OpenComputers/files/560287/fml-server-latest.log.txt)

**Comment by astr0n8t** [comment] 2016-11-03 13:51
I have this too, but none of my logs show anything except for the error printed in chat.

**Comment by Vexatos** [comment] 2016-11-14 18:31
Duplicate of #1998 and #2014.

**Closed as completed by Vexatos** 2016-11-14 18:31 UTC
