### ISSUE TITLE
nanomachines no potion effects-minecraft 1.10.2

### ISSUE THREAD

**Issue by xaleb** [MightyPirates/OpenComputers#2275] opened 2017-02-18 15:05 UTC
I went into a creative world,  drank nanomachines, and used the debug command after 50 drinks. No potion effects were on any inputs. I am using ftb infinity lites settings. Is this a known problem, or do I need to change the configs? Configs do indeed have the potion effects white-listed

Config entries are below:

nanomachines {

    # Time in seconds it takes for the nanomachines to process a command
    # and send a response.
    commandDelay=1

    # The distance in blocks that nanomachines can communicate within. If
    # a message comes from further away, it'll be ignored. When responding,
    # the response will only be sent this far.
    commandRange=2

    # The relative number of connectors based on the number of available
    # behaviors (see triggerQuota).
    connectorQuota=0.2

    # Radius in blocks of the disintegration behavior for each active input.
    disintegrationRange=1

    # How much damage the hungry behavior should deal to the player when the
    # nanomachine controller runs out of energy.
    hungryDamage=5

    # How much energy the hungry behavior should restore when damaging the
    # player.
    hungryEnergyRestored=50

    # Range of the item magnet behavior added for each active input.
    magnetRange=8

    # The maximum number of inputs for each node of the "neural network"
    # nanomachines connect to. I.e. each behavior node and connector node
    # may only have up to this many inputs.
    maxInputs=2

    # Hard maximum number of active inputs. This is mainly to avoid people
    # bumping other nanomachines' inputs to max, killing them in a matter
    # of (milli)seconds.
    maxInputsActive=4

    # The maximum number of outputs for each node (see maxInputs).
    maxOutputs=2

    # Whitelisted potions, i.e. potions that will be used for the potion
    # behaviors nanomachines may trigger. This can contain strings or numbers.
    # In the case of strings, it has to be the internal name of the potion,
    # in case of a number it has to be the potion ID. Add any potion effects
    # to make use of here, since they will all be disabled by default.
    potionWhitelist=[
      "potion.moveSpeed",
      "potion.digSpeed",
      "potion.damageBoost",
      "potion.jump",
      "potion.resistance",
      "potion.fireResistance",
      "potion.waterBreathing",
      "potion.nightVision",
      "potion.absorption",
      "potion.blindness",
      "potion.confusion",
      "potion.digSlowDown",
      "potion.harm",
      "potion.hunger",
      "potion.moveSlowdown",
      "potion.poison",
      "potion.weakness",
      "potion.wither"
    ]

    # How many input nodes may be active at the same time before negative
    # effects are applied to the player.
    safeInputsActive=2

    # The relative amount of triggers available based on the number of
    # available behaviors (such as different potion effects). For example,
    # if there are a total of 10 behaviors available, 0.5 means there will
    # be 5 trigger inputs, triggers being the inputs that can be activated
    # via nanomachines.
    triggerQuota=0.4
}

**Comment by Vexatos** [comment] 2017-02-18 15:09
Duplicate of #1885.

**Closed as completed by Vexatos** 2017-02-18 15:09 UTC
