### ISSUE TITLE
Incompatibility with Ars Magica 2

### ISSUE THREAD

**Issue by Reyls** [MightyPirates/OpenComputers#544] opened 2014-09-07 10:15 UTC
OC 1.6.4-1.3.4
latest AM2

when a robot destroy an ore from AM2 it get this item
http://i.imgur.com/uL88U2L.png
it's the ID of crescent hammer from TE and it works like a wrench
any other block of AM2 just drop when destroyed by a robot

**Comment by Vexatos** [comment] 2014-09-07 10:28
... You are actually playing Minecraft in German?
_cries with joy_

**Comment by Reyls** [comment] 2014-09-07 10:47
Warum nicht?
Biste froh dass einer deine Übersetzungen nutzt?  ;)

**Comment by fnuecke** [comment] 2014-09-07 12:08
Can't reproduce the invalid item issue, what kind of pickaxe is that, and does it also happen with "normal" pickaxes for you? (which is what I tried it with)

As for the not being able to pick it up issue, that's caused by AM2 trying to send a network packet to the fake player, which errors (see your log, you should see a traceback for each item from AM2 the robot tries to pick up). The only way I could reasonably work around this would be via major hackiness, adding a fake network handler to the fake player, or a bunch of nasty special cases, either of which I'm, quite frankly, unwilling to do. The sane solution to the issue would be for AM2 to check in their `am2.lore.CompendiumUnlockHandler.onPlayerPickupItem` event handler whether the player is a fake player or not. But since from what I understand AM2 isn't being updated for MC1.6 anymore, I'm afraid you're pretty much out of luck on this one.

**Comment by Reyls** [comment] 2014-09-07 12:46
It is the essence pickaxe from magical crops (unbreakable ;)), but the issue happens with diamond pickaxe, too.
Well, it is not that bad. AM2 has a few bugs anyway, so I kicked it out of my mods

**Comment by fnuecke** [comment] 2014-09-07 14:30
Hmm, yeah, that didn't change anything, either. If this is in multiplayer, maybe it's some discrepancy in IDs on the server vs. on the client? (tho it'd have to be some other mod causing this then, since the digging is purely server side as far as OC is concerned). Otherwise it might be some other mod interfering. Either way, I'll close this since it works for me in both single and multiplayer in the latest version.

**Closed as completed by fnuecke** 2014-09-07 14:30 UTC
