### ISSUE TITLE
Nanomachines getName() crashes minecraft

### ISSUE THREAD

**Issue by Itggot-Lucas-Glimfjord** [MightyPirates/OpenComputers#2021] opened 2016-08-15 19:15 UTC
Minecraft crashes every time the nanomachines receive the getName command

**Comment by xarses** [comment] 2016-08-16 16:50
Please provide version information

**Comment by Itggot-Lucas-Glimfjord** [comment] 2016-08-17 20:30
I'm using 1.6.0.3-rc.1

**Comment by fnuecke** [comment] 2016-09-18 17:42
Can't reproduce, crash log please.

**Comment by Vexatos** [comment] 2017-01-27 15:53
Duplicate of the (more recent) #2220 and fixed via https://github.com/MightyPirates/OpenComputers/commit/52a032ff63aea6ada292da1a47ec8caa958521f6.

**Closed as completed by Vexatos** 2017-01-27 15:53 UTC
