### ISSUE TITLE
Terminal Server And/Or Remote Terminal and chunks.

### ISSUE THREAD

**Issue by drunkripper** [MightyPirates/OpenComputers#2280] opened 2017-02-22 01:50 UTC
So the terminal server & remote terminal won't talk to each other after the chunks load, you have to give your self a brand new terminal server and remote terminal. You should make a Crafting recipe to reset all the keys on an item and make it basically brand new. (IP too if you can)

I either get the greeting screen and can't type, or i get "Invalid key, most likely another terminal has been bound to the server." When the settings have stayed the same. No terminal has changed.

**Comment by payonel** [comment] 2017-12-03 05:47
duplicate of #2246

**Closed as completed by payonel** 2017-12-03 05:47 UTC
