### ISSUE TITLE
Raid block bug? 

### ISSUE THREAD

**Issue by SniperHauss89** [MightyPirates/OpenComputers#1162] opened 2015-05-19 20:15 UTC
Hello I am experiencing a possible bug with the Raid block. it doesn't have to do with how it functions but rather with it's state I suppose. in a nutshell what is happening is: Say you have 2 or more Raid blocks you just crafted and you put down just one and then break that one it ends up not stacking even know it is empty like the freshly crafted ones that haven't been placed yet. It's behaving as if it has drives in it when it doesn't. not sure if this is normal or not.

**Comment by MyNameIsKodos** [comment] 2015-05-20 02:02
Someone correct me if I'm wrong, but once you place it, it's assigned an address, which makes it 'unique' and thus not stackable. This isn't a bug, it is working as intended.

**Comment by dgelessus** [comment] 2015-05-20 09:55
But with no drives in it the address is kind of pointless, isn't it? IMO it's not that important _which_ empty RAID I place down.

**Comment by fnuecke** [comment] 2015-05-20 11:01
Yeah, what Kodos describes is the reason, pretty much, and I agree with you that it'd make sense to not write the NBT if the Raid is empty, to allow stacking it again. I'll look into it.

**Comment by fnuecke** [comment] 2015-05-20 21:32
Bloody typos. Closed via f96515acdffcfe4099622670314bc44e3fc1f1d2.

**Closed as completed by fnuecke** 2015-05-20 21:32 UTC
