### ISSUE TITLE
Crashes every time

### ISSUE THREAD

**Issue by TheMajesticPickle** [MightyPirates/OpenComputers#2276] opened 2017-02-19 00:56 UTC
This report used to be about it running in a specific pack. But now, I tried running a pack that contained ONLY opencomputers... heres the result. http://pastebin.com/JAWgCKW0
I'd really like to use this mod, seriously. I've tried and tried again. This has been a problem of mine with every pack that contains this mod. I need a fix, without removing the entire mod, even if it means I have to change the mods code (preferably not, unless it's simple) Thanks in advance.

**Comment by Vexatos** [comment] 2017-02-19 07:47
Duplicate of #1911.

**Closed as completed by Vexatos** 2017-02-19 07:47 UTC

**Comment by TheMajesticPickle** [comment] 2017-02-19 18:32
actually that method didn't work. in curse launcher, I went into settings and changed the launcher from the jar launcher to the native launcher, and now it works without any problem.
