### ISSUE TITLE
crash problem

### ISSUE THREAD

**Issue by saaaaad** [MightyPirates/OpenComputers#1850] opened 2016-06-06 14:31 UTC
hi there my game crash in blac screen when (imeen 1.7.10 modepack) so when i click play i see black screen and game crash the modepack devolper ask me to put my issues there 
crash log 
http://paste.ubuntu.com/17062110/

**Comment by xarses** [comment] 2016-06-06 17:34
It appears that from your log that EnderIO and funky-locomotion are conflicting. You should update or remove funky

```
    EnderIO: Found the following problem(s) with your installation:
                  * An unsupportted old RF API is installed (1.7.10R1.0.0 from funky-locomotion-1.7.10-beta-7.jar).
                    Ender IO needs at least 1.7.10R1.0.2 and will NOT work with older versions.
```

This appears to have nothing to do with OpenComputers

**Comment by fnuecke** [comment] 2016-06-06 18:19
> java.lang.NoClassDefFoundError: com/typesafe/config/ConfigMergeablejava.lang.NoClassDefFoundError: com/typesafe/config/ConfigMergeable

Duplicate of #1516. Means your installation is broken. Reinstall Forge/the modpack. At least older versions of the Curse launcher also did not download that lib correctly, also [see this issue](http://minecraft.curseforge.com/projects/davy-jones-locker/issues/482).

**Closed as completed by fnuecke** 2016-06-06 18:19 UTC
