### ISSUE TITLE
SkyFactory 3 Crashing on Curse

### ISSUE THREAD

**Issue by KebnTheFirst** [MightyPirates/OpenComputers#2254] opened 2017-02-02 22:27 UTC
Having some strange bug with Open Computers causing a crash on SF3 with Curse but I cannot reproduce it on Legacy FTB Client. Here's a copy of the crash log:

http://pastebin.com/rmNW7i4i

Any ideas on how to fix this?

**Comment by Vexatos** [comment] 2017-02-03 08:00
Duplicate of #1911.

**Closed as completed by Vexatos** 2017-02-03 08:00 UTC
