### ISSUE TITLE
java.lang.NoClassDefFoundError: com/typesafe/config/ConfigMergeable

### ISSUE THREAD

**Issue by vagaprime** [MightyPirates/OpenComputers#1911] opened 2016-06-26 04:15 UTC
Just got reported to me. Player was trying to use the curse launcher. when they switched back to the FTB launcher the modpack was able to launch with out problem.

https://github.com/vagaprime/MageTech-Gate/issues/1

Forge 10.13.4.1614

OpenComputers 1.5.22.46

reporting to the academycraft devs as well.

**Comment by fnuecke** [comment] 2016-06-26 07:32
Broken Forge installation, missing at least one library. This is just the Curse launcher being a derp. See [this issue for a workaround](http://minecraft.curseforge.com/projects/davy-jones-locker/issues/482).

Duplicate of #1867.

**Closed as completed by fnuecke** 2016-06-26 07:32 UTC
