### ISSUE TITLE
[Localization] Localize chat messages

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#96] opened 2014-01-25 16:03 UTC
As far as I know, chat messages which appear are always English so far. It would be nice if these could be translatable.

Also: A chat message "too many components" appears if there are essential components like the CPU missing. This should not appear, I assume (using dev43)

**Comment by Forecaster** [comment] 2014-01-25 16:06
I don't think that is possible since chat messages are sent from the server.

And I can confirm the "too many components" message, it's what confused me when I was playing around with the servers. That message seemed to appear at times it shouldn't have.

**Comment by Vexatos** [comment] 2014-01-25 16:08
Localizing chat messages through the server should be possible if there is a way for the server to check which language the client has selected.

**Comment by fnuecke** [comment] 2014-01-25 16:11
Yeah, I just didn't get around to localizing those. It should be possible to generate localized messages using a different method (`server.sendChatToPlayer(ChatMessageComponent message)` to be specific). If I understand it correctly that'll basically create a "template" with localization keys that is then resolved by the clients.

As for the component error message, good point, would be clearer to say there's no CPU if that's the cause.

**Comment by Lunatrius** [comment] 2014-01-25 18:02
Instead of sending a `ChatComponentText` send a `ChatComponentTranslation`. Can't remember the exact names in 1.6.4, but `ChatMessageComponent.createFromTranslation("message.oc.example", arg1, arg2)` should be what you're looking for.

**Closed as completed** 2014-01-26 14:40 UTC
