### ISSUE TITLE
Issue with power consumption

### ISSUE THREAD

**Issue by viser001** [MightyPirates/OpenComputers#833] opened 2015-01-18 19:13 UTC
Some blocks, including the Server Rack, and the Power Converter, do not seem to be able to fill their internal capacitors. This causes them to draw power at insane rates, including draining 51200000 RF in 1-3 minutes. For one reason or another, this also results in the server being unable to turn on, but also not giving any error message, such as not having any power. In addition, it also prevents power from being fed in through cables, conduits, or any other way other than direct connection to a battery or other power reservoir.
Issue discovered on the mod pack Resonant Rise, version 3.2.2.1, mainline.

**Comment by MyNameIsKodos** [comment] 2015-01-18 19:49
What version of OC is in the RR pack?

**Comment by Pwootage** [comment] 2015-01-18 20:04
I can confirm this. I am using version 1.4.3.22. However, it only happened when I was using universal cable - ender io cable seemed to either prevent the issue or it was just limited enough that I didn't notice.

For me, it was draining greater than 10kRF/t. I would assume they are not reporting their empty capacity correctly.

**Comment by Kubuxu** [comment] 2015-01-18 20:30
I had the same issue with Charger and BC Kinesis pipes.

**Comment by viser001** [comment] 2015-01-18 20:33
For me, energy transfer cables didn't work, and only batteries transfer energy

**Comment by Pwootage** [comment] 2015-01-18 20:51
Without knowing enough about all the different power sources and how OC uses them, it may be possible that it's draining the power multiple times. Perhaps someone with knows the tile entity layout of OC needs to take a look at this.

**Comment by MyNameIsKodos** [comment] 2015-01-18 20:52
For those of you not using preconfigured modpacks, try updating to the latest OC, available at http://ci.cil.li/ and make sure you're still having the issue.

**Comment by fnuecke** [comment] 2015-01-18 20:53
What version of BC / TE / CoFHCore was this with?

**Comment by fnuecke** [comment] 2015-01-18 20:58
Regarding universal cables, looks like the Mekanism logic was inverted... I swear by my beard that I fixed this not too long ago, so this either vanished in a bad merge or Mekanism decided to switch things around again. So that particular case be fixed in the next commit.

**Comment by Pwootage** [comment] 2015-01-18 21:00
Latest versions of each, if I'm not mistaken:
buildcraft-6.3.1
ThermalExpansion-[1.7.10]4.0.0B8-23
CoFHCore-[1.7.10]3.0.0B9-40

Rest of my modpack: 
http://pastebin.com/2q7CtHk8

**Comment by MyNameIsKodos** [comment] 2015-01-18 21:02
I have those versions of TE and CoFHCore, and can confirm the problem does not exist for me. However, I do not have that version of BC so the problem may lie within. ¯_(ツ)_/¯   Heck if I know though =)

**Comment by Pwootage** [comment] 2015-01-18 21:05
Do you have mekanism/UE installed?

**Comment by MyNameIsKodos** [comment] 2015-01-18 21:05
I do not, as UE is very unstable right now, and Mekanism causes me to have TPS issues over long periods of time.

**Comment by Pwootage** [comment] 2015-01-18 21:09
The problem likely lies therein then, if you're not having these problems.

**Comment by fnuecke** [comment] 2015-01-18 21:33
So I just tried with only BC + TE, and could not reproduce the issue with 1.4.5.
Please give the latest [dev-build](http://ci.cil.li) (the `universal` one) a go and see if that fixes it for you, thanks.

**Comment by viser001** [comment] 2015-01-19 01:52
I play on a server, and, due to how bad my computer is, i cant play single player for more than a few minutes before it crashes. sorry i cant test it myself.

**Comment by fnuecke** [comment] 2015-02-01 22:51
Assuming this is fixed in latest. Reopen/let me know if it isn't.

**Closed as completed by fnuecke** 2015-02-01 22:51 UTC
