### ISSUE TITLE
Trasformer error

### ISSUE THREAD

**Issue by amreo** [MightyPirates/OpenComputers#1246] opened 2015-06-25 18:46 UTC
Last OpenComputer (beta)

[20:37:09] [main/INFO]: Setting user: amreo
[20:37:13] [Client thread/INFO]: LWJGL Version: 2.9.1
[20:37:15] [Client thread/ERROR]: Couldn't initialize twitch stream
[20:37:27] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Factory, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:BC Robotics, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:ComputerCraft, FMLFileResourcePack:Nether Ores, FMLFileResourcePack:OpenComputers, FMLFileResourcePack:ProjectRed, FMLFileResourcePack:ProjectRed-Compatibility, FMLFileResourcePack:ProjectRed-Integration, FMLFileResourcePack:ProjectRed-Transmission, FMLFileResourcePack:ProjectRed-Illumination, FMLFileResourcePack:ProjectRed-Expansion, FMLFileResourcePack:ProjectRed-Transportation, FMLFileResourcePack:ProjectRed-Exploration, FMLFileResourcePack:Thermal Dynamics, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:WR-CBE Core, FMLFileResourcePack:WR-CBE Addons, FMLFileResourcePack:WR-CBE Logic, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:Forge Microblocks, FMLFileResourcePack:Forge Multipart, FMLFileResourcePack:Minecraft Multipart Plugin, FMLFileResourcePack:MrTJPCore
[20:37:44] [Sound Library Loader/INFO]: Sound engine started
[20:37:47] [Client thread/INFO]: Created: 1024x512 textures/blocks-atlas
[20:37:49] [Client thread/INFO]: Created: 1024x512 textures/items-atlas
[20:38:26] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Factory, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:BC Robotics, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:ComputerCraft, FMLFileResourcePack:Nether Ores, FMLFileResourcePack:OpenComputers, FMLFileResourcePack:ProjectRed, FMLFileResourcePack:ProjectRed-Compatibility, FMLFileResourcePack:ProjectRed-Integration, FMLFileResourcePack:ProjectRed-Transmission, FMLFileResourcePack:ProjectRed-Illumination, FMLFileResourcePack:ProjectRed-Expansion, FMLFileResourcePack:ProjectRed-Transportation, FMLFileResourcePack:ProjectRed-Exploration, FMLFileResourcePack:Thermal Dynamics, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:WR-CBE Core, FMLFileResourcePack:WR-CBE Addons, FMLFileResourcePack:WR-CBE Logic, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:Forge Microblocks, FMLFileResourcePack:Forge Multipart, FMLFileResourcePack:Minecraft Multipart Plugin, FMLFileResourcePack:MrTJPCore
[20:38:27] [Client thread/INFO]: Created: 1024x512 textures/items-atlas
[20:38:36] [Client thread/INFO]: Created: 1024x1024 textures/blocks-atlas
[20:38:38] [Sound Library Loader/INFO]: Sound engine started
[20:39:08] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[20:39:08] [Server thread/INFO]: Generating keypair
[20:39:10] [Server thread/INFO]: Preparing start region for level 0
[20:39:11] [Server thread/INFO]: Preparing spawn area: 38%
[20:39:13] [Server thread/INFO]: Preparing spawn area: 55%
[20:39:15] [Server thread/INFO]: Changing view distance to 12, from 10
[20:39:16] [Server thread/INFO]: amreo[local:E:63bc1849] logged in with entity id 319 at (-703.1438542777838, 21.864430612022748, -771.0631057575804)
[20:39:16] [Server thread/INFO]: amreo joined the game
[20:39:41] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 25825ms behind, skipping 516 tick(s)
[20:40:09] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 27610ms behind, skipping 552 tick(s)
[20:40:21] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 12671ms behind, skipping 253 tick(s)
[20:40:40] [Client thread/INFO]: [CHAT] **§aOpenComputers§f: There were §cerrors§f running the class transformer. Please report this, together with your (full!) FML §alatest.log§f/§afml-server-latest.log§f logfile, thank you!**
[20:40:43] [Server thread/INFO]: Saving and pausing game...
[20:40:43] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[20:40:44] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[20:40:44] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[20:41:28] [Client thread/INFO]: [CHAT] Version 1.4.1.9 of WR-CBE is available
[20:42:02] [Client thread/INFO]: Stopping!
[20:42:03] [Server thread/INFO]: Stopping server
[20:42:03] [Server thread/INFO]: Saving players
[20:42:03] [Server thread/INFO]: Saving worlds
[20:42:03] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[20:42:03] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[20:42:03] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[20:42:04] [Client Shutdown Thread/INFO]: Stopping server
[20:42:04] [Client Shutdown Thread/INFO]: Saving players
[20:42:04] [Client Shutdown Thread/INFO]: Saving worlds
[20:42:04] [Client Shutdown Thread/INFO]: Saving chunks for level 'New World'/Overworld
[20:42:04] [Client Shutdown Thread/INFO]: Saving chunks for level 'New World'/Nether
[20:42:04] [Client Shutdown Thread/INFO]: Saving chunks for level 'New World'/The End

**Comment by amreo** [comment] 2015-06-25 19:03
There's a error another in 1.5.12.26

[20:58:36] [main/INFO]: Setting user: amreo
[20:58:39] [Client thread/INFO]: LWJGL Version: 2.9.1
[20:58:40] [Client thread/ERROR]: Couldn't initialize twitch stream
[20:58:49] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Factory, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:BC Robotics, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:ComputerCraft, FMLFileResourcePack:Nether Ores, FMLFileResourcePack:OpenComputers, FMLFileResourcePack:ProjectRed, FMLFileResourcePack:ProjectRed-Compatibility, FMLFileResourcePack:ProjectRed-Integration, FMLFileResourcePack:ProjectRed-Transmission, FMLFileResourcePack:ProjectRed-Illumination, FMLFileResourcePack:ProjectRed-Expansion, FMLFileResourcePack:ProjectRed-Transportation, FMLFileResourcePack:ProjectRed-Exploration, FMLFileResourcePack:Simply Jetpacks, FMLFileResourcePack:Thermal Dynamics, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:WR-CBE Core, FMLFileResourcePack:WR-CBE Addons, FMLFileResourcePack:WR-CBE Logic, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:Forge Microblocks, FMLFileResourcePack:Forge Multipart, FMLFileResourcePack:Minecraft Multipart Plugin, FMLFileResourcePack:MrTJPCore
[20:59:04] [Sound Library Loader/INFO]: Sound engine started
[20:59:06] [Client thread/INFO]: Created: 1024x512 textures/blocks-atlas
[20:59:07] [Client thread/INFO]: Created: 1024x512 textures/items-atlas
[20:59:22] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Factory, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:BC Robotics, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:ComputerCraft, FMLFileResourcePack:Nether Ores, FMLFileResourcePack:OpenComputers, FMLFileResourcePack:ProjectRed, FMLFileResourcePack:ProjectRed-Compatibility, FMLFileResourcePack:ProjectRed-Integration, FMLFileResourcePack:ProjectRed-Transmission, FMLFileResourcePack:ProjectRed-Illumination, FMLFileResourcePack:ProjectRed-Expansion, FMLFileResourcePack:ProjectRed-Transportation, FMLFileResourcePack:ProjectRed-Exploration, FMLFileResourcePack:Simply Jetpacks, FMLFileResourcePack:Thermal Dynamics, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:WR-CBE Core, FMLFileResourcePack:WR-CBE Addons, FMLFileResourcePack:WR-CBE Logic, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:Forge Microblocks, FMLFileResourcePack:Forge Multipart, FMLFileResourcePack:Minecraft Multipart Plugin, FMLFileResourcePack:MrTJPCore
[20:59:23] [Client thread/INFO]: Created: 1024x512 textures/items-atlas
[20:59:26] [Client thread/INFO]: Created: 1024x1024 textures/blocks-atlas
[20:59:27] [Sound Library Loader/INFO]: Sound engine started
[20:59:45] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[20:59:45] [Server thread/INFO]: Generating keypair
[20:59:45] [Server thread/INFO]: Preparing start region for level 0
[20:59:47] [Server thread/INFO]: Changing view distance to 12, from 10
[20:59:47] [Server thread/INFO]: amreo[local:E:bc304f47] logged in with entity id 243 at (-682.8486750577777, 5.3199999868869785, -782.1685849044283)
[20:59:47] [Server thread/INFO]: amreo joined the game
[20:59:53] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 5764ms behind, skipping 115 tick(s)
[20:59:58] [Client thread/INFO]: [CHAT] **§aOpenComputers§f: There were §cerrors§f running the class transformer. Please report this, together with your (full!) FML §alatest.log§f/§afml-server-latest.log§f logfile, thank you!**
[20:59:59] [Client thread/INFO]: [CHAT] Version 1.4.1.9 of WR-CBE is available
[21:01:29] [Server thread/INFO]: Saving and pausing game...
[21:01:29] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[21:01:29] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[21:01:29] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[21:01:30] [Server thread/INFO]: Stopping server
[21:01:30] [Server thread/INFO]: Saving players
[21:01:30] [Server thread/INFO]: Saving worlds
[21:01:30] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[21:01:30] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[21:01:30] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[21:01:32] [Client thread/INFO]: Stopping!

**Comment by fnuecke** [comment] 2015-06-25 19:05
Duplicate of #1231.

**Closed as completed by fnuecke** 2015-06-25 19:05 UTC
