### ISSUE TITLE
strange program/computer interaction on restart

### ISSUE THREAD

**Issue by KyeDuo** [MightyPirates/OpenComputers#2503] opened 2017-08-31 00:40 UTC
I have found a weird bug.
When I restart my world, none of the computer programs I have running will update the screen when I hit number keys that are used for input, but it will update if I hit the letter keys that control the program. The program does respond to the number key inputs, but the screen won't update. Rebooting the program will fix this. I haven't tried unloading the chunk as there are chunkloaders in the area.
I don't think this is a program issue as it runs fine until world restart.
I am using the latest OC and forge for 1.7.10. I can give the list of other mods if necessary. I have quite a few.

**Comment by payonel** [comment] 2017-08-31 05:37
I think this bug is related to #2302 
I think when a world or chunk loads the gpu is not bound as it was in the previous state
@fnuecke I could run a check in openos to periodically rebind a gpu, but perhaps we are not restoring the bound-state of the gpus when the chunk loads ... as we should

**Comment by fnuecke** [comment] 2017-08-31 08:18
Hmm, the computers *should* wait long enough for things to have been rebound before continuing to execute; maybe the screen is in another chunk so there's some extra delay? Someone would have to debug to see if the Problem is actually on the Lua side (proxy object gone bad?) or on the Scala/Java side (GPU component not being bound at all)...

**Comment by KyeDuo** [comment] 2017-08-31 20:47
One computer the screen and tower are in the same chunk. The other, part of the screen is in the same chunk as the tower.
IDK if this is related but, when I use the Warp Drive Mod and try and jump computers, they stop responding completely and you have to either reboot them or break the monitor to cause the program to crash.
OpenOS 1.5 does not have either behaviors.

**Comment by payonel** [comment] 2017-09-08 06:54
@fnuecke 
confirmed repro on 1.7.10 single player

"before": when the creative robot is first placed and booted into openos
"after": after "Save and Quit", and reloading the world, and seeing the bug repro

a list of a description of things /before/ and /after/
1. component.list() will /before/ iterate to gpu somewhere in the middle of the components, but then gpu is first /after/ (i know it's an unordered iterator, but it was interesting none the less)
2. The same set of components are available
3. all guids are the same
4. `component.list()` never returns fewer or more components
5. creating a `local gpu = component.gpu` and using that local gpu object continues to work
6. using that `local gpu` ref to the proxy, and printing `gpu.getScreen()` **returns nil after**. Recreating a proxy (`component.proxy(component.list("gpu")()).getScreen()`) also **returns nil** 
7. the robot continues to receive keyboard events
8. no additional events are fired (such as "component_added") [ as expected, just saying the mere act of loading the world isn't throwing more events ]

**Comment by payonel** [comment] 2017-10-03 09:58
closing as duplicate of #2302

**Closed as completed by payonel** 2017-10-03 09:58 UTC

**Comment by LemADEC** [comment] 2017-10-23 22:14
Issue was only fixed for robots, computers still reproduce the issue.

**Comment by payonel** [comment] 2017-10-24 08:45
@LemADEC you can open a new ticket with repro steps if you have any

**Comment by LemADEC** [comment] 2017-10-24 22:10
This is the original issue, still reproduced by the original author, as posted on my tracker linked above.

**Comment by payonel** [comment] 2017-10-24 22:17
@LemADEC please open a new ticket. following the steps in this ticket does not reproduce the bug, thus I closed it.

In your new ticket provide:

1. The minimal set of mods required for the repro. Can this repro with OC only?
2. State whether it repros with our 1.7.0 build ( https://minecraft.curseforge.com/projects/opencomputers/files )
3. what mc version do you see the repro
4. are you using a computer case, tablet, server rack, or robot?
5. does this repro in single player
