### ISSUE TITLE
1.9.4 There were errors running the class transformer

### ISSUE THREAD

**Issue by TheMrCaveman** [MightyPirates/OpenComputers#1890] opened 2016-06-16 18:53 UTC
1.9.4 OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar

There were errors running the class transformer message popped up! see log.

[fml-server-latest.txt](https://github.com/MightyPirates/OpenComputers/files/319116/fml-server-latest.txt)

**Comment by fnuecke** [comment] 2016-06-25 18:15
Fixed in latest build, duplicate of #1892.

**Closed as completed by fnuecke** 2016-06-25 18:15 UTC
