### ISSUE TITLE
Errors Running The Class Transformer

### ISSUE THREAD

**Issue by Hastling** [MightyPirates/OpenComputers#2053] opened 2016-09-07 08:46 UTC
I'm using the latest version of OpenComputers.. [Here's](http://bacongaming.net/repo/fml-server-latest.log) a link that will allow you to view the fml-server-latest. I apologize for the size, this is a rather beefy pack.

**Comment by 7OOTnegaTerces** [comment] 2016-09-07 22:05
I've got the same error!  Here's my latest.log file: http://paste.ee/p/E30Ed.  That's the file in the log folder in my Minecraft instance, which I'm assuming (hoping) is the one you want.  I'm running MC 1.10.2 on Mac OSX El Capitan.

**Comment by 7OOTnegaTerces** [comment] 2016-09-07 22:39
My issue was fixed by updating to this OC build: http://ci.cil.li/job/OpenComputers-dev-MC1.10/lastSuccessfulBuild/artifact/build/libs/OpenComputers-MC1.10.2-1.6.0.31-dev.jar

**Comment by Hastling** [comment] 2016-09-08 02:49
I downloaded 1.6.0.31-dev and still the issue persists.

**Comment by Vexatos** [comment] 2016-11-14 18:42
Duplicate of #2014. Should not appear in the latest release (1.6.0) anymore.

**Closed as completed by Vexatos** 2016-11-14 18:42 UTC
