### ISSUE TITLE
Crash on scroll.

### ISSUE THREAD

**Issue by emwebb** [MightyPirates/OpenComputers#895] opened 2015-02-07 17:15 UTC
I appear to be crashing whenever I attempt to scroll with my mouse with the following crash report:
http://pastebin.com/5LHbP5GZ
This occurred both when I was in the shell and when I was using another program (IRC). When using a tier 3 GPU/Screen set up. It did not occur when using a Tier 1 set up.
It appears at a glance that the method "mouseScroll" in an instance of the interface li.cil.oc.api.component.TextBuffer is not being implemented by whatever is implementing it. 
I switched between a few versions (1.4.8,1.4.7,1.4.7a,1.4.6,1.4.5) and all seemed to have the problem.
It may be a problem caused by another mod , but the stacktrace doesn't contain any packages from any other mods.

**Comment by fnuecke** [comment] 2015-02-07 17:16
Duplicate of #852. See that for a workaround.

**Closed as completed by fnuecke** 2015-02-07 17:16 UTC
