### ISSUE TITLE
(OpenOS 1.6.1) /bin/pastebin.lua saves empty file

### ISSUE THREAD

**Issue by IgorTimofeev** [MightyPirates/OpenComputers#2325] opened 2017-03-27 19:16 UTC
Since we have updated to newest mod version, we were facing with a problem where /bin/pastebin.lua saves empty file:

![2017-03-27_21 54 14](https://cloud.githubusercontent.com/assets/11760002/24373205/48313896-1339-11e7-98e7-af7811add559.png)

![2017-03-27_21 54 20](https://cloud.githubusercontent.com/assets/11760002/24373209/4efb8384-1339-11e7-8f96-60ecc82fadc7.png)

Problem can be easily fixed by changing **http** to **https** in source code.

![2017-03-27 22 13 06](https://cloud.githubusercontent.com/assets/11760002/24373646/a6077f42-133a-11e7-8acc-1b6b2da87838.png)

**Comment by Vexatos** [comment] 2017-03-28 09:35
Duplicate of #2230. Update OC.

**Comment by Vexatos** [comment] 2017-03-28 14:43
Apparently not a duplicate. Blame @payonel.

**Comment by payonel** [comment] 2017-05-23 07:37
@Vexatos this does not repro for me, http works just fine
should we change pastebin to use https?
are there config settings that are related? (my settings are default, all I saw was enableHttp and enableHttpHeaders)

**Comment by payonel** [comment] 2017-05-27 06:32
d80c7a84364c58106c21012eff4c5eb07bed83e6

**Closed as completed by payonel** 2017-05-27 06:32 UTC
