### ISSUE TITLE
Crash when breaking monitor while PC is running.

### ISSUE THREAD

**Issue by witchica** [MightyPirates/OpenComputers#1421] opened 2015-09-13 13:30 UTC
Log: http://paste.ee/p/138DE

Version: latest from curseforge (1.8)
What happened?: I broke a monitor while a computer was running and got the above error.

**Comment by dgelessus** [comment] 2015-09-13 20:52
As far as I know this is an error that randomly happens when sounds are being played and that there is nothing that can be done about it. The crash doesn't corrupt the world or anything, so you should be able to restart the game and continue playing.

**Comment by fnuecke** [comment] 2015-09-14 12:17
It certainly _looks_ like it's just MC being a derp. Plus I can't think of a case where OC would interact with the sound system upon breaking a screen, such that this exception could be caused. Buuut who knows. Does this happen reliably? I.e. every time you break a screen? Only when the computer is running?

**Comment by witchica** [comment] 2015-09-14 14:42
@fnuecke It seems to happen when I either break a screen/place alot of monitors together, but not reliably, just random

**Comment by fnuecke** [comment] 2015-10-02 19:18
Tried a bit and can't reproduce the crash, my only guess is that it's actually something in MC/Forge derping. Unless someone has an idea what might actually be causing this, I'm afraid there's nothing I can do.

**Comment by dgelessus** [comment] 2015-10-02 22:01
FWIW, I sometimes get these sound-related `ConcurrentModificationException`s when powering on computers, i. e. when hitting the power button in the GUI. This crashes the game once, the next time I load the world it doesn't happen again.

**Comment by fnuecke** [comment] 2015-10-04 09:48
Please try setting `client.soundVolume` in the OC config to zero. That'll prevent OC from playing any sounds. If it doesn't happen anymore after that (you'll have to be the judge over what timeframe, a week or so?) I suppose it _is_ something weird threading related (tho from looking at the code I can't tell where), and I'll have a closer look. If it still happens, it's not OC.

**Comment by payonel** [comment] 2017-10-04 03:12
thanks for the bug report, closing as it does not repro

**Closed as completed by payonel** 2017-10-04 03:12 UTC
