### ISSUE TITLE
Documentation handler crash with AE2 rv2-beta21

### ISSUE THREAD

**Issue by RobertCochran** [MightyPirates/OpenComputers#978] opened 2015-03-28 23:13 UTC
I had to update AE2 because the new Mekanism was preventing crafting. Apparently, an API or two has
changed between beta 8 (what I had), and beta 21, because now the handler is deciding not to play nice. Here's a crash report - http://pastebin.com/2r5cbh0E

**Comment by ultrasn0w** [comment] 2015-03-29 01:46
I can con confirm this, happens when I press "U" to view the usage of Items in NEI.
Report:
http://pastebin.com/YQVR5HFM

Greetings
ultrasn0w

**Comment by RobertCochran** [comment] 2015-03-29 03:16
From http://ae-mod.info/Downloads/ - "For developer: Deprecates the old usage of the AEItemDefinitions via the direct method access of \* blocks() \* parts() \* items() \* materials() and thus use the new re-direct via definitions(). All definitions are now initialized, no matter what. But SubItems, Items and Blocks are not registered, if by chance are disabled. - thatsIch"

**Comment by fnuecke** [comment] 2015-03-29 11:28
Thanks for the info!

I'm temporarily disabling AE2 integration if version rv2-beta-20 or newer is detected for now, since, while deprecated, the used API methods shouldn't crash IMHO. So I don't want to spend a ton of time of working around that if there's a chance for it to get fixed on AE2's end.

I will look into making version specific calls once the AE2 builds have stabilized (latest builds crash for me when opening a terminal, so I can't really test).

**Comment by fnuecke** [comment] 2015-03-30 16:00
Seems to be fixed in rv2-beta-22, at least I can't reproduce it there. So I enabled integration for newer versions again.

**Comment by ultrasn0w** [comment] 2015-03-30 23:24
After I grabbed the latest OC build from jenkins (1.5.4.490) and the latest AE version (rv2-beta-22), I still experience the crash whenever i look up the usage of an Item :(

**Comment by fnuecke** [comment] 2015-03-30 23:31
Ahh, darn, I think didn't test with controllers disabled...

**Closed as completed** 2015-03-30 23:57 UTC

**Comment by KJA1582** [comment] 2015-03-31 01:07
Got this in a dev setup (latest OC src and dev jar of AE2) and integration for AE2 doesn't get executed (potentially because mod.getMod.isAvaialable returns false).

**Comment by fnuecke** [comment] 2015-03-31 01:26
Very latest? Works fine for me in dev with 18 and - so long as I'm careful not to crash it - 22 (i.e. `getItemsInNetwork` works for me, `getCraftables` I can't test).

**Comment by KJA1582** [comment] 2015-03-31 01:31
1.7.10, but I probably just set it up wrong somehow. Whenever I use IntelliJ's "Minecraft Client" task, it just loads Forge and OC, none of the others. I just put the dev jar of AE2 into the run/mods folder.

**Comment by KJA1582** [comment] 2015-03-31 15:27
It just doesn't initialize the integration when the condign option ignorePower is true. Otherwise it does (at least it initializes) work.

**Comment by fnuecke** [comment] 2015-03-31 16:12
Ahh, that's a very good point actually, and a sneaky little bug. Using a non-power-related mod availability check now. Thanks for making me aware of that!

**Comment by KJA1582** [comment] 2015-03-31 16:50
Your welcome. I simply set the providesPowerower option in ae2 (Mods.scala) to false and it works so far.

**Comment by KJA1582** [comment] 2015-03-31 17:33
BTW, how do I 'publish' things in Intellij so I can stick 'em in a non-dev MC install?

**Comment by fnuecke** [comment] 2015-03-31 19:32
Run `gradlew build`, then the JAR is in the `/build/libs` directory.
