### ISSUE TITLE
server crash  please help

### ISSUE THREAD

**Issue by emilyvans** [MightyPirates/OpenComputers#3149] opened 2019-08-25 13:59 UTC
jar:OpenComputers-MC1.12.2-1.7.4.153.jar
crashlog:https://pastebin.com/drsiswcD

**Comment by payonel** [comment] 2019-08-25 16:11
you provided zero repro steps, and only a crash log. for heaven's sake, i wish people would learn how to make a good bug report and explain the minimal steps required to reproduce a problem.

that said, i believe this is fixed in our latest dev builds. Of course, I could test that if I had any idea what your repro was

dev builds: https://ci.cil.li/
duplicate of #3123

**Closed as completed by payonel** 2019-08-25 16:11 UTC

**Comment by emilyvans** [comment] 2019-08-25 16:12
you only have to join the server

**Comment by SquidDev** [comment] 2019-08-25 16:22
In this case, "only joining the server" entails finding out what pack you're running, installing it, loading the pack, finding what server you're on, joining the server, and only then can we find out the basic information about the crash.

If mod developers ended up doing this for every single bug report, we'd all be wasting a lot of time. Especially in this case as it appears the bug has already been fixed. 

Instead, it's much easier for everyone if you spend an extra 5 minutes writing a good bug report - for instance, include what you did to cause the bug, all your logs (not just your crash report, etc...). It saves everyone time in the long run :).

**Comment by emilyvans** [comment] 2019-08-27 13:34
the problem was that the camping mod that made a server rack crash the server the rack was corrupt
