### ISSUE TITLE
[1.12.2, AL2] Applied Llamagistics makes OC adapter useless

### ISSUE THREAD

**Issue by polyzium** [MightyPirates/OpenComputers#2725] opened 2018-01-13 20:34 UTC
The adapter does not detect any compatible block i place next to it (even vanilla ones like note blocks, but in this case i tried to place an Energy Pylon from DE.) with Applied Llamagistics 2 installed. It just doesn't appear in the components list.
Meanwhile this gets thrown out into server's console. It tries to do the AE2 integration thing when AL2 changed lots of stuff making AL2 and OC conflict with each other.
```
[23:24:55] [Server thread/WARN] [opencomputers]: A component of type 'li.cil.oc.common.tileentity.Adapter' threw an error while being connected to the component network.
java.lang.NoClassDefFoundError: Could not initialize class li.cil.oc.integration.appeng.AEUtil$
	at li.cil.oc.integration.appeng.DriverController$.getTileEntityClass(DriverController.scala:22) ~[DriverController$.class:?]
	at li.cil.oc.api.prefab.DriverSidedTileEntity.worksWith(DriverSidedTileEntity.java:18) ~[DriverSidedTileEntity.class:?]
	at li.cil.oc.server.driver.Registry$$anonfun$2.apply(Registry.scala:102) ~[Registry$$anonfun$2.class:?]
	at li.cil.oc.server.driver.Registry$$anonfun$2.apply(Registry.scala:102) ~[Registry$$anonfun$2.class:?]
	at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259) ~[TraversableLike$$anonfun$filterImpl$1.class:?]
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[ResizableArray$class.class:?]
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) ~[ArrayBuffer.class:?]
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258) ~[TraversableLike$class.class:?]
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270) ~[TraversableLike$class.class:?]
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104) ~[AbstractTraversable.class:?]
	at li.cil.oc.server.driver.Registry$.driverFor(Registry.scala:102) ~[Registry$.class:?]
	at li.cil.oc.api.Driver.driverFor(Driver.java:129) ~[Driver.class:?]
	at li.cil.oc.common.tileentity.Adapter.neighborChanged(Adapter.scala:92) ~[Adapter.class:?]
	at li.cil.oc.common.tileentity.Adapter$$anonfun$neighborChanged$2.apply(Adapter.scala:151) ~[Adapter$$anonfun$neighborChanged$2.class:?]
	at li.cil.oc.common.tileentity.Adapter$$anonfun$neighborChanged$2.apply(Adapter.scala:150) ~[Adapter$$anonfun$neighborChanged$2.class:?]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[IndexedSeqOptimized$class.class:?]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[ArrayOps$ofRef.class:?]
	at li.cil.oc.common.tileentity.Adapter.neighborChanged(Adapter.scala:150) ~[Adapter.class:?]
	at li.cil.oc.common.tileentity.Adapter.onConnect(Adapter.scala:161) ~[Adapter.class:?]
	at li.cil.oc.server.network.Node$class.onConnect(Node.scala:53) [Node$class.class:?]
	at li.cil.oc.server.network.Network$NodeBuilder$$anon$4.onConnect(Network.scala:596) [Network$NodeBuilder$$anon$4.class:?]
	at li.cil.oc.server.network.Network.<init>(Network.scala:30) [Network.class:?]
	at li.cil.oc.server.network.Network$.joinNewNetwork(Network.scala:481) [Network$.class:?]
	at li.cil.oc.api.Network.joinNewNetwork(Network.java:76) [Network.class:?]
	at li.cil.oc.common.inventory.ComponentInventory$class.connectComponents(ComponentInventory.scala:73) [ComponentInventory$class.class:?]
	at li.cil.oc.common.tileentity.Adapter.connectComponents(Adapter.scala:30) [Adapter.class:?]
	at li.cil.oc.common.tileentity.traits.ComponentInventory$class.writeToNBTForClient(ComponentInventory.scala:178) [ComponentInventory$class.class:?]
	at li.cil.oc.common.tileentity.Adapter.li$cil$oc$common$tileentity$traits$OpenSides$$super$writeToNBTForClient(Adapter.scala:30) [Adapter.class:?]
	at li.cil.oc.common.tileentity.traits.OpenSides$class.writeToNBTForClient(OpenSides.scala:47) [OpenSides$class.class:?]
	at li.cil.oc.common.tileentity.Adapter.writeToNBTForClient(Adapter.scala:30) [Adapter.class:?]
	at li.cil.oc.common.tileentity.traits.TileEntity$class.getUpdateTag(TileEntity.scala:116) [TileEntity$class.class:?]
	at li.cil.oc.common.tileentity.Adapter.func_189517_E_(Adapter.scala:30) [Adapter.class:?]
	at li.cil.oc.common.tileentity.traits.TileEntity$class.getUpdatePacket(TileEntity.scala:107) [TileEntity$class.class:?]
	at li.cil.oc.common.tileentity.Adapter.func_189518_D_(Adapter.scala:30) [Adapter.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288) [ot.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:273) [ot.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115) [ou.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

**Comment by payonel** [comment] 2018-01-13 22:03
probably Applied Llamagistics is using the same namespaces or mod info as ae2, and that borks the adapter integration with oc. I've dealt with issues like this before and to be honest, it generally is a weird hack at best to protect from this issue. This is simply an incompatibility issue and we won't fix. it is the fault of a mod reusing the same namespace as another mod trying to be a drop in for it, or a fork of it, and not using all the same class names. Specifically, AL2 is using the AE2 mod name, but does not have li.cil.oc.integration.appeng.AEUtil. 
closing as won't fix, sorry

**Comment by skyem123** [comment] 2018-01-15 14:31
To try to understand what's happening, when does the error message appear in the console? When the block is placed, or when the game starts, or both?

**Comment by polyzium** [comment] 2018-01-15 14:35
When i place the adapter block next to a compatible block to interact with @skyem123

**Comment by skyem123** [comment] 2018-01-15 14:50
So... The adapter block is tripping over the AE API when trying to do anything with any block... Interesting, I don't think I can help though. :/

**Comment by polyzium** [comment] 2018-01-15 14:53
the Applied **Llama**gistics API, they changed lots of stuff thus breaking AE2 integration for OC thus breaking the adapter block completely. As a temporary solution i had to use Refined Storage which is buggy asf

**Comment by skyem123** [comment] 2018-01-15 14:57
Well... This problem is how AL implemented it and how OC uses it, basically as far as OC is concerned, it's the code it has to interact with AE that it crashes on.

**Comment by polyzium** [comment] 2018-01-15 15:03
Tho AL author said that it includes its own OC driver, it still crashes despite im using latest revisions of both OC and AL. See the reference above

**Comment by skyem123** [comment] 2018-01-15 20:26
yes I can see that. 😬 
The problem is the interaction between the two mods, not one individual mod.
From what I can tell, OC tries to do something because it thinks it sees AE2, which crashes because it's actually AL, which has a different implementation of the API... because AE2 changed its API and AL uses the original API and OC uses the new API?

I do wonder if there's a way to support both without breaking things, however I don't have the knowledge or the time to work this out, I'm afraid.

**Comment by payonel** [comment] 2018-01-15 20:36
Tell you what, I'll investigate protecting from one bad apple causing the adapter to fail to communicate with anything, but as for supporting a mod that reuses the same mod name as another -- I would rather not.

**Comment by thiakil** [comment] 2018-01-16 00:39
AL didn't change anything, which is the problem, as AE2 did change their api after release.

All that should be needed for AL is the ability to disable the built in driver (should it not already be possible), or for the crash to not completely screw over the adaptor - which should already be the case for a mod that allows external integration.

AL has a built in driver.

**Comment by asiekierka** [comment] 2018-07-04 18:15
This can be closed, Applied Llamagistics has been abandoned by its author.

**Closed as completed** 2018-07-04 19:55 UTC

**Comment by thiakil** [comment] 2018-07-05 04:21
`li.cil.oc.api.prefab.DriverSidedTileEntity.worksWith` (or what calls it) should still be catching exceptions.
