### ISSUE TITLE
There were errors running the class transformer

### ISSUE THREAD

**Issue by BlueAccords** [MightyPirates/OpenComputers#2050] opened 2016-09-06 01:36 UTC
Ran into this error upon the creation of a new instance while trying to automatically generate terrain following [this](https://www.youtube.com/watch?v=7WSMgOVsnCU) video.  

Additional Info:
- Local single player
- running [All the mods](https://minecraft.curseforge.com/projects/all-the-mods) modpack
- `Forge 12.18.1.2075`
- `OptiFine 1.10.2 HD U C3`
- Operating System: OSX El Capitan 10.11.6
- MultiMC launcher

Here is the [latest.log](https://gist.github.com/BlueAccords/beb15845eb337cb95c974005f60d5288)  

Not sure where to find `fml-server-latest.log`.

**Comment by 7OOTnegaTerces** [comment] 2016-09-07 22:39
I had the same error.  My issue was fixed by updating to this OC build: http://ci.cil.li/job/OpenComputers-dev-MC1.10/lastSuccessfulBuild/artifact/build/libs/OpenComputers-MC1.10.2-1.6.0.31-dev.jar

**Comment by Vexatos** [comment] 2016-11-14 18:44
`fml-server-latest.log` or `fml-client-latest.log` are in your `logs/` directory.

This is most likely a duplicate of #1998 or #2014 (or both), so I'm closing this for now. It should not appear using the latest release of OpenComputers (1.6.0).

**Closed as completed by Vexatos** 2016-11-14 18:44 UTC
