### ISSUE TITLE
[MC1.9.4] Incorrect color on lines after cursor

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#1935] opened 2016-07-05 18:04 UTC
Using OpenComputers on the BTM server, lines after the cursor are flashing random colors, happens in the editor and in shell. Only I am getting this apparently but I haven't been getting this before so it might be a regression/my card.

My old card as usual: ATI Radeon HD 4770 in Ubuntu Linux

A recording of the issue is provided:
[https://www.youtube.com/watch?v=yQYNgEJltck](https://www.youtube.com/watch?v=yQYNgEJltck&t=7)

**Comment by malgoe** [comment] 2016-07-22 11:17
I got the same problem. I'm on OpenComputers-MC1.10.2-1.6.0.21-dev.

**Comment by gamax92** [comment] 2016-07-22 22:23
@malgoe What graphics card and OS?

**Comment by malgoe** [comment] 2016-07-24 10:47
Ingame: Tier 3 graphics card and openos
On my real computer: NVIDIA GeForce GT 730M / Intel HD Graphics 4600 and Ubuntu

**Comment by exaskye** [comment] 2016-07-26 23:26
My guess is this caused by OpenComputers accessing GL11 directly instead of going through GlStateManager. (just do a grep on the codebase for `GL11` — there's not many places it gets used for things that normally go through the state manager, but it _does_ get used.)

A number of places also seem to rely on popAttrib/pushAttrib, but those are dummied out in RenderState, which is likely causing the OpenComputers renderers to leak state.

(Note that random TEs near the screen _also_ flash random colors in sync with the screen, like signs, banners, etc.)

**Comment by fnuecke** [comment] 2016-07-27 18:38
As it's happening _within_ the renderer, I'm actually inclined to believe it's _because_ it's using the GlStateManager, and the issue lies in that not playing nice with being used in display lists. I'll rip out uses of GlStateManager in the text renderer (and reset the state manually) as an experimental fix. I'm afraid I can't reproduce it, so someone will have to tell me if it worked or not.

**Comment by exaskye** [comment] 2016-07-27 19:19
Oh, if you're changing colors or textures in the display list, I know for a fact that causes state manager desyncs. You can force a state manager resync with something like:

```
GL11.glColor3f(1, 1, 1);
GlStateManager.color(1, 1, 1);
```

(and similar for disable/enable/etc)

**Comment by fnuecke** [comment] 2016-07-27 20:03
Aye, I already did that after the list, exactly because of that. Here the problem was during the list execution, which is hopefully fixed now (since I'm not using the state manager _in_ the list for setting the colors anymore).

**Closed as completed** 2017-10-08 00:25 UTC
