### ISSUE TITLE
Game says to report this

### ISSUE THREAD

**Issue by gilfort** [MightyPirates/OpenComputers#2097] opened 2016-10-17 08:04 UTC
As i got into a world, there was a message in the chat, that i should report that something did go wrong and to provide the latest.log. So here it is
http://pastebin.com/8t3VZ5zx

hope this helps in any way.

**Comment by Vexatos** [comment] 2016-11-14 18:48
This is most likely a duplicate of #1998 or #2014 (or both), so I'll be closing this for now. It should not appear anymore using the latest OpenComputers release (1.6.0).

**Closed as completed by Vexatos** 2016-11-14 18:48 UTC
