### ISSUE TITLE
Bug "os.getenv"

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2012] opened 2016-08-10 15:29 UTC
1. Launch computer (Computer Case(Creative), Internet Card, APU(Creative), Memory 2x3.5 and HDD 4MB)
2. Open Lua in shell
3. Input "for k,v in os.getenv do print(k, v) end" and press "Enter"
   Screen turn off.

**Comment by payonel** [comment] 2016-08-10 17:42
first of all, i think what you wanted to see was `for k,v in pairs(os.getenv()) do print(k,v) end`

secondly - if you use an analyzer, are you seeing "too long without yielding" ?

**Comment by ghost** [comment] 2016-08-10 20:12
1. Oh yeah, perhaps that's what I wanted to see
2. no

By the way my monitor was not enough because of this energy. I connected more.
In an endless loop displays a message "table 00000000397EED9D0 nil"

**Comment by Fingercomp** [comment] 2016-08-11 16:15
This is a standard Lua behaviour, and not a bug.

``` lua
for a, b, c in somefunc do
  -- some code --
end
```

Each iteration `func` is called, and its output values are assigned to `a`, `b`, and `c`. If first value is `nil`, `for` loop ends.
Basically, the code above is equal to the following code:

``` lua
while true do
  local a, b, c = somefunc()
  if a == nil then
    break
  end
  -- some code --
end
```

In your case, the `for` loop calls `os.getenv()`, and gets a table of environment variables. As the output is always a non-nil value (a table), the `for` loop never ends.

**Comment by payonel** [comment] 2016-08-11 17:50
as @Fingercomp said, this is correct lua behavior. Thanks @FlexMC for reporting that it was a "not enough power" scenario. Closing as "will not fix"

**Closed as completed by payonel** 2016-08-11 17:50 UTC
