### ISSUE TITLE
Error running the class transformer

### ISSUE THREAD

**Issue by McSassyK** [MightyPirates/OpenComputers#2132] opened 2016-11-14 23:54 UTC
I'm running HermitPack and get this error when I log on: "OpenComputers" There were errors running the class transformer. Thanks!

[fml-client-latest.txt](https://github.com/MightyPirates/OpenComputers/files/590778/fml-client-latest.txt)

**Comment by payonel** [comment] 2016-11-15 04:18
Duplicate of #2014 

```
[17:43:32] [Client thread/WARN] [OpenComputers/OpenComputers]: Missing implementations for interface mekanism.api.IMekWrench, skipping injection.
[17:43:32] [Client thread/WARN] [OpenComputers/OpenComputers]: Missing implementation of canUseWrench(Lnet/minecraft/item/ItemStack;Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/util/math/BlockPos;)Z
```

**Comment by payonel** [comment] 2016-11-15 04:19
please use our most recent releases: https://github.com/MightyPirates/OpenComputers/releases

**Closed as completed by payonel** 2016-11-15 04:18 UTC

**Comment by McSassyK** [comment] 2016-11-15 13:09
This is part of HermitPack. Is this something I can update or don't they have to?

**Comment by payonel** [comment] 2016-11-16 06:18
If you play on a server the server would have to update their pack as well.

We need the HermitPack maintainers to update the default version of oc to our release version
I found that in the curse launcher, when you are looking at your hermitpack optiions, you can edit the profile and unlock it. Then, list the mods in the pack and select opencomputers, and then click on "versions". From there, click the down arrow to the right of our release version.
