### ISSUE TITLE
[1.12.2] Errors running class transformer

### ISSUE THREAD

**Issue by jesmores** [MightyPirates/OpenComputers#2617] opened 2017-11-08 04:04 UTC
latest.log -> https://pastebin.com/v5jC3RUM

It's a custom pack, running on Forge 14.23.0.2531
OpenComputers version 1.12.1-1.7.0.20

Can provide modlist if necessary.

Something I need to worry about, or can I continue playing my world? I don't have any OC blocks placed in the world yet.

**Comment by payonel** [comment] 2017-11-08 04:42
duplicate of #2616

**Closed as completed by payonel** 2017-11-08 04:42 UTC

**Comment by jesmores** [comment] 2017-11-08 07:11
But ... I'm not running sponge. At least not that I know of. I built the pack myself using the Curse/Twitch launcher. It's a single player instance.

**Comment by payonel** [comment] 2017-11-08 07:24
I'm looking at all the "spongepowered" in the stack traces

**Comment by jesmores** [comment] 2017-11-08 08:24
Is it possible one of my mods is somehow using sponge APIs (or trying to) without me running a sponge server? Like I said, it's a single player instance, no server involved.

**Comment by jesmores** [comment] 2017-11-08 08:33
I think I've figured it out - Did a search for anything that contains the string "spongepowered" in my instance folder and found it in the MalisisCore jar (required dependency for MalisisDoors mod). Disabled both mods and the error no longer appears.

Thanks!

**Comment by thiakil** [comment] 2017-11-09 00:38
Looks like Malisis uses the Mixin library (which is used by / made for Sponge but not required to be part of), and the Mixins can't handle Scala or otherwise what OC does in the CoreMod with removing Scala classes.

**Comment by brisingraerowing** [comment] 2017-11-11 08:25
This is an issue between MalisisCore and Lite Loader. You need to update Lite Loader to fix this (it was using an older Sponge Mixins library from what I can tell, and the API was different).

**Comment by jesmores** [comment] 2017-11-11 08:59
Does Lite Loader normally get added automatically to a pack created using the Twitch launcher? I didn't explicitly add it otherwise.

**Comment by brisingraerowing** [comment] 2017-11-11 17:46
I don't use the Twitch Launcher (never could get it to work), so I wouldn't know. If you use a LL mod from Curse (of which there are several) it might get installed.

**Comment by thiakil** [comment] 2017-11-12 01:39
The stacktace shows the Mixin classes are coming from the Malisis jar, so I'm doubtful it has anything to do with LL

**Comment by brisingraerowing** [comment] 2017-11-12 01:54
The LiteLoader team confirmed the issue. LiteLoader's version gets loaded first, and due to the incompatible API, Malisis crashes later in the loading cycle. 

[Issue Link](http://develop.liteloader.com/liteloader/LiteLoader/issues/36)
