### ISSUE TITLE
3D Prints - semi-transparency

### ISSUE THREAD

**Issue by NickNackGus** [MightyPirates/OpenComputers#2189] opened 2016-12-18 02:23 UTC
If 3D printing a block with semi-transparency in their textures, such as vanilla Minecraft's stained glass texture, semi-transparent pixels render as completely transparent. Tested in Opencomputers 1.6.0.4 for Minecraft 1.10.2, running Java 1.8.0_111 (64bit) in Ubuntu 16.04 LTS.

**Comment by NickNackGus** [comment] 2016-12-22 16:34
Retested this issue with and without MCMultipart for Opencomputers 1.6.1.6. Also noted that while the placed 3D print is fully transparent where the original texture is partially transparent, the held view of the print is fully opaque.
[Example Picture](http://imgur.com/a/uIJyE)
[Example .3dm File](http://pastebin.com/A8wXTr3Q)

**Comment by asiekierka** [comment] 2022-09-02 20:31
Duplicate of https://github.com/MightyPirates/OpenComputers/issues/2938 - although this one technically came first, the latter has more information.

**Closed as completed by asiekierka** 2022-09-02 20:31 UTC
Labels: bug
