### ISSUE TITLE
OpenComputers 1.12.2 Extremely laggy

### ISSUE THREAD

**Issue by Lokii270** [MightyPirates/OpenComputers#3402] opened 2021-01-16 05:48 UTC
I'm running OpenComputers on 1.12.2 with Forge 14.23.5.2854, Java 1.8.0_275 and OpenComputers 1.7.5.192.

When booting a PC, it often fails to boot (too long without yielding error). During boot, my game drops to about 2fps, or about 20fps with major stutters.

If it does manage to boot, it runs at about 20fps with major stutters.

I'm running the default config, with no other mods. I've tried on several different hard drives, different java versions and with other mods involved.

My specs are i5-9400F, RTX 2060 and 32GB of RAM.

Please let me know how I can fix this.

**Comment by AR2000AR** [comment] 2021-03-27 22:49
> My specs are i5-9400F, RTX 2060 and 32GB of RAM.

Check the jvm argument. Your game may not be able to use more then 1 or 2 GB of RAM by default. You can see minecraft's RAM usage form the F infos (fist few line in the to right corner)

**Comment by payonel** [comment] 2021-05-11 02:54
oc machines really aren't supposed to tax your system like this. can you start a creative world, look at a block in front of you and run /oc_sc -- boot up that machine and report

**Comment by voice-at-magicmirror** [comment] 2021-07-12 19:24
Looks like stutters are happens at the same time with screen updates. In my observations even just cursor blinking cause stutters. Here is [video demonstration](https://files.magicalmirro.red:5443/upload/42b519c773815ac7356029d017cd3227b98253d6/kYNUb1jrxfv0yO8ty3lNTfBxJwBkStJvpd36f6UY/simplescreenrecorder-2021-07-12_22.13.02.mkv)

**Comment by payonel** [comment] 2022-08-31 08:02
@Lokii270 I cannot repro this behavior. I think we need to close this ticket unless we can learn more about the setup
Is there anything unusual about your computer hardware? The debug screen shows a more than adequate cpu and gpu, but you've only allowed ~1GB of ram for the game? And just in this simple case you're using over 50% of the ram you can give the game. Even when I use these unreasonable constraints my systems cannot reproduce this issue.

Is anything virtualized? Are you streaming the game? Was your system using swap space ram from other applications at the time?

Closing without more info

**Closed as completed by payonel** 2022-08-31 08:02 UTC
Labels: bug
