### ISSUE TITLE
[1.10.2] Nanomachines getName() causes crash

### ISSUE THREAD

**Issue by TheTokenMaster** [MightyPirates/OpenComputers#2242] opened 2017-01-27 15:12 UTC
Sorry to post this without the crash info, I don't have it on me at present.
I send the getName() request and then the game crashes before I receive the response.
I will try to get the crash info soon.

**Comment by TheTokenMaster** [comment] 2017-01-27 15:39
I think this may be down to mod interaction, I've tried it on another computer with just OpenComputers and it didn't crash, however that other computer is using Linux not Windows. I will try it on the computer where the bug first happened.

**Comment by Vexatos** [comment] 2017-01-27 15:51
Most likely a duplicate of #2220. Next time, please provide the versions of Minecraft and OC you are using, too.

**Closed as completed by Vexatos** 2017-01-27 15:51 UTC
