### ISSUE TITLE
"lua" not works OC 1.7.6

### ISSUE THREAD

**Issue by Bumer-32** [MightyPirates/OpenComputers#3548] opened 2022-09-01 10:04 UTC
after update to OC 1.7.6 i`m boot from new OpenOS and taped "lua"
as result:

![image](https://user-images.githubusercontent.com/79054301/187888585-1ea1606d-e308-40b5-9101-7e605842b4ed.png)

LOL: if computer spawned by /oc_sc all works

**Comment by ProgramCrafter** [comment] 2022-09-01 15:52
Workaround for this issue: execute `require('core/full_buffer')`, possibly by creating file with this contents on another OC computer and somehow transferring it to affected computer.

**Comment by Ocawesome101** [comment] 2022-09-01 19:31
i can't reproduce this even with only 192KB of RAM.

**Comment by Ocawesome101** [comment] 2022-09-01 19:31
can you give more details on your setup please?

**Comment by payonel** [comment] 2022-09-02 04:10
@Bumer-32 I need a world save or a reliable repro for this please

**Comment by DoubleHypercube** [comment] 2022-09-02 07:36
@payonel I have this bug on the latest CF release, the "Creatix" robot from OC's tab seems to have the bug
not sure if just me for robots though, but there is also an unrelated (?) reflection error in my logs

**Comment by asiekierka** [comment] 2022-09-02 09:03
Confirmed, can reliably reproduce. Reverting https://github.com/MightyPirates/OpenComputers/commit/c9530ae0dd9a2426eab8cedef6c241dbb5086c70 fixes the issue.

**Comment by Bumer-32** [comment] 2022-09-02 11:41
lol
I don't know why it works, but it works on the computer now
(seriously?)
but it doesn't work on Creatix
[world.zip](https://github.com/MightyPirates/OpenComputers/files/9477547/world.zip)

**Comment by Ocawesome101** [comment] 2022-09-02 12:58
if you assemble a robot from scratch is it still broken?

**Comment by Bumer-32** [comment] 2022-09-02 15:13
yes

By the way, the creative (from inventory) tablet does not work at all (hand made tablet works)
![2022-09-02_18 10 04](https://user-images.githubusercontent.com/79054301/188180243-55de9122-a88a-4c57-bd26-486ed2c2965f.png)

**Comment by payonel** [comment] 2022-09-03 00:17
thanks everyone. i'll root cause this and put out a proper fix asap

**Comment by payonel** [comment] 2022-09-03 20:50
fixed by revert 912d93efb0d84425c896498b8944e7584e3b661d

**Closed as completed by payonel** 2022-09-03 20:50 UTC
Labels: bug-priority
