### ISSUE TITLE
redstone_changed event bug

### ISSUE THREAD

**Issue by Nex4rius** [MightyPirates/OpenComputers#2228] opened 2017-01-18 18:41 UTC
The redstone_changed event doesn't work with bundled cables.
It shows us:
1) "redstone_changed"
2) UUID
3) side
4) previous signal strength
5) new signal strength

But it treats all 16 colored cable signals as if they are are the same color and it doesn't even tell us which color changed.

This <a href="https://www.youtube.com/watch?v=g7OBYfYv96E">video</a> shows it better.

OpenComputers-MC1.7.10-1.6.1.11-universal

**Comment by xarses** [comment] 2017-01-18 19:16
Sounds like a dupe of #1385

**Comment by payonel** [comment] 2017-12-11 14:12
I agree this is a duplicate of #1385

**Closed as completed by payonel** 2017-12-11 14:12 UTC
