### ISSUE TITLE
[GT5u] robot.swing returns wrong response with some blocks

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1791] opened 2016-05-03 17:19 UTC
[In #1766 I thought all tools for GT5u where not working, when I did more testing I found it was user error, now I've gone through some iterations and see that there is still some oddness with torches that is screwing with my head]

I have two kinds of torches, the vanilla torch, an a Carpenters torch from Carpenters blocks

I expect that the following table reflects how my tools work as this is how they work for Steve

|  | Iron Pick(v) | GTu Pick | hand |
| --- | --- | --- | --- |
| Torch (v) | True | False | True |
| Carpenters Torch | True | False | True |

Given this table, I'd expect identical results from the robot however, they are 

|  | result | reason | world state | expected state |
| --- | --- | --- | --- | --- |
| **Iron Pick(v)** |  |  |  |  |
| Torch (v) | true | block | harvested | harvested |
| Carpenters Torch | true | block | harvested | harvested |
| **GT5u Pick** |  |  |  |  |
| Torch (v) | **false** | air | **harvested** | **unchanged** |
| Carpenters Torch | false | block | unchanged | unchanged |
| **Hand** |  |  |  |  |
| Torch (v) | true | block | harvested | harvested |
| Carpenters Torch | true | block | harvested | harvested |

I still don't understand why the robot can harvest one, detect returns `passable` for both Items

This effect of vanilla torches can be seen in other less than full block aka `passable` items, with similar results 

|  | result | reason | world state | expected state |
| --- | --- | --- | --- | --- |
| Gardens from Pam's Harvest Craft | false | block | harvested | unchanged |
| Every tree sapling I've tested | false | block | harvested | unchanged |
| Wheat | false | air | harvested | unchanged |
| Dandelion | false | block | harvested | unchanged |

To further muck with my brain, while most of these calls return `false` and `block` but in some cases we get `air` back instead. So far this is a torch attached to the side of a block (torches on the top return `block`), and Wheat

**Comment by fnuecke** [comment] 2016-05-11 20:02
The agents use whatever the item's respective methods return, so this sounds like the GT tools return something weird / non-standard / unexpected. Would probably need specific integration to work around.

**Comment by payonel** [comment] 2018-03-18 04:13
robots are now able to use the GT5u picks to harvest things they previously could not, though strangely they are also able to harvest plants they previously could not

Honestly, this is good enough for me. There must be some rather custom player swing actions that GT is doing, and we'd have to have a duplicate of that for the robot agent code.

It might have been closed some time ago, but 4a83d4426dc032a58b7b080f8a9533343af83f8b is probably related to these changes.

**Closed as completed by payonel** 2018-03-18 04:13 UTC
