### ISSUE TITLE
Recipes requiring chests require a Magical Chest if Essential Craft is installed

### ISSUE THREAD

**Issue by flarn2006** [MightyPirates/OpenComputers#1399] opened 2015-09-03 01:49 UTC
This occurs with computer cases and microcontrollers. I haven't checked anything else; I don't know if anything else requires a chest as an ingredient.

But yeah, I tested and it doesn't work if I just use a regular vanilla chest like what normally works. If Essential Craft is installed, it only works with a Magical Chest from said mod.

**Comment by Kubuxu** [comment] 2015-09-03 06:54
Report that to EssentiaCraft. AFAIK OpenComputers just uses oredict name for `chest`.

**Comment by fnuecke** [comment] 2015-09-05 23:01
Yeah, OC looks for strings in recipes (such as is the case for chest here) in the oredict first, then looks for items with that name and so on. So it'd appear that EC replaces the oredict entry for chest with a magical chest? Which'd be odd either way, assuming that's what's actually happening.

**Comment by foone** [comment] 2015-10-03 23:34
I raised a related issues on EssentialCraft to try and fix it over there, but having looked at their code they're just doing the standard thing and adding the magical chest to the oredict under "chest".

I'm not great on Scala but I think there's something going on with one of [the fallbacks for parseIngredient](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/common/recipe/Recipes.scala#L349)

Perhaps [the fallback that checks for an unlocalized name of "chest" ](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/common/recipe/Recipes.scala#L404) is breaking because their magical chest has an unlocalized name of just "chest"?

**Comment by flarn2006** [comment] 2015-10-03 23:36
@foone: Are you saying the issue actually is with OpenComputers? If so, I think this issue should be reopened.

**Comment by foone** [comment] 2015-10-03 23:40
Yes, I believe it is. 
My current workaround is changing the recipe file to read "minecraft:chest" so that it doesn't look it up by oredict/trigger this bug.

**Comment by flarn2006** [comment] 2015-10-03 23:41
If you've confirmed that works, I suggest you submit a pull request to fix it.

**Comment by foone** [comment] 2015-10-03 23:47
That works but has the side-effect of breaking the oredict use, which isn't optimal. Any sort of chest should be usable in these recipes, such as trapped chests or other mod's chests.

**Comment by foone** [comment] 2015-10-04 00:16
The same problem is happening with glass: Screens are requiring Magical Fortified Glass from EE3.

**Comment by flarn2006** [comment] 2015-10-04 00:23
@fnuecke, can you please reopen the issue?

**Comment by foone** [comment] 2015-10-04 00:35
I've confirmed that this bug happens with only EE3 + OpenComputers installed (at latest versions), so there's no other mods interfering. Other mods' recipes with chests are not being affected by this, only OpenComputers.

**Comment by fnuecke** [comment] 2015-10-04 09:24
Gah, looks like in all my tests some other mod already added vanilla chests to the oredict, but those mods don't (and it's not in there by default).

**Comment by gjgfuj** [comment] 2015-10-04 09:25
So you add vanilla chest to the oredict and it'd work?

**Comment by Kubuxu** [comment] 2015-10-04 09:25
They are in oreDict: https://github.com/MinecraftForge/MinecraftForge/blob/3331d2a496dcd69c0728539d740f6cf4bb46d98c/src/main/java/net/minecraftforge/oredict/OreDictionary.java#L130

**Comment by fnuecke** [comment] 2015-10-04 09:25
Exactly, that's my plan.

**Comment by fnuecke** [comment] 2015-10-04 09:26
Uhh, not in my version of Forge :X

**Comment by Kubuxu** [comment] 2015-10-04 09:27
It was in December: https://github.com/MinecraftForge/MinecraftForge/commit/3c936e88f2bc7144b2d2b1f7f1dab0fa0a67256b

**Comment by fnuecke** [comment] 2015-10-04 09:27
Kubuxu: that's 1.8, we're talking 1.7.

**Comment by Kubuxu** [comment] 2015-10-04 09:27
Gosh really they didn't port that.
Oh Lex...

**Comment by gjgfuj** [comment] 2015-10-04 09:29
Nah of course not. Thatd be dumb! And we all know lex is a smart man.

**Comment by fnuecke** [comment] 2015-10-04 09:38
The actual argument is probably closer to "that'd encourage staying on 1.7". But yeah, that's kinda meh, too, the focus should be on getting people wanting to be on 1.8, not them wanting to get away from 1.7 :p 

Oh well. [/off topic rant]

**Comment by fnuecke** [comment] 2015-10-04 09:39
Should be fixed in [build 779](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/779/), lemme know if it isn't.

**Comment by foone** [comment] 2015-10-04 23:40
@fnuecke It fixes chests, but not the other broken items.
I checked all the recipies (according to NEI) and the only other broken items are glass and ender pearls

**Comment by fnuecke** [comment] 2015-10-05 08:00
Oh, there's more :X Is that all then? Or anything else besides glass (panes?) and ender pearls?

**Comment by gjgfuj** [comment] 2015-10-05 09:22
Close reopen close reopen.

**Comment by foone** [comment] 2015-10-05 12:26
just glass (blocks, not panes) and ender pearls. Nothing else looked wrong in the recipes.

**Comment by fnuecke** [comment] 2015-10-05 21:25
Let's see how many more times we can reopen this :P

**Closed as completed** 2015-10-05 21:24 UTC
