### ISSUE TITLE
Pasting stops at around line 257 if pasting more than 257 lines

### ISSUE THREAD

**Issue by phanski33** [MightyPirates/OpenComputers#3084] opened 2019-04-07 19:49 UTC
I'm trying to paste this: https://pastebin.com/jdaM8FKG and everytime it stops pasting at around line 257. I've changed the maxClipboard value but it did nothing.

**Comment by UV-Husky** [comment] 2019-04-17 07:16
You can use the built-in Pastebin program. Add internet card to the computer => 
use command `pastebin get <code> <filename>`

**Comment by payonel** [comment] 2019-06-06 04:27
@NiamiTV you've found an interesting problem in our code with clipboard events
1. we have a `maxClipboard` setting in the config that is intended to limit the size of the string you can send via clipboard. This is done to limit the packet size load from clients to servers. However, this setting was never used, and is by default 1024. To actually start using this limit would definitely cause a lot more grief that trouble it would solve, as 1024 chars is a very restricted clipboard, and our users have enjoyed no such limit this entire time. I have thus opted to removed this setting in our config.
2. Our code does break up very large clipboard messages from clients to servers, and puts a delay on sending each part, but does send all of the parts. This code is working and shall remain
3. On the server side, we buffer the clipboard parts as signals in the "computer signal queue". The running machine state (the computer) pulls the signals, and openos seeing the "clipboard" events, pastes the text into your file you have open for edit. However,
3.a) the clipboard text is broken in lines, and each line is put into its own clipboard signal. Your example file is 1331 lines long, and thus would generate 1331 "clipboard" events
3.b) our machine signal queue handler is hard coded to limit the number of queued signals at 256.

And bam, you have the 256 line limit issue. Sometimes (most times?) you see 257 because machine state wakes up soon enough to get at least 1 of the signals before the queue is maxed out, discarding the remaining 1074 lines.

I tested creating clipboard events that pack more than a single line of text. This mitigates part of the problem, but it is also possible that such a solution could cause unanticipated side affects in the community that isn't expecting this change in clipboard data

I have decided to pull out the hard coded value of 256 for our max queue size, and put that in our configuration. It will default to 256 so as to not interfere with what the community has come to expect. Thus, with the fix for this bug, if you wanted to paste such a large file, you'd want to change the oc config on the server, and change `computer.maxSignalQueueSize` from its default 256 to something more like 2048

The alternative solution is to download the file in-game, such as by using the pastebin tool @SpaceBeeGaming suggested.

**Comment by Cre8or** [comment] 2022-08-27 08:49
I know this is an old (and closed) issue, but I suspect the fix described by @payonel is not working as intended.

https://github.com/MightyPirates/OpenComputers/blob/b8234144472038adfd474b469cce6eed5ecb3b59/src/main/resources/application.conf#L278

If I understand this correctly, the intention is for `maxSignalQueueSize` to be *at least* 256. Clients shall be able to increase this limit to a higher value (which corresponds to what Payonel described in the comment above).

However, in my modpack, I've been unable to increase this limit beyond the default value. I've tried pasting a file with ~300 lines and the insertion stopped at 256. It would seem that this is because, in the code implementation, the limit is calculated using `min` instead of `max`:

https://github.com/MightyPirates/OpenComputers/blob/b8234144472038adfd474b469cce6eed5ecb3b59/src/main/scala/li/cil/oc/Settings.scala#L472

The end of this line should probably read:

```kt
[...] config.getInt("computer.maxSignalQueueSize") else 256) max 256 
```

...so that the greater value of the two is used.

I'll attempt to fix this myself for my modpack (for personal use only!), but still wanted to bring this up to your attention so it can be resolved in future releases. And sorry for the issue bump. 😄

**Comment by payonel** [comment] 2022-08-27 17:19
There is something about putting the operator/function name `min` or `max` between two numbers that I really dislike about scala. I'm probably the only one that makes this mistake. Thanks  @Cre8or

**Closed as completed** 2022-08-27 17:48 UTC
