### ISSUE TITLE
[1.11.2] OpenComputers does not recognizing BuildCraft as a viable energy source

### ISSUE THREAD

**Issue by mezz** [MightyPirates/OpenComputers#2376] opened 2017-05-10 20:15 UTC
![2017-05-10_13 14 35](https://cloud.githubusercontent.com/assets/916092/25919184/be60f2ac-3582-11e7-82cf-fc6f95085e06.png)

The new Buildcraft alpha is loaded but OC does not detect it.

**Comment by NickNackGus** [comment] 2017-05-10 20:17
Last I checked, OpenComputers is not currently enabling support for mods that are in alpha. Once it's out of alpha, support may be re-added. If I'm wrong, please correct me.

**Comment by xarses** [comment] 2017-05-10 21:42
Dupe of #2338 and possibly resolved by #2369 (not merged)

**Comment by Vexatos** [comment] 2017-05-14 13:36
Essentially a duplicate of #2338.

**Closed as completed by Vexatos** 2017-05-14 13:36 UTC
