### ISSUE TITLE
Client crash when placing Drone

### ISSUE THREAD

**Issue by henkaa** [MightyPirates/OpenComputers#2198] opened 2016-12-23 11:24 UTC
Environment: Curse client running FTB Direwolf 20 1.1.4 with Java 8 
To reproduce:

* Built parts drone tier1, cpu, ram, eeprom, card with extra instructions (do not have the name atm but was tier 1), item storage upgrade and database upgrade, The eeprom was blank with Lua. (eeprom + book)
* Assembled parts in the assembler.
* Placed drone on the ground.

This makes the client crash. When I try to restart the client, I see the world for a breif second (if lucky), then the client crash again.

Worth to know. Other players on the server does not seem to have been affected what I know of.

The following report is on FTB: [https://forum.feed-the-beast.com/threads/drones-crashes-client.207356/](https://forum.feed-the-beast.com/threads/drones-crashes-client.207356/)

The following attachment is the Crash report from the last try to restart the client: [http://paste.feed-the-beast.com/view/dfc2dd42](http://paste.feed-the-beast.com/view/dfc2dd42)

**Comment by Vexatos** [comment] 2016-12-23 16:39
The log specifically mentions Waila, so it might only crash if you are looking at the drone with Waila enabled. Could you try verifying that?

**Comment by Vexatos** [comment] 2016-12-23 16:39
The log specifically mentions Waila, so it might only crash if you are looking at the drone with Waila enabled. Could you try verifying that? Remove Waila from the mod pack and see if it stops crashing.

I do not know what's causing this issue; an error like this shouldn't be possible.

**Comment by payonel** [comment] 2016-12-23 16:45
Schrödinger's drone

**Comment by Vexatos** [comment] 2016-12-23 16:48
Essentially, the stack trace means that the drone's target coordinate suddenly is a.... boolean value instead of a number. This obviously is not done anywhere in OC itself.

**Comment by Vexatos** [comment] 2016-12-23 16:56
@henkaa Also, could you check whether it occurs with a drone gotten from the creative tab?

**Comment by Vexatos** [comment] 2016-12-23 16:59
@henkaa Could you check whether it occurs with a drone gotten from the creative tab? Does it still occur using the latest release of OpenComputers (1.6.1)?

**Comment by Vexatos** [comment] 2016-12-23 17:08
If none of the things above shed any light onto the issue, you could try finding the smallest set of mods required for the bug to occur. With only OpenComputers, Waila and with or without Wawla (all of which are mentioned in the crash) I am not able to reproduce this, so it might be some other mod entirely causing it. I apologize for the inconvenience, but, as stated, I am unable to reproduce the bug myself.

![See here.](https://thumbs.gfycat.com/ClosedAnchoredIsabellineshrike-size_restricted.gif)

**Comment by Landrash** [comment] 2016-12-23 23:32
[This](https://forum.feed-the-beast.com/threads/opencomputer%E2%80%99s-drone-entity-crashes-player.201920/) seems to be the same issue with the same pack.

**Comment by Dimtree** [comment] 2016-12-25 00:50
I can reproduce the crash with drones both custom-built and spawned from the creative tab.

I can also confirm that you will only crash if you look directly at the drone. Placing it with the Actually Additions Auto-Placer succeeds and the drone will function as expected.

As for the crash when re-logging, it seems to be that you log back in looking at the same drone that crashed you in the first place. As a workaround, you can "kill" the drone entity with:
`/kill @e[type=OpenComputers.Drone]`

Looking in the logs, there's a NullPointerException saving the drone entity's NBT data. Specifically it seems the entity's vehicle is null and WAILA/WAWLA doesn't like that.

I've attached my client log (no errors server-side).
[crash-2016-12-24_19.28.52-client.txt](https://github.com/MightyPirates/OpenComputers/files/672012/crash-2016-12-24_19.28.52-client.txt)

**Comment by Vexatos** [comment] 2016-12-25 01:01
@Dimtree Thanks for the info. Does the issue still occur if you remove Waila or is it specific to that mod accessing the drone's data? Can you reproduce it using the latest version of OC (1.6.1.6)

**Comment by Dimtree** [comment] 2016-12-25 04:05
Removing WAILA/WAWLA from the client solves the issue. Possibly a duplicate of #2031?

I am unable to reproduce the crash with OC 1.6.1.6 (DW20 pack v1.2.1 beta). WAILA/WAWLA weren't updated, so either 1.6.1.6 fixed the problem or whatever other thing causing problems went away. Either way, Schrödinger's drone is no more.

**Comment by Vexatos** [comment] 2016-12-25 10:43
This looks very much like the same crash, indeed. However, it is different to the crash report from @henkaa, so I will leave this open for them to check whether the latest OpenComputers update fixes it for them.

**Comment by fnuecke** [comment] 2017-02-04 14:03
Probably same as  #2081.

**Closed as completed by fnuecke** 2017-02-04 14:03 UTC
