### ISSUE TITLE
[1.7.2] Bad Loot Disk Generation?

### ISSUE THREAD

**Issue by Techokami** [MightyPirates/OpenComputers#253] opened 2014-05-13 02:54 UTC
Now you guys know I rolled my own build with more loot disks, but this happens even with an unmodified copy.
Sometimes, a loot chest will generate a loot disk without any program data on it whatsoever. This is effectively a junk disk, as a computer will not read it. Bitrot, perhaps?

There should be a way to force initialize a floppy disk if this ever happens. Like, calling a function on the disk drive device itself. Or, double check loot disk generation code?

**Comment by fnuecke** [comment] 2014-05-13 11:16
Do the generated disks have labels? If so, is it always the same one?
Also maybe double-check your spelling, if the path in the loot file is incorrect that might be a cause.

**Comment by Techokami** [comment] 2014-05-13 17:19
The disks have no label. At first I assumed you had made blank floppies loot, but it doesn't seem to be the case.
I'll double check my loot list for typos.
EDIT: Just proofread loot.properties, no typos.

**Comment by fnuecke** [comment] 2014-05-15 10:59
Hmm, all right. I'll have a closer look soon-ish.

**Comment by fnuecke** [comment] 2014-05-21 11:32
So, it _seems_ as though there's a call-path that ignores the custom item generation, and directly accesses `WeightedRandomChestContent`'s base item, namely `ChestGenHooks.getOneItem`. That is, as far as I can tell, not used by Minecraft itself, though, so another Mod would have to cause that, which seems unlikely... even if that's the cause, I'm not sure what I'd want to do about that, because generating one 'generator' per item seems somewhat suboptimal: to my knowledge there is no way to set the actual probability for a generator to get called, just a 'weight'. Which is an Integer, of all things. And while there are such interestingly named fields as `theMinimumChanceToGenerateItem`, those are in fact the minimum and maximum stack sizes, not a real 'chance' in the probabilistic sense at all.

In 1.3 I'll probably just make the base item the OpenOS disk and call it a day. This may or may not lead to a disproportionate number of OS disks, but I don't really think it matters :P

**Comment by Techokami** [comment] 2014-05-21 12:29
Yeah, the problem stems from Dungeon Pack. Somehow, it generates pottery stamps from Modular Flower Pots just fine? Ask @jaquadro in #oc tonight when he's around for ideas.
But making OpenOS install disks the base is also a good idea!

Sent from my Windows Phone

**Comment by fnuecke** [comment] 2014-06-14 17:06
I think this should be fixed in the recent builds, but if you still encounter empty floppies please let me know!

**Closed as completed by fnuecke** 2014-06-14 17:06 UTC

**Comment by Techokami** [comment] 2014-06-14 17:17
Yes, the dungeon loot chests in Dungeon Pack now generate OpenOS install disks. Good of a solution as any.
