### ISSUE TITLE
[Suggestion] Video memory

### ISSUE THREAD

**Issue by LightningSh0ck** [MightyPirates/OpenComputers#2545] opened 2017-10-07 22:28 UTC
Gpus should have a memory that behaves somewhat like a "virtual" screen of their equivalent tier(no matter what monitor they are bound to, or if they are bound at all), not as a separate component, but they should be accesed via their own gpu's API and should have the following methods(added to the gpu API):

depth(): number -- Gets the maximum color depth supported by the GPU(ignores monitor)

memoryGetResolution(): number, number -- Gets the video memory resolution which is the same as the maximum resolution of the gpu and cannot be changed, you wouldn't have to.

memoryGet(x: number, y: number): string, number, number, number or nil, number or nil --same as get method but for memory instead of monitor

memorySet(x: number, y: number, value: string[, vertical:boolean]): boolean --same as set method but for memory instead of monitor

memoryCopy(x: number, y: number, width: number, height: number, tx: number, ty: number) --same as copy but for memory(both as source and destination)

save(x: number, y: number, width: number, height: number, tx: number, ty: number): boolean -- somewhat like copy where source is the monitor and destination is the memory. x and y are the monitor's source location, tx and ty are the destination in memory

load(x: number, y: number, width: number, height: number, tx: number, ty: number): boolean -- reverse of save method, source(x and y) is the memory and destination(tx and ty) is the monitor, or shall it go the other way(x and y monitor destination, tx and ty memory source)? I am not sure.

memoryFill(x: number, y: number, width: number, height: number, char: string): boolean -- same as fill method but for memory

gpu api for reference here: http://ocdoc.cil.li/component:gpu

Important note: thing like color pallette, foreground and background set/get methods also affect memory, those methods are shared. Also memory methods except load should consume less energy than their monitor counterparts.

So, you would ask why. Well, I think tables in Lua are quite messy, they occupy a lot of memory. So creating an imitation of this in Lua would consume a lot of space and resources(mostly from calling get method pixel by pixel). We could make sprites with this, like old gaming machines had and I think it would be a cool enhancement as windowed graphical interfaces are becoming popular in OC, and with this we could save invisible parts for the user when windows overlap. It should work as a static table implemented in Java and accessible by Lua, to save memory footprint on Minecraft servers. Sorry if I have a bad English.

**Comment by payonel** [comment] 2017-10-08 00:55
duplicate of #779 
not an exact duplicate, but this is an issue we have discussed and to some degree continue to discuss.
To be honest, there is a low chance this will be implemented, but we appreciate this idea

**Closed as completed by payonel** 2017-10-08 00:55 UTC
