### ISSUE TITLE
[1.10] No longer recognizes bundled cables from Project Red

### ISSUE THREAD

**Issue by mopsyd** [MightyPirates/OpenComputers#2290] opened 2017-02-26 19:30 UTC
Chickenbones recently updated project red to work for 1.10.2, and the redstone component no longer seems to recognize bundled cables. Colored wires and redstone wire still seem to work normally.

**Comment by brisingraerowing** [comment] 2017-02-26 23:51
Duplicate of #2259 

There is an open pull request for this: #2260

**Closed as completed** 2017-02-27 07:06 UTC
