### ISSUE TITLE
Robot sometimes disappears / gets into a bad state

### ISSUE THREAD

**Issue by jaquadro** [MightyPirates/OpenComputers#637] opened 2014-10-31 00:35 UTC
Preface: This bug is probably awful and I have little useful information to give.  Techokami will kill me if I don't report it, though.

I have a robot that I repeatedly run the dig command on to carve out chunks form Y=40 down.  On two occasions when I've come back to the area, the robot has been invisible.  Opis confirmed it was present where it should be (in front of the chest, since its work was done).  Triggering a block update would make the robot appear again.  It would be in a bad state though:

![robot](https://cloud.githubusercontent.com/assets/852988/4854617/8048cffe-6095-11e4-9215-68628594a993.png)

The robot appears off, all slots disabled, and its console is missing.  It does still have its tool inventory, which is a pick, chunk loader, and dig program.

Breaking and placing the robot again puts it back into a good state.  I suspect whatever the problem is, is limited to client side.

**Comment by Techokami** [comment] 2014-10-31 01:45
FYI this is from my private Minecraft server, and my OpenComputers builds are based on git repo snapshots from the master-1.7.10 branch on Saturday mornings, GMT-5, since that's when I update the mods on the server. Just to give you an idea about the age of the copy of OpenComputers in use here.

**Comment by fnuecke** [comment] 2014-10-31 16:06
Definitely sounds like a desync issue, yeah. Is there a chance the robot is currently moving while you get back to it? If so, mind placing a second one in that chunk that doesn't move, and when it happens again see if that one still appears correctly?

Oh, and what server is this, Forge? Cauldron? Version?

**Comment by Techokami** [comment] 2014-10-31 16:18
Forge 1232, iirc.

Sent from my Windows Phone

**Comment by jaquadro** [comment] 2014-10-31 17:48
It's unlikely the robot was moving when I came back.  IIRC the times I went back was well after when it should have completed its work.  One thing I should have done before resetting the robot is try logging out of the client, and see if that also corrects the problem.

**Comment by fnuecke** [comment] 2014-11-01 00:54
All right. Did you have a look if any warnings show up in the log around the time you go near the robot again? And yeah, seeing if re-logging fixes the issue would also be interesting to know.

**Comment by jpastuszek** [comment] 2014-11-02 22:39
I have "seen" this invisible robot problem once before. It was standing still (in os.sleep()) where it should have but it was not rendered at all. The hit box was displayed when I have hovered on it (if I remember correctly) and It was there. I am not sure if I destroyed and placed again but I got it working and this didn't happen any more.

**Comment by fnuecke** [comment] 2014-11-03 01:29
Odd, if this had happened after a move that could have been _somewhat_ plausible (since the movement is a tiny bit hacky to avoid having to re-create the full, complex robot TileEntity over and over again). But if this can happen for a robot that's just sitting there... I don't have any leads. Will need some digging.

**Comment by fnuecke** [comment] 2014-11-16 00:18
Just a quick update, I'm afraid I have not been able to reproduce this recently (I _think_ I've seen this happen a long, long time ago, but not recently), so no progress, yet.

If anyone has any more information on this, anything might help - for example
- Does this happen anywhere or only on chunk borders?
- Have you seen this happen if OC was the only mod loaded (if the answer is no it could be some incompatibility issue)?
- Has this happened to anyone while in single player?

Thanks, and sorry for the inconvenience.

**Comment by jpastuszek** [comment] 2014-11-16 19:29
This has happened to me recently as well when I have picked and placed the robot to work around input issue reported before.

Note the things in his slots!

![2014-11-13_21 19 23](https://cloud.githubusercontent.com/assets/20052/5062809/a941ad9e-6dc5-11e4-85bc-e8c6c47a4e8b.png)

Also see this:

![2014-11-13_21 19 35](https://cloud.githubusercontent.com/assets/20052/5062810/aa69fab4-6dc5-11e4-8d79-4f2c34b491ca.png)

The robot is holding it's own CPU!
When I picked it and placed again everything was back to normal. That is his components were not shown in the slots and they were empty as supposed to be and the display was there as well.

This is very rare to happen though. 
I hope this gives your some clues.
I was playing SMP on version 1.3.6 on the problematic chunks reported in another issue.

**Comment by fnuecke** [comment] 2014-11-18 09:39
Thanks, this may well be related to the robots apparently losing their state / desyncing.

I've added some checks to avoid calls to `getTileEntity` where, from my understanding, that _may_ trigger chunk loads - most notably in the packet handler, and seeing as this seems to happen primarily (only?) in server play, this may have been related (might have caused unexpected initialization order, stuff like that).

Anyone who experienced these issues, could you please give [the latest build](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/) (231 or newer) a try and see if things still go wrong occasionally? Thanks!

**Comment by jaquadro** [comment] 2014-11-18 14:48
Would that explanation make sense for a robot that carries its own chunk loader around?

I can do some more passive testing but @Techokami will need to turn the power requirement back off.

**Comment by fnuecke** [comment] 2014-11-18 15:30
It could, maybe even more so (since not even another player would have to be present on the server to cause a robot running around in an area (on the server) that's not loaded on some clients).

**Comment by Techokami** [comment] 2014-11-18 16:15
Or use a Creative Case to build a testing robot. (It'll be like a Tier 3 but ignore power requirements)
Talk to me on AIM tonight and we can discuss it.

Sent from my Windows Phone

**Comment by jpastuszek** [comment] 2014-11-18 18:11
I have tried version 232 and the good news is that I could access my robot (input) just after I have logged in to my server :) but the bad news is is that my server crashes if I don't log in to it for few seconds after it has started or I log in and then just after I log out (keeps going until I stay in):

https://gist.github.com/jpastuszek/48112e4325d8ab5c56eb

Looks like IC2 is failing on it's energy update. This only happens when I upgrade OC...
This does not happen when I run same world in single player mode (probably because it's life cycle is same as my session). If I open my world in single player (to trigger migrations?) and then save it and restore it on my server the crash is still there.

So I cannot test the scenario when I log out and back in to see if robot is accessible since the server will crash just after I log out.

**Comment by fnuecke** [comment] 2014-11-18 19:52
Hmm, strange that that wouldn't have happened before; nothing related to IC2 changed I don't think. I'll try to reproduce with that build, but 489 is a pretty old IC2 build, mind updating to see if it still happens with the newer builds?

**Comment by jpastuszek** [comment] 2014-11-19 11:05
Same problem after updating IC2 to 650:
https://gist.github.com/jpastuszek/a900dc7a802aa9781ac1

Looks like something to do with:
li.cil.oc.common.tileentity.Charger.onChunkUnload(Charger.scala:16) [Charger.class:?]

**Comment by fnuecke** [comment] 2014-11-19 11:12
Thanks for the log, actual error was in capacitor. Should be fixed in the next build!

**Comment by jpastuszek** [comment] 2014-11-19 11:14
Yes, looks like if I pick capacitor at -31,65,252 and I log out it does not crash. If I place it again boom!
Thank you!

**Closed as completed** 2014-11-25 19:51 UTC

**Comment by fnuecke** [comment] 2014-11-25 19:53
I've finally managed to track down the issue where robots would hold their CPU/RAM/etc in their hands, which was indeed the client getting into a bad state due to an unexpected packet order. The fix for this _probably_ also fixes other robot client state related issues, but I'm not absolutely sure about that. If, _in build 240 or later_, robots vanish as described in the first post of this issue, let me know and I'll re-open and re-investigate this.

**Comment by FeepingCreature** [comment] 2017-08-28 09:21
A robot vanished for me; when I tried to block update to make it reappear I could not open its inventory at all and its name kept rapidly cycling through robot names. Reconnecting fixed that issue, showing that the robot had run out of energy (this may or may not be related).
This is with OpenComputers 1.6.2.7 in FTB Beyond.

**Comment by xarses** [comment] 2017-08-28 17:24
@FeepingCreature due to the age of this issue, this is highly unlike to be the same issue. Please create a new issue and link to this one as its possibly related. Please include your MC, OC, and Forge versions in your issue. Also, Include any possible steps for reproducing the problem you ran into.

**Comment by FeepingCreature** [comment] 2017-08-28 19:38
If it's a different issue, and since there's no log errors, I'll file if I ever figure out how to reproduce it. Given that it took a week of play for this to happen the first time, that seems unlikely though.
