### ISSUE TITLE
Ability for players to Label Floppys.

### ISSUE THREAD

**Issue by Erumaaro** [MightyPirates/OpenComputers#1506] opened 2015-10-27 01:24 UTC
A GUI would be perfect for that, maybe requirering a pencil?
Would greatl'y simplify finding the correct Floppy...

**Comment by Voidi** [comment] 2015-10-27 01:39
Duplicate of https://github.com/MightyPirates/OpenComputers/issues/1340

**Closed as completed** 2015-10-27 02:01 UTC
