### ISSUE TITLE
Could not resolve all dependencies for configuration ':apiCompile'.

### ISSUE THREAD

**Issue by RobertCochran** [MightyPirates/OpenComputers#1613] opened 2016-01-14 15:00 UTC
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':apiCompile'.
> Could not resolve mrtjp:ProjectRed:1.7.10-4.6.2.82.
  Required by:
      li.cil.oc:OpenComputers:MC1.7.10-1.6.0-dev+11606c7
   > Could not GET 'https://libraries.minecraft.net/mrtjp/ProjectRed/1.7.10-4.6.2.82/ProjectRed-1.7.10-4.6.2.82.pom'. Received status code 403 from server: Forbidden
   > Could not GET 'http://coloredlightscore.us.to/maven/clc/mrtjp/ProjectRed/1.7.10-4.6.2.82/ProjectRed-1.7.10-4.6.2.82.pom'.
      > Connection to http://coloredlightscore.us.to refused
> Could not resolve coloredlightscore:ColoredLightsCore:1.3.7.35.
  Required by:
      li.cil.oc:OpenComputers:MC1.7.10-1.6.0-dev+11606c7
   > Could not GET 'https://libraries.minecraft.net/coloredlightscore/ColoredLightsCore/1.3.7.35/ColoredLightsCore-1.3.7.35.pom'. Received status code 403 from server: Forbidden
   > Could not GET 'http://coloredlightscore.us.to/maven/clc/coloredlightscore/ColoredLightsCore/1.3.7.35/ColoredLightsCore-1.3.7.35.pom'.
      > Connection to http://coloredlightscore.us.to refused

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 hrs 26 mins 17.438 secs
```

Maybe I've done something wrong, but at least two of those are 403s,
so that was definitely on purpose. Either way, can't build because gradle
_helpfully_ errors out instead of ignoring or even asking what I want to do.
I've had it bail out on that spot 3 different times about 1:10 in.

**Comment by Kubuxu** [comment] 2016-01-14 15:02
Duplicate of #1611 and check if #1612 resolves it.

**Comment by RobertCochran** [comment] 2016-01-14 23:16
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':apiCompile'.
> Could not resolve mrtjp:ProjectRed:1.7.10-4.6.2.82.
  Required by:
      li.cil.oc:OpenComputers:MC1.7.10-1.6.0-dev+734a808
   > Could not GET 'https://libraries.minecraft.net/mrtjp/ProjectRed/1.7.10-4.6.2.82/ProjectRed-1.7.10-4.6.2.82.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 42.398 secs
```

#1612 does not completely resolve it. It doesn't take an hour to decided to die,
so that's definitely a plus. But I'm still getting 403s for the libraries.minecraft.net
link. Does anyone know what happened to it?

**Comment by Techokami** [comment] 2016-01-15 00:21
I think Project:Red's Maven has died? I suggest poking them about it. (Someone already has on the Minecraft forums thread)

**Comment by fnuecke** [comment] 2016-01-15 20:41
Threw it up to my maven as a fallback, let me know if it still doesn't work.

**Closed as completed by fnuecke** 2016-01-15 20:41 UTC

**Comment by RobertCochran** [comment] 2016-01-15 23:06
Just completed a successful build, so we're good over here
