### ISSUE TITLE
[OC 1.6 Beta 3 for 1.9.4] Nanomachines Problems

### ISSUE THREAD

**Issue by Vixlia** [MightyPirates/OpenComputers#1885] opened 2016-06-15 04:39 UTC
Playing on a server running **Forge version 12.17.0.1941**-universal, and was testing nanomachines with a friend, only getting particle effects and occasionally magnetism. **We did not get any potion effects.** I have tested every individual input with getActiveEffects() and did not find anything in the output after 10 nanomachines' worth of different inputs (100 inputs total); unless magnetism was activated or a particle effect was visible, where it would output the correct label for the effect. MC 1.9.4 did change how potion and status effects worked on the player. Did the nanomachines change with this? I don't have a link to any documentation or references on the new status effects system.

Aside from the potion effects not being available, **attempting to use getName() will crash the user with the nanomachines in them** (not the one at the computer) and the computer sending the protocol will not receive the output.

**Comment by Vexatos** [comment] 2017-01-27 15:54
The crash has been fixed via https://github.com/MightyPirates/OpenComputers/commit/52a032ff63aea6ada292da1a47ec8caa958521f6 (see #2220).

**Comment by Vexatos** [comment] 2017-01-29 10:15
I found the cause of potion effects not being there: Their names changed in 1.9 so the potion whitelist in the config only contains potion effects with wrong names. Now there's two options: Either we change the config to use the new potion names or we change it to use their new unique identifiers (both would be strings, e.g. the current `potion.wither` has the name `effect.wither` and the identifier `wither` now. @fnuecke Which change would you prefer?

**Comment by fnuecke** [comment] 2017-01-29 10:24
UUID sounds like the more robust approach then, so let's go with that.

**Closed as completed** 2017-01-29 10:46 UTC
