### ISSUE TITLE
Crash When i use the monitors!!!

### ISSUE THREAD

**Issue by delete225** [MightyPirates/OpenComputers#25] opened 2013-12-24 21:33 UTC
When i put monitors i take crash :( ,
And in console i see this:
Client> #
Client> # A fatal error has been detected by the Java Runtime Environment:
Client> #
Client> #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x69836694, pid=5084, tid=788
Client> #
Client> # JRE version: Java(TM) SE Runtime Environment (7.0_45-b18) (build 1.7.0_45-b18)
Client> # Java VM: Java HotSpot(TM) Client VM (24.45-b08 mixed mode windows-x86 )
Client> # Problematic frame:
Client> # C  [atioglxx.dll+0x806694]
Client> #
Client> # Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
Client> #
Client> # An error report file with more information is saved as:
Client> # C:\Users\myra\AppData\Roaming.minecraft\hs_err_pid5084.log
Client> #
Client> # If you would like to submit a bug report, please visit:
Client> #   http://bugreport.sun.com/bugreport/crash.jsp
Client> # The crash happened outside the Java Virtual Machine in native code.
Client> # See problematic frame for where to report the bug.
Client> #
Client> AL lib: (EE) alc_cleanup: 1 device not closed
Game ended with bad state (exit code 1)
Ignoring visibility rule and showing launcher due to a game crash
Deleting C:\Users\myra\AppData\Roaming.minecraft\versions\1.6.4-Forge9.11.1.953\1.6.4-Forge9.11.1.953-natives-24591299565777
Couldn't delete C:\Users\myra\AppData\Roaming.minecraft\versions\1.6.4-Forge9.11.1.953\1.6.4-Forge9.11.1.953-natives-24591299565777 - scheduling for deletion upon exit

What i need to do ? I realy like this mod :)

**Comment by fnuecke** [comment] 2013-12-24 21:40
That it crashes in `atioglxx.dll` suggests it's your (real) graphics card driver messing up. Try updating it.

**Comment by delete225** [comment] 2013-12-25 13:05
It say to me its update to last version !!! ._. What i can do?

**Comment by fnuecke** [comment] 2013-12-25 14:58
Hmm, mind telling me what graphics card you have, exactly?

Edit: someone reported a crash [on the Minecraft bugtracker](https://mojang.atlassian.net/browse/MC-34056) that crashed at the exact same address in that DLL, which is _incredibly_ unlikely to be chance. That is marked as a duplicate for [this bug report](https://mojang.atlassian.net/browse/MC-31618) which mentions placing item frames / paintings in the world as a cause for crashes. Could you check if doing that also crashes the game for you?

**Comment by fnuecke** [comment] 2013-12-30 15:07
Marking this as a duplicate of #31 since that one has better logs.

**Closed as completed by fnuecke** 2013-12-30 15:07 UTC
