### ISSUE TITLE
There were errors running the class transformer

### ISSUE THREAD

**Issue by jurplel** [MightyPirates/OpenComputers#2062] opened 2016-09-18 21:38 UTC
[latest.log](http://hastebin.com/aserutulan.log)
OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar

**Comment by topher2010** [comment] 2016-09-25 19:02
I'm getting this error as well.  here is a dropbox link to my fml-latest log file.

https://www.dropbox.com/s/xm2485e2kc7m2zs/fml-client-latest.log?dl=0

**Comment by Alaberti** [comment] 2016-10-01 13:03
I think this issue has been address tons of times, try the dev builds here: http://ci.cil.li/job/OpenComputers-dev-MC1.10/ see https://github.com/MightyPirates/OpenComputers/issues/1998

**Comment by Vexatos** [comment] 2016-11-14 18:25
Duplicate of #1998.

**Closed as completed by Vexatos** 2016-11-14 18:25 UTC
