### ISSUE TITLE
Screen does not show anything

### ISSUE THREAD

**Issue by Roadrunner116** [MightyPirates/OpenComputers#2236] opened 2017-01-24 20:06 UTC
Hi,
I am playing the Direwolf20 1.10.2 Modpack in Version 1.3.2 with OC in 1.6.1.6.

The screens seem to render nothing. I tried every Tier.
The computer beeps and blinks as it is starting but the screen stays black.

Is this a known issue with a fix?

Cheers, Roadrunner116

**Comment by payonel** [comment] 2017-01-24 21:14
the case needs a GPU, and the screen needs to be in connection with the case (block-to-block contact or a cable)

If you cannot resolve the issue, please take a screenshot of your layout of screen and case, as well as a screenshot of the interior components of your case.

**Comment by xarses** [comment] 2017-01-24 21:53
What does it show when you open the screen gui vs the screen block with out the gui open?
Did you install an eeprom, a operating system, a graphics card, and keyboard and are they adjacent to the case, or connected by cable? What happens when you query the system with a debug card?

Given it's put together correctly, are there any messages in the client or server logs when you attempt to open the GUI.

If you spawn in the creative robot, can you see the output in its gui?

This has been seen before in some (older) video cards and performance mods, and removing the performance, or flipping off features tends to resolve this issue

**Comment by dbergey** [comment] 2017-01-26 20:54
I'm running OptiFine_1.10.2_HD_U_D4 and I see this issue. WIll try updating to OptiFine_1.10.2_HD_U_D6 to see if it persists. Any hints as to what features I should turn off?

**Comment by payonel** [comment] 2017-01-26 22:28
well try removing optifine first to confirm the problem goes away.

**Comment by dbergey** [comment] 2017-01-27 02:48
Reporting back that removing optifine does not fix it.

**Comment by xarses** [comment] 2017-01-27 18:33
- We still need to ensure that the computer was built correctly (screen shots in the case, and the connection between the case and monitor)  will be helpful here.
- Still need to know if the issue is with the GUI also, or just the text on the block
  - if the issue is present in the GUI, does the creative robot also have the issue?
  - if the issue is present in the GUI, but not on the creative robotwhat does a OC debug card, used on the case output
- Still need to know if there is relevant messages in the log file

**Comment by Vexatos** [comment] 2017-02-25 08:37
Does this still occur using OpenComputers 1.6.2?

**Comment by Roadrunner116** [comment] 2017-02-25 08:50
Sorry for not answering. I had no time to play since I opened this thread.  I did not change anything. The server got updated to pack version 1.5.1. I do not know right now which occurred version is used in this version of the modpack, but everything works fine

**Comment by Roadrunner116** [comment] 2017-02-25 08:51
Oc not occurred.  Sorry

**Comment by fnuecke** [comment] 2017-02-25 12:33
Was most likely fixed via 2751cec8c1526d489976627b4ffa0d6731616ee5.

**Closed as completed by fnuecke** 2017-02-25 12:33 UTC
