### ISSUE TITLE
OpenC HDD wiped [1.6.1.6]

### ISSUE THREAD

**Issue by Meri-Dax** [MightyPirates/OpenComputers#2221] opened 2017-01-12 20:01 UTC
Hello everyone, I'm currently playing on some multiplayer server with friends, with a custom feed the beast modpack, and I don't know where it comes from but sometimes all the data on my HDD gets wiped out, to the point I must reinstall the openOS

What could I provide to get what's not right ?

**Comment by xarses** [comment] 2017-01-13 17:24
Please see https://github.com/MightyPirates/OpenComputers/issues/2092.

We need the version(s) of at least MC and OC (1.6.1.6), if not the whole mod set. You should see if there is something in the server log about the disk, odds are if your a dupe of 2092 then, its not obvious.

As a fall-back, the UUID of the disk is presisted on the server's filesystem.

**Comment by payonel** [comment] 2017-01-17 20:05
duplicate of #2092

**Closed as completed by payonel** 2017-01-17 20:05 UTC
