### ISSUE TITLE
event error

### ISSUE THREAD

**Issue by Nex4rius** [MightyPirates/OpenComputers#2528] opened 2017-09-18 13:23 UTC
I'm getting this weird error in <a href="https://github.com/Nex4rius/Nex4rius-Programme/blob/Tank/Tank/server/tank/anzeige.lua">my program.</a> Am I doing something wrong or is this a problem in the event api?
<img src="https://oc.cil.li/uploads/monthly_2017_08/1.PNG.01daec78e5b11c65718509dcea571a3e.PNG" />

**Comment by payonel** [comment] 2017-09-18 14:58
you definitely may have found a bug.
can you please:
1. tell us what oc version you are running ("latest" is not descriptive)
2. explain the repro a) steps you take to hit this, b) how often this error occurs, c) does it repro after you reboot your oc computer?
3. please, if you can, reduce this to MINIMAL repro [far less code i need to run]

I would be very glad to fix this if you can improve this bug report. Thanks -payo

**Comment by Nex4rius** [comment] 2017-09-19 21:30
I have OpenComputers-MC1.7.10-1.6.2.12-universal
I tested it with OpenOS 1.6 and OpenOS 1.6.1 and it didn't happen.

But I used my <a href="https://github.com/Nex4rius/Nex4rius-Programme/blob/master/OpenOS-Updater/updater.lua">program</a> to update OpenOS directly from the github files to 1.6.8 and I got the error but strangly only in this <a href="https://github.com/Nex4rius/Nex4rius-Programme/blob/Tank/Tank/server/tank/anzeige.lua">program</a> and not in other programs that use the event api (probably something to do with event.timer() and event.cancel() which I don't use in other programs).
I've tried to pinpoint what line(s) exactly is causing this error in my code but so far without luck.

Reproduce:
run this "pastebin run -f icKy25PF" (on a fresh installation, with t3 gpu and t3 screen)
~~then run this "pastebin run -f cyF0yhXZ Tank"~~
wait ~2min

edit: I've shortend the code a bit (550 down to 186 lines) and the error still appears <a href="https://gist.github.com/Nex4rius/97ed82b76060c8251d8d0d3dd5b623bf#file-anzeige-lua">here</a>

**Comment by skyem123** [comment] 2017-09-20 15:42
I remember getting something similar to this error before... I can't recall exactly what I did to get my program working, but I do know that it was caused by timers.

I think it's because it doesn't like you cancelling timers that are already finished or cancelled? I am not too sure though, either way, the error message is not helpful and it stumped me for a while.

**Comment by payonel** [comment] 2017-09-20 16:25
This bug has my attention because the `handler` object should NEVER be nil. But If you can reduce the repro, I would appreciate it.

first of all, the first program changes the openos files. I'm not going to try to debug what that updater does, if it messes up any of the kernel files, and MOST importantly, expecting me to update openos to test your repro completely nullifies the meaning of what version you are on, and whether the bug has been fixed in later versions (assuming that updater even works corretly)

secondly, running the Tank program has two issues
1. you didn't tell me whether to select server or client. nor did you mention if I needed both
2. you didn't mention that I needed a modem device, and it appears that i do? ... 

I am very invested in fixing this bug - and I appreciate the time you've already put into working with this bug. But honestly, this repro is more of a "debug my program" and less of a "bug" report.

**Comment by payonel** [comment] 2017-09-20 16:34
a minimal repro won't require me to press enter to a prompt, pick a name for a "Client", choose between server and client, none of that

**Comment by payonel** [comment] 2017-09-20 16:52
I ran as Client for about 30 minutes. no crash [testing on latest openos from http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/ ]

**Comment by payonel** [comment] 2017-09-20 17:10
If I run  your program and choose "Server", it reboots and changes the resolution and tells me to wait.
After some time (maybe two minutes like you said) it reverts to a command prompt `home #`. But the resolution is only 1 line high, so who knows if an error message printed. Oh, and while I'm typing this I see my test machine with your script just rebooted...

Everything is wrong with this as a repro
1. simplify the program
2. remove all code unrelated to your program and keep only what is needed for the bug
3. don't make it hard for me to see the error
4. don't make me choose ANY options unless it is crucial for the repro
5. don't make me add any hardward (e.g. modem) unless it is _necessary_ for a repro

**Comment by Nex4rius** [comment] 2017-09-20 17:25
Sorry about that.

I've reduced the code now and the error still appears.
Copy <a href="https://gist.github.com/Nex4rius/97ed82b76060c8251d8d0d3dd5b623bf#file-this-has-the-error-lua">this</a> and run it and after 1min the error occurs.

**Comment by payonel** [comment] 2017-09-20 18:12
it repros very nicely with this. thank you @Nex4rius

**Closed as completed** 2017-09-21 11:49 UTC
