### ISSUE TITLE
[Suggestion] Chunk loader for computer.

### ISSUE THREAD

**Issue by S0ZDATEL** [MightyPirates/OpenComputers#2564] opened 2017-10-21 10:22 UTC
In the mod is a chunk loader for robots and drones, but not for computers or servers. It can be made in the form of a card or block.

**Comment by skyem123** [comment] 2017-10-21 14:33
Well, not sure how it should be done to be consistent, but it sounds like a good idea.

**Comment by ben-mkiv** [comment] 2017-10-21 16:36
it could be just allowed in a adapter?!

**Comment by Fingercomp** [comment] 2017-10-21 21:41
Maybe simply allowing to assemble a microcontroller with the chunkloader upgrade is enough. It's even already written in [the manual](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/doc/en_US/item/chunkloaderUpgrade.md), though the upgrade seems to be blacklisted in the code.

Also, this is a duplicate of #2499.

**Comment by payonel** [comment] 2017-10-24 09:27
allowed upgrade in uC might be the right solution, but we'll track in the other issue

**Closed as completed by payonel** 2017-10-24 09:27 UTC
