### ISSUE TITLE
client crash on a manual page

### ISSUE THREAD

**Issue by NoX-programer** [MightyPirates/OpenComputers#1305] opened 2015-07-17 07:33 UTC
To reprocuce: take
appliedenergistics2-rv2-stable-10.jar
ExtraCells-1.7.10-2.2.73b129.jar
OpenComputers-MC1.7.10-1.5.14.30-universal.jar
then open NEI, find ME Upgrade (any tier), hit U, open manual, try to scroll down (at 1st tab of it). Getting this:
Description: Rendering screen

java.lang.ArithmeticException: / by zero
    at li.cil.oc.client.gui.Manual.func_73863_a(Manual.scala:154)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by makkarpov** [comment] 2015-07-17 07:38
Duplicate of #1295

**Comment by NoX-programer** [comment] 2015-07-17 07:42
Oops, sorry.

**Closed as completed** 2015-07-17 07:54 UTC
