### ISSUE TITLE
Feature: Screenlock & Screenunlock type of feature.

### ISSUE THREAD

**Issue by tbbw** [MightyPirates/OpenComputers#657] opened 2014-11-06 18:48 UTC
Hello iwe been playing around with OC a while now and enjoy it alot :)
But i noticed the rendering of the screens ( big Tier3 screens ) are kinda sluggish when your updating alot to it (on default settings).

But i have somewhat of a solution in mind.
How about been able to lock/unlock the screen as in:
I lock it... do all my interactions ( writing text and such at same speed ) and then unlock the screen and all my changes gets changed in one go even doh it took the same ammount of power and time... just would look alot better on the client side and i guess it might save some bandwith (?) too instead of a deja-vu of my 2400baud modem :P

Well just wanted to get it out there and get u guys thinking about it :)

**Comment by LordFokas** [comment] 2014-11-06 19:22
I can think of more than a couple ways that can go wrong on multiplayer, but I'm always up for optimization. I'm pretty sure OC already does that kind of optimization in quite a few places...

I'm also sure the community (especially those people who know OC to its guts) will come up with ways to make that work. If that gets approved, that is.

**Comment by fnuecke** [comment] 2014-11-06 23:07
Duplicate of #457. I think. At least very related; feel invited to share your thoughts on what's been discussed in there, too!

**Closed as completed by fnuecke** 2014-11-06 23:07 UTC

**Comment by tbbw** [comment] 2014-11-07 02:53
I dont see why double buffering would be the same as locking the screen building up a queue of copy, fill, set, setBackground and setForeground commands and then unlocking it so these commands goes in one go.
It's not two screen buffers i'm refering to... besides the user does not realy gain access to the gpu's or the monitors current screen buffer in that way as it is currently anyway.
Not sure if i'm not getting the point out correctly... think of it as a "sleep" statement for the monitor while the gpu is doing it's thing and the monitor catches up afterwards once unlocked.

Edit: I guess ther are diffrent ways to shave the same camel but a few posts in on #457 i can see you guys are already discussing why duble buffering and resending the whole screen to all the clients would be a bad idea so it's true this is kinda related but very diffrent from double buffering.

**Comment by fnuecke** [comment] 2014-11-07 11:51
Well, the technicalities of the implementation are a bit different, but the desired result is exactly the same, no? I.e. performing multiple operations in advance, then flushing them to the visible screen in one go.

The one _noticeable_ difference I can see is that when queuing the changes before applying them means `get` behaves differently from the double buffering approach (as in here it'd return the same thing until flushing, when using the double buffering approach you could immediately tell changes even if the buffers have not yet been swapped).

I think it's an interesting alternative approach, but if something like this makes it in, I prefer the double-buffer approach, since it's closer to what I'm used to from "real life" graphics coding.
