### ISSUE TITLE
Crash on screen click

### ISSUE THREAD

**Issue by WazWaz** [MightyPirates/OpenComputers#909] opened 2015-02-12 07:32 UTC
This happened repeatably while I was trying to get power to my computer system from RotaryCraft, but stopped showing up once everything was in place. I have the full report if useful and can probably reproduce it by disassembling stuff.

```
java.lang.NoSuchMethodError: li.cil.oc.api.component.TextBuffer.mouseDown(DDILnet/minecraft/entity/player/EntityPlayer;)V
    at li.cil.oc.common.tileentity.Screen.click(Screen.scala:156)
    at li.cil.oc.common.block.Screen.rightClick(Screen.scala:349)
    at li.cil.oc.common.block.Screen.onBlockActivated(Screen.scala:332)
    at li.cil.oc.common.block.SimpleBlock.func_149727_a(SimpleBlock.scala:259)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1436)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1942)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
```

**Comment by WazWaz** [comment] 2015-02-12 07:59
I'm pretty sure it's happening when using a screen with no keyboard attached.

**Comment by fnuecke** [comment] 2015-02-12 19:30
Duplicate of #852.

**Closed as completed by fnuecke** 2015-02-12 19:30 UTC
