### ISSUE TITLE
There were errors running the class transformer

### ISSUE THREAD

**Issue by MariuszPL55** [MightyPirates/OpenComputers#2093] opened 2016-10-12 19:42 UTC
I know the title is repeated multiple time, but I attach the log - hope this will be fix. I'm using OpenComputers with Industrial Craft for MC 1.10.2
[latest.log](https://github.com/MightyPirates/OpenComputers/files/525489/latest.txt)

**Comment by gamax92** [comment] 2016-10-13 17:15
Like the chat message says we still need `fml-server-latest.log` (or `fml-client-latest.log` if this is singleplayer)

**Comment by MariuszPL55** [comment] 2016-10-13 22:09
I don't have such a file. Maybe you mean fml-client-latest.log?

[fml-client-latest.txt](https://github.com/MightyPirates/OpenComputers/files/528308/fml-client-latest.txt)

**Comment by gamax92** [comment] 2016-10-14 06:26
```
[21:33:15] [Client thread/WARN] [OpenComputers/]: Failed patching btb.renderLeash, method not found.
```

Seems to be just this common issue, a thing to note about class transformer 'errors' is that they're actually rather harmless and OC will completely function normally despite the issue.

**Comment by PapyRedstone** [comment] 2016-10-17 11:59
personally i can run oc alone with tis error but when i put other mods with it i can't use oc

**Comment by Vexatos** [comment] 2016-11-14 18:35
Duplicate of #1998.

**Closed as completed by Vexatos** 2016-11-14 18:35 UTC
