### ISSUE TITLE
Nanomachines getName() causes crash

### ISSUE THREAD

**Issue by TheTokenMaster** [MightyPirates/OpenComputers#2244] opened 2017-01-27 16:04 UTC
Using "OpenComputers-MC1.10.2-1.6.1.6" and only OpenComputers, no other mods.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.10.2-1.6.1.6.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 27/01/17 16:00
Description: Ticking player

java.lang.IllegalArgumentException: unsupported data type
	at li.cil.oc.server.network.Network$Packet$$anonfun$16$$anonfun$apply$11.apply(Network.scala:705)
	at li.cil.oc.server.network.Network$Packet$$anonfun$16$$anonfun$apply$11.apply(Network.scala:694)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:186)
	at li.cil.oc.server.network.Network$Packet$$anonfun$16.apply(Network.scala:694)
	at li.cil.oc.server.network.Network$Packet$$anonfun$16.apply(Network.scala:690)
	at scala.Option.fold(Option.scala:157)
	at li.cil.oc.server.network.Network$Packet.<init>(Network.scala:690)
	at li.cil.oc.server.network.Network$.newPacket(Network.scala:546)
	at li.cil.oc.server.network.Network$.newPacket(Network.scala:431)
	at li.cil.oc.api.Network.newPacket(Network.java:226)
	at li.cil.oc.common.nanomachines.ControllerImpl$$anonfun$respond$1.apply$mcV$sp(ControllerImpl.scala:157)
	at li.cil.oc.common.nanomachines.ControllerImpl$$anonfun$update$1.apply(ControllerImpl.scala:238)
	at li.cil.oc.common.nanomachines.ControllerImpl$$anonfun$update$1.apply(ControllerImpl.scala:238)
	at scala.Option.foreach(Option.scala:245)
	at li.cil.oc.common.nanomachines.ControllerImpl.update(ControllerImpl.scala:238)
	at li.cil.oc.common.event.NanomachinesHandler$Common$.onLivingUpdate(NanomachinesHandler.scala:92)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_Common$_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:492)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1931)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at li.cil.oc.server.network.Network$Packet$$anonfun$16$$anonfun$apply$11.apply(Network.scala:705)
	at li.cil.oc.server.network.Network$Packet$$anonfun$16$$anonfun$apply$11.apply(Network.scala:694)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:186)
	at li.cil.oc.server.network.Network$Packet$$anonfun$16.apply(Network.scala:694)
	at li.cil.oc.server.network.Network$Packet$$anonfun$16.apply(Network.scala:690)
	at scala.Option.fold(Option.scala:157)
	at li.cil.oc.server.network.Network$Packet.<init>(Network.scala:690)
	at li.cil.oc.server.network.Network$.newPacket(Network.scala:546)
	at li.cil.oc.server.network.Network$.newPacket(Network.scala:431)
	at li.cil.oc.api.Network.newPacket(Network.java:226)
	at li.cil.oc.common.nanomachines.ControllerImpl$$anonfun$respond$1.apply$mcV$sp(ControllerImpl.scala:157)
	at li.cil.oc.common.nanomachines.ControllerImpl$$anonfun$update$1.apply(ControllerImpl.scala:238)
	at li.cil.oc.common.nanomachines.ControllerImpl$$anonfun$update$1.apply(ControllerImpl.scala:238)
	at scala.Option.foreach(Option.scala:245)
	at li.cil.oc.common.nanomachines.ControllerImpl.update(ControllerImpl.scala:238)
	at li.cil.oc.common.event.NanomachinesHandler$Common$.onLivingUpdate(NanomachinesHandler.scala:92)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_Common$_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:492)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1931)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 1776
	Entity Name: Dav3TheR4ve
	Entity's Exact location: 37.64, 80.00, 209.85
	Entity's Block location: World: (37,80,209), Chunk: (at 5,5,1 in 2,13; contains blocks 32,0,208 to 47,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@1325d02c
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 677419808 bytes (646 MB) / 1040142336 bytes (991 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.2.2124 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2124.jar) 
	UCHIJAAAA	Forge{12.18.2.2124} [Minecraft Forge] (forge-1.10.2-12.18.2.2124.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.1.6} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	OpenComputers{1.6.1.6} [OpenComputers] (OpenComputers-MC1.10.2-1.6.1.6.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.10.2-1.6.1.6.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Dav3TheR4ve'/1776, l='New World', x=37.64, y=80.00, z=209.85]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Vexatos** [comment] 2017-01-27 16:16
Duplicate of #2242 and #2220. I has already been fixed.

**Closed as completed by Vexatos** 2017-01-27 16:16 UTC
