### ISSUE TITLE
[1.10.2] World unload crash

### ISSUE THREAD

**Issue by thiakil** [MightyPirates/OpenComputers#2068] opened 2016-09-24 05:50 UTC
`[13:19:34] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.world.WorldEvent$Unload@4ac2bd08:
java.lang.NoClassDefFoundError: li/cil/oc/common/EventHandler$$anonfun$onWorldUnload$1
    at li.cil.oc.common.EventHandler$.onWorldUnload(EventHandler.scala:409) ~[EventHandler$.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_482_EventHandler$_onWorldUnload_Unload.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) [EventBus.class:?]
    at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:399) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.ClassNotFoundException: li.cil.oc.common.EventHandler$$anonfun$onWorldUnload$1
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_102]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_102]
    ... 7 more
Caused by: java.lang.NullPointerException`

full log: [fml-server-1.txt](https://github.com/MightyPirates/OpenComputers/files/490987/fml-server-1.txt)

OC version: 51085de (compiled by me to get the drone placement fix, no modifications)
Forge: 12.18.1.2084

This seems to have caused some world corruption, as it caused errors in ExtraUtils2 on subsequent server startup

**Comment by fnuecke** [comment] 2017-02-04 12:48
Looks like some mod's class transformer threw an NPE, impossible to tell which one though. Unless this happens with OC only, I'll close this. If you *can* reproduce it with OC only, please reopen it.

**Closed as completed by fnuecke** 2017-02-04 12:48 UTC
