### ISSUE TITLE
"init" event not caught by /boot/94_shell.lua

### ISSUE THREAD

**Issue by Sukasa** [MightyPirates/OpenComputers#2264] opened 2017-02-05 23:54 UTC
Using /oc_spawnComputer to spawn in a computer, I installed openOS and then removed the install disk and rebooted.

I then typed 'hostname test', and then 'reboot'.  After rebooting, the hostname does not show up as part of the shell prompt.

Entering the lua interpreter and running "event.push('init')" and closing the Lua interpreter resulted in the hostname showing up as part of the shell prompt.  It seems that the "init" event is either being fired before 94_shell.lua can execute, or is not firing at all.

**Comment by payonel** [comment] 2017-02-06 00:33
I believe all boot scripts (everything under /boot) are run before init is pushed. I'll review this workflow and fix later.

**Comment by payonel** [comment] 2017-05-15 00:43
Ok, there is not a bug with the signaling system here, the issue is that the user profile runs after the init signal, and the user profile changes PS1 and ignores /etc/hostname

**Comment by payonel** [comment] 2017-05-15 06:57
closed by https://github.com/MightyPirates/OpenComputers/commit/8f9eabc84e8dbdeb98c8ee2e7af85f00add91677

**Closed as completed by payonel** 2017-05-15 06:57 UTC
