### ISSUE TITLE
Robot's wifi card stops working after server restart

### ISSUE THREAD

**Issue by Belgabor** [MightyPirates/OpenComputers#1224] opened 2015-06-16 17:08 UTC
Version: 1.7.10-1.5.12.26

I have a robot that uses event.pull to react to wifi messages. Whenever the (minecraft) server gets restarted, the robot's wifi is dead. Restarting the robot doesn't help, I have to break and replace it to get it to work again.

**Comment by fnuecke** [comment] 2015-06-16 19:09
Does this also happen in single player? If you have the wifi card in a card container so you can remove and re-insert it, does that fix it?

**Comment by fnuecke** [comment] 2015-06-16 20:10
I'm afraid I cannot reproduce this. Can you give me a more in-depth description and a minimalistic reproduction case (i.e. new world, then place what where, open what ports, send what messages when etc).

**Comment by Belgabor** [comment] 2015-06-16 20:28
Going to try to get you more info. So far I can tell it doesn't seem to happen in SSP with Creatix.
I'll replace the robot on the server with one that has a card container and check what happens.

The program running on the robot is here:
https://github.com/Belgabor/OpenComputers/blob/master/teleport_robot.lua

**Comment by Belgabor** [comment] 2015-06-16 21:52
Reinserting the wifi card in a card container does the trick as well.

**Comment by fnuecke** [comment] 2015-06-20 15:41
Tested on a server and still can't reproduce this.

Could you set up two computers/Creatices with wireless cards and send me a _minimalist_ script to run on the sending one and one for the receiving one with which you can reproduce the issue?

For reference, what I did for testing: on the first one (receiver), I ran `component.modem.open(1)` from the interpreter, then run `dmesg`, on the other (sender) I just ran `component.modem.broadcast(1, "test")` once before and once after the server restart. Both messages showed up on the receiver.

**Comment by Belgabor** [comment] 2015-06-22 00:18
I can trigger the bug with your example. Thing is, computer and robot need to be some distance apart. When I had them right next to each other it worked fine. As soon as I put the robot one level below the computer (distance 12-13 according to the wireless message), the bug happened. When I had them close (and it didn't happen), distance read 0.

**Comment by fnuecke** [comment] 2015-08-28 16:49
Still can't reproduce this, and that it'd be position dependent makes it even weirded; sounds more like you might be having bad luck with the obstacle sampling so that sometimes messages come through, sometimes they don't (which is normal and intended). If you can provide me savegame where this happen I can have another look at it, otherwise I'll be closing this under the assumption that it's that.

**Comment by fnuecke** [comment] 2015-11-15 21:15
Still haven't seen this, and there have been no other reports. If you still can reproduce the issue, let me know and send me a world file as mentioned.

**Closed as completed by fnuecke** 2015-11-15 21:15 UTC

**Comment by Belgabor** [comment] 2015-11-15 23:04
The server's been down for a while so I can't check any more. If it occurs again, I'll reopen.
