### ISSUE TITLE
Robot complete failure - "name cycler"

### ISSUE THREAD

**Issue by MaHuJa** [MightyPirates/OpenComputers#899] opened 2015-02-08 13:01 UTC
https://www.dropbox.com/s/7mxwasrwbe6rs0b/fml-client-namecycler.txt?dl=0
OpenComputers-MC1.7.10-1.4.8.33-universal.jar - but I've seen this error before.

[11:18:22] [Client thread/ERROR] [FML/]: A TileEntity oc:robot(li.cil.oc.common.tileentity.RobotProxy) has thrown an exception during loading, its state cannot be restored. Report this to the mod author

Pair of robots, T1, minimal memory, graphics/screen/keyboard, disk drive (boots off of floppy), inventory module. They perform the exact same task, in a nutshell
1) place block from inventory (searching through if necessary)
2) rotate right
3) sleep  -- failure happens around here
4) rotate right
5) select(16) if compare then swing
6) goto 1

Occasionally they are OOM before they're even booted, but it usually loads and starts working. At which point it will keep working. (No new memory is allocated on my end.) Until this problem occurs.

Both of them fail at around the same time. I'm not entirely sure where the above log fits into things chronologically, but I'm assuming it's related. I had to dig into a couple logs old (client-3) to find that. The others appear to have no noteworthy OC messages.

When the bug occurs, I have the following visible effects:
a) They lose their pickaxe/axe respectively.
b) Their names start cycling through various robot names, switching apparently once per tick (hence "name cycler")
c) The interface is inaccessible.

Upon reloading the game and world, they're replaced by robots as if you threw a t1 case into an assembler and pressed built without any components.

**Comment by fnuecke** [comment] 2015-02-09 12:15
To quote the full trace

```
java.lang.NullPointerException
    at li.cil.oc.common.tileentity.traits.Computer$class.readFromNBT(Computer.scala:152) ~[Computer$class.class:?]
    at li.cil.oc.common.tileentity.RobotProxy.func_145839_a(RobotProxy.scala:129) ~[RobotProxy.class:?]
    at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:116) [aor.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:496) [aqk.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) [ChunkIOProvider.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
    at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
    at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
    at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
    at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
    at net.minecraft.world.World.func_147437_c(World.java:365) [ahb.class:?]
    at vazkii.botania.client.fx.FXSparkle.pushOutOfBlocks(FXSparkle.java:174) [FXSparkle.class:?]
    at vazkii.botania.client.fx.FXSparkle.func_70071_h_(FXSparkle.java:141) [FXSparkle.class:?]
    at net.minecraft.client.particle.EffectRenderer.func_78868_a(EffectRenderer.java:77) [bkn.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2043) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_45]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
```

This looks like Botania somehow causes a tile entity's `readFromNBT` method to be called on the client side. This should never happen. Ever. But I guess I can throw a check in there to make sure it's ignored on the client side... wouldn't be surprised if this caused issues with other mods, too, though.

Also, could you please try reproducing this in a new world? The other exception is thrown in the code responsible for converting blocks of an old format to the current format. Thanks.

**Comment by fnuecke** [comment] 2015-02-09 12:41
Please give the latest builds a try (1.4.9 or 1.5.0-dev), see if the side-check helps.

**Comment by MaHuJa** [comment] 2015-02-10 12:00
Maybe it should be brought to @Vazkii 's attention then...

It's been closer to two months since the first time it happened, and this was probably the third time. That is just how intermittent this issue is and therefore I do not believe I can confirm a fix. For now I'm keeping the robots off of the 3x3 area I presume is affected by this.

The setup was a pure daisy - flower that turns surrounding stone and wood into the special type used for crafting - with a pair of those robots next to it, placing the stone/wood in the corners of the 3x3.
It always happens to both of them at the same time. 

Given the cleanness of my other logfiles wrt OC errors, I'm thinking the other exception is related to this one somehow. For example, the spurious call corrupting its data to the point where it thinks it is an older version needing to be upgraded.

It also isn't obvious where I'd get 1.4.9 from.

**Comment by fnuecke** [comment] 2015-02-10 12:11
Maybe. And if it's only so I'm told other mods call readFromNBT client-side, too :P

Either way, 1.4.9 is now officially released, see releases / Curse (once approved). For future reference, you can also get the builds on my Jenkins at http://ci.cil.li/

I'm closing this for now, because I also suspect the two to be related. If this happens again, please reopen / let me know and I'll reopen this.

**Closed as completed by fnuecke** 2015-02-10 12:11 UTC

**Comment by Vazkii** [comment] 2015-02-10 14:27
The line in question is this one, I can't see how that would call readFromNBT.
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/client/fx/FXSparkle.java#L174

**Comment by fnuecke** [comment] 2015-02-10 19:02
Hmm. Digging into the trace it looks like the particle effect has a reference to a server world somehow - or at least a client world that has a server's chunk provider (hence triggering a chunk load when looking up the block info [b/c getBlock triggers chunk loads], which AFAIK doesn't happen on the client).

One theory would be that the particles are created using a server world (i.e. from the server thread). This seems possible _in singleplayer mode_ since it looks like it'd then [use the client proxy](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/client/core/proxy/ClientProxy.java#L301) - maybe a `if (!world.isRemote) return;` for sanity wouldn't hurt?

The other theory would be that something messes with the client world, but that seems less likely, I'd expect that to mess up way more things way worse.
