### ISSUE TITLE
Could not read data(1.7.10)

### ISSUE THREAD

**Issue by SpicyForthProgrammer** [MightyPirates/OpenComputers#2176] opened 2016-12-10 21:06 UTC
I was just messing around with the cc emulator when all the sudden this issue popped up and froze my world:

```
[B#347]  [15:37:08] [Server thread/ERROR] [OpenComputers]: Unexpected error loading a state of computer at (477.5, 4.5, -1039.5). State: Paused. Unless you're upgrading/downgrading across a major version, please report this! Thank you.
[B#347]  java.lang.Exception: li.cil.repack.com.naef.jnlua.LuaRuntimeException: could not read data
[B#347]  	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.load(NativeLuaArchitecture.scala:351) ~[NativeLuaArchitecture.class:?]
[B#347]  	at li.cil.oc.server.machine.Machine.liftedTree1$1(Machine.scala:721) [Machine.class:?]
[B#347]  	at li.cil.oc.server.machine.Machine.load(Machine.scala:720) [Machine.class:?]
[B#347]  	at li.cil.oc.server.component.Server.load(Server.scala:78) [Server.class:?]
[B#347]  	at li.cil.oc.common.inventory.ItemStackInventory$class.reinitialize(ItemStackInventory.scala:27) [ItemStackInventory$class.class:?]
[B#347]  	at li.cil.oc.server.component.Server.reinitialize(Server.scala:37) [Server.class:?]
[B#347]  	at li.cil.oc.common.inventory.ItemStackInventory$class.$init$(ItemStackInventory.scala:16) [ItemStackInventory$class.class:?]
[B#347]  	at li.cil.oc.server.component.Server.<init>(Server.scala:37) [Server.class:?]
[B#347]  	at li.cil.oc.integration.opencomputers.DriverServer$.createEnvironment(DriverServer.scala:22) [DriverServer$.class:?]
[B#347]  	at li.cil.oc.common.inventory.ComponentInventory$$anonfun$onItemAdded$1.apply(ComponentInventory.scala:118) [ComponentInventory$$anonfun$onItemAdded$1.class:?]
[B#347]  	at li.cil.oc.common.inventory.ComponentInventory$$anonfun$onItemAdded$1.apply(ComponentInventory.scala:117) [ComponentInventory$$anonfun$onItemAdded$1.class:?]
[B#347]  	at scala.Option.foreach(Option.scala:245) [scala-library-2.11.1.jar:?]
[B#347]  	at li.cil.oc.common.inventory.ComponentInventory$class.onItemAdded(ComponentInventory.scala:117) [ComponentInventory$class.class:?]
[B#347]  	at li.cil.oc.common.tileentity.Rack.li$cil$oc$common$tileentity$traits$ComponentInventory$$super$onItemAdded(Rack.scala:40) [Rack.class:?]
[B#347]  	at li.cil.oc.common.tileentity.traits.ComponentInventory$class.onItemAdded(ComponentInventory.scala:78) [ComponentInventory$class.class:?]
[B#347]  	at li.cil.oc.common.tileentity.Rack.onItemAdded(Rack.scala:361) [Rack.class:?]
[B#347]  	at li.cil.oc.common.inventory.Inventory$class.setInventorySlotContents(Inventory.scala:42) [Inventory$class.class:?]
[B#347]  	at li.cil.oc.common.tileentity.Rack.func_70299_a(Rack.scala:40) [Rack.class:?]
[B#347]  	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77) [aay.class:?]
[B#347]  	at li.cil.oc.common.container.StaticComponentSlot.li$cil$oc$common$container$ComponentSlot$$super$putStack(StaticComponentSlot.scala:8) [StaticComponentSlot.class:?]
[B#347]  	at li.cil.oc.common.container.ComponentSlot$class.putStack(ComponentSlot.scala:40) [ComponentSlot$class.class:?]
[B#347]  	at li.cil.oc.common.container.StaticComponentSlot.func_75215_d(StaticComponentSlot.scala:8) [StaticComponentSlot.class:?]
[B#347]  	at li.cil.oc.common.container.Player$$anonfun$tryTransferStackInSlot$4.apply$mcVI$sp(Player.scala:88) [Player$$anonfun$tryTransferStackInSlot$4.class:?]
[B#347]  	at li.cil.oc.common.container.Player$$anonfun$tryTransferStackInSlot$4.apply(Player.scala:83) [Player$$anonfun$tryTransferStackInSlot$4.class:?]
[B#347]  	at li.cil.oc.common.container.Player$$anonfun$tryTransferStackInSlot$4.apply(Player.scala:83) [Player$$anonfun$tryTransferStackInSlot$4.class:?]
[B#347]  	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778) [scala-library-2.11.1.jar:?]
[B#347]  	at scala.collection.immutable.Range.foreach(Range.scala:160) [scala-library-2.11.1.jar:?]
[B#347]  	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777) [scala-library-2.11.1.jar:?]
[B#347]  	at li.cil.oc.common.container.Player.tryTransferStackInSlot(Player.scala:83) [Player.class:?]
[B#347]  	at li.cil.oc.common.container.Player.func_82846_b(Player.scala:48) [Player.class:?]
[B#347]  	at net.minecraft.inventory.Container.func_75144_a(SourceFile:193) [zs.class:?]
[B#347]  	at li.cil.oc.common.container.Player.func_75144_a(Player.scala:35) [Player.class:?]
[B#347]  	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:883) [nh.class:?]
[B#347]  	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) [ix.class:?]
[B#347]  	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) [ix.class:?]
[B#347]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[B#347]  	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
[B#347]  	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
[B#347]  	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
[B#347]  	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
[B#347]  	at fastcraft.at.a(F:978) [fastcraft-1.23.jar:?]
[B#347]  	at fastcraft.H.aq(F:36) [fastcraft-1.23.jar:?]
[B#347]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
[B#347]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[B#347]  Caused by: li.cil.repack.com.naef.jnlua.LuaRuntimeException: could not read data
[B#347]  	at li.cil.repack.com.naef.jnlua.LuaState.lua_pcall(Native Method) ~[LuaState.class:?]
[B#347]  	at li.cil.repack.com.naef.jnlua.LuaState.call(LuaState.java:677) ~[LuaState.class:?]
[B#347]  	at li.cil.oc.server.machine.luac.PersistenceAPI.unpersist(PersistenceAPI.scala:164) ~[PersistenceAPI.class:?]
[B#347]  	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.load(NativeLuaArchitecture.scala:363) ~[NativeLuaArchitecture.class:?]
[B#347]  	... 43 more
[B#347]  [15:37:08] [Server thread/ERROR] [OpenComputers]: Unexpected error loading a state of computer at (477.5, 4.5, -1039.5). State: Paused. Unless you're upgrading/downgrading across a major version, please report this! Thank you.
[B#347]  java.lang.Exception: li.cil.repack.com.naef.jnlua.LuaRuntimeException: could not read data
[B#347]  	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.load(NativeLuaArchitecture.scala:351) ~[NativeLuaArchitecture.class:?]
[B#347]  	at li.cil.oc.server.machine.Machine.liftedTree1$1(Machine.scala:721) [Machine.class:?]
[B#347]  	at li.cil.oc.server.machine.Machine.load(Machine.scala:720) [Machine.class:?]
[B#347]  	at li.cil.oc.server.component.Server.load(Server.scala:78) [Server.class:?]
[B#347]  	at li.cil.oc.common.inventory.ComponentInventory$$anonfun$onItemAdded$1.liftedTree2$1(ComponentInventory.scala:123) [ComponentInventory$$anonfun$onItemAdded$1.class:?]
[B#347]  	at li.cil.oc.common.inventory.ComponentInventory$$anonfun$onItemAdded$1.apply(ComponentInventory.scala:122) [ComponentInventory$$anonfun$onItemAdded$1.class:?]
[B#347]  	at li.cil.oc.common.inventory.ComponentInventory$$anonfun$onItemAdded$1.apply(ComponentInventory.scala:117) [ComponentInventory$$anonfun$onItemAdded$1.class:?]
[B#347]  	at scala.Option.foreach(Option.scala:245) [scala-library-2.11.1.jar:?]
[B#347]  	at li.cil.oc.common.inventory.ComponentInventory$class.onItemAdded(ComponentInventory.scala:117) [ComponentInventory$class.class:?]
[B#347]  	at li.cil.oc.common.tileentity.Rack.li$cil$oc$common$tileentity$traits$ComponentInventory$$super$onItemAdded(Rack.scala:40) [Rack.class:?]
[B#347]  	at li.cil.oc.common.tileentity.traits.ComponentInventory$class.onItemAdded(ComponentInventory.scala:78) [ComponentInventory$class.class:?]
[B#347]  	at li.cil.oc.common.tileentity.Rack.onItemAdded(Rack.scala:361) [Rack.class:?]
[B#347]  	at li.cil.oc.common.inventory.Inventory$class.setInventorySlotContents(Inventory.scala:42) [Inventory$class.class:?]
[B#347]  	at li.cil.oc.common.tileentity.Rack.func_70299_a(Rack.scala:40) [Rack.class:?]
[B#347]  	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77) [aay.class:?]
[B#347]  	at li.cil.oc.common.container.StaticComponentSlot.li$cil$oc$common$container$ComponentSlot$$super$putStack(StaticComponentSlot.scala:8) [StaticComponentSlot.class:?]
[B#347]  	at li.cil.oc.common.container.ComponentSlot$class.putStack(ComponentSlot.scala:40) [ComponentSlot$class.class:?]
[B#347]  	at li.cil.oc.common.container.StaticComponentSlot.func_75215_d(StaticComponentSlot.scala:8) [StaticComponentSlot.class:?]
[B#347]  	at li.cil.oc.common.container.Player$$anonfun$tryTransferStackInSlot$4.apply$mcVI$sp(Player.scala:88) [Player$$anonfun$tryTransferStackInSlot$4.class:?]
[B#347]  	at li.cil.oc.common.container.Player$$anonfun$tryTransferStackInSlot$4.apply(Player.scala:83) [Player$$anonfun$tryTransferStackInSlot$4.class:?]
[B#347]  	at li.cil.oc.common.container.Player$$anonfun$tryTransferStackInSlot$4.apply(Player.scala:83) [Player$$anonfun$tryTransferStackInSlot$4.class:?]
[B#347]  	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778) [scala-library-2.11.1.jar:?]
[B#347]  	at scala.collection.immutable.Range.foreach(Range.scala:160) [scala-library-2.11.1.jar:?]
[B#347]  	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777) [scala-library-2.11.1.jar:?]
[B#347]  	at li.cil.oc.common.container.Player.tryTransferStackInSlot(Player.scala:83) [Player.class:?]
[B#347]  	at li.cil.oc.common.container.Player.func_82846_b(Player.scala:48) [Player.class:?]
[B#347]  	at net.minecraft.inventory.Container.func_75144_a(SourceFile:193) [zs.class:?]
[B#347]  	at li.cil.oc.common.container.Player.func_75144_a(Player.scala:35) [Player.class:?]
[B#347]  	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:883) [nh.class:?]
[B#347]  	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) [ix.class:?]
[B#347]  	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) [ix.class:?]
[B#347]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[B#347]  	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
[B#347]  	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
[B#347]  	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
[B#347]  	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
[B#347]  	at fastcraft.at.a(F:978) [fastcraft-1.23.jar:?]
[B#347]  	at fastcraft.H.aq(F:36) [fastcraft-1.23.jar:?]
[B#347]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
[B#347]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[B#347]  Caused by: li.cil.repack.com.naef.jnlua.LuaRuntimeException: could not read data
[B#347]  	at li.cil.repack.com.naef.jnlua.LuaState.lua_pcall(Native Method) ~[LuaState.class:?]
[B#347]  	at li.cil.repack.com.naef.jnlua.LuaState.call(LuaState.java:677) ~[LuaState.class:?]
[B#347]  	at li.cil.oc.server.machine.luac.PersistenceAPI.unpersist(PersistenceAPI.scala:164) ~[PersistenceAPI.class:?]
[B#347]  	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.load(NativeLuaArchitecture.scala:363) ~[NativeLuaArchitecture.class:?]
[B#347]  	... 39 more
[B#347]  [15:37:34] [Server thread/WARN] [OpenComputers]: A component of type 'disk_drive' disappeared (ade81dcb-d8c6-4a36-ac59-aed7561f974d)! This usually means that it didn't save its node.
[B#347]  [15:37:34] [Server thread/WARN] [OpenComputers]: A component of type 'screen' disappeared (5d0563b5-11df-47fc-9476-a8127658a3af)! This usually means that it didn't save its node.
[B#347]  [15:37:34] [Server thread/WARN] [OpenComputers]: A component of type 'keyboard' disappeared (425e52e7-6006-472d-b551-abf02282421b)! This usually means that it didn't save its node.
[B#347]  [15:37:34] [Server thread/WARN] [OpenComputers]: A component of type 'server_destruct' disappeared (5608902c-2798-4d6c-8255-809595a83476)! This usually means that it didn't save its node.
[B#347]  [15:55:45] [Server thread/INFO]: Saving and pausing game...
```

after some looking around it appears that it was actually a self destructor(computronics) in a server that delete it causing the game to crash

**Comment by Vexatos** [comment] 2016-12-11 07:49
Which versions of OpenComputers and Computronics are you using?

**Comment by Vexatos** [comment] 2016-12-11 11:34
Looks like a duplicate of #2123.

**Comment by SpicyForthProgrammer** [comment] 2016-12-12 13:05
1.6.0.9

**Comment by payonel** [comment] 2017-12-04 09:50
i blame computronics :)

**Closed as completed by payonel** 2017-12-04 09:50 UTC
