### ISSUE TITLE
1.12.2 Support

### ISSUE THREAD

**Issue by D3nnis3n** [MightyPirates/OpenComputers#2537] opened 2017-09-21 22:32 UTC
Would you mind implementing 1.12.2 Support? To be honest i was pretty surprised OpenComputers was the only mod not working in 1.12.2.

**Comment by LiEyWe** [comment] 2017-09-22 10:24
#2530

**Comment by Vexatos** [comment] 2017-09-22 10:43
Duplicate of #2530.

**Closed as completed by Vexatos** 2017-09-22 10:43 UTC
