### ISSUE TITLE
Redstone card doesn't work

### ISSUE THREAD

**Issue by thedimas3007** [MightyPirates/OpenComputers#3478] opened 2021-10-02 21:38 UTC
It only works as an input and can't control redstone around computer/redstone controller

Forge version: 1.12.2:2855
Minecraft version: 1.12.2
OpenComputers version: 1.7.5.217

**Comment by thedimas3007** [comment] 2021-10-02 21:39
when i run setOutput(1,15) in lua console, redstone on redstone controller doesn't change

**Comment by Ocawesome101** [comment] 2021-10-02 22:00
I've just experienced this issue also.  Also on build 217.

**Comment by mihis** [comment] 2021-11-08 19:36
Looks like a duplicate of #3470 

Try to reproduce on build 216

**Comment by asiekierka** [comment] 2022-06-08 17:11
IMO this is a regression from https://github.com/MightyPirates/OpenComputers/commit/59d63fe57ecee6d11971bf02fd0633325889acd1

**Comment by Ocawesome101** [comment] 2022-06-09 04:56
I thought this was fixed in 218?

**Comment by CaitlynMainer** [comment] 2022-06-09 09:05
Same, I thought https://github.com/MightyPirates/OpenComputers/pull/3449 took care of this?

**Comment by asiekierka** [comment] 2022-06-09 19:06
Oh, it was only merged in December. I see. I got the dates wrong!

**Closed as completed by asiekierka** 2022-06-09 19:06 UTC
