### ISSUE TITLE
[pams] crafting.craft() can lock the main thread

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1816] opened 2016-05-25 06:23 UTC
When crafting with items with multiple results and the 3,7, or 11 slot selected (the right most column of the 3x3 crafting grid)
![2016-05-24_23 05 15](https://cloud.githubusercontent.com/assets/2107834/15529768/7c88cbbc-2204-11e6-9bf0-f4ff03c55e68.png)

It will lock the main thread of the game and never return, In most cases this requires forcibly killing java to close the server

This has been tested with 
- [water bucket] - shapeless, Pams havest craft, returns (empty) bucket and pams water bucket

Other shapeless recipes don't exhibit this behavior (including pams ie milk bucket is fine)
Other shaped recipes don't exhibit this behavior

OpenComputers-MC1.7.10-1.5.22.42-universal
Pam's HarvestCraft 1.7.10Lb
MC 1.7.10
Forge 1566

**Comment by fnuecke** [comment] 2016-05-25 16:54
Can't reproduce in 1.6, I'm guessing this is a duplicate of #1651.
If this also happens in 1.6 for you, let me know and I'll reopen.

**Closed as completed by fnuecke** 2016-05-25 16:54 UTC

**Comment by xarses** [comment] 2016-05-25 17:18
`crafting.craft(1)` as mentioned in #1651 prevents the lockup, so its most likely the same issue
