### ISSUE TITLE
Crash when using Nanomachines

### ISSUE THREAD

**Issue by Versalkul** [MightyPirates/OpenComputers#2278] opened 2017-02-21 12:50 UTC
I was using this example programm: https://gist.github.com/fnuecke/dc8c79bfb37e66f99649

When i tried option 11 (getName) the game crashed

Crash log : [crashlog.txt](https://github.com/MightyPirates/OpenComputers/files/790105/crashlog.txt)

**Comment by Vexatos** [comment] 2017-02-21 13:25
Duplicate of #2242 and #2220. I has already been fixed.

**Closed as completed by Vexatos** 2017-02-21 13:25 UTC
