### ISSUE TITLE
the internet card gives issues whit oppm  end irc chat but not whit wget

### ISSUE THREAD

**Issue by FINK89i** [MightyPirates/OpenComputers#3699] opened 2024-04-04 14:48 UTC
hello sdag i decied to make a computer but afther i build a level 2 pc whit apu end internet card 512k of ram end 1 mb of storage afther ive installed open os end network i was installin oppm but it say no internet but i have  so i instaled irc for ask some help they could not help me but wget works idk if pastebin does but also afther a reboot irc also died  idk before on another world all worked fine but also they stped working i tried to download a vm of opencomputers end on there they work fine so idk please help also i lost the logs but i can make new ones if u need

**Comment by asiekierka** [comment] 2024-04-07 08:51
Duplicate of https://github.com/MightyPirates/OpenComputers/issues/3700

**Closed as completed** 2024-04-07 08:51 UTC
