### ISSUE TITLE
Lua Interpreter Tab Completion Errors

### ISSUE THREAD

**Issue by J0SLAN** [MightyPirates/OpenComputers#1671] opened 2016-02-25 02:27 UTC
Tab-completion for the stock Lua interpreter on OpenOS errors whenever it finds a number instead of a string, and also works for strings that have non-alphanumeric characters, for which it shouldn't. Just minor bugs.

**Comment by fnuecke** [comment] 2016-02-27 12:47
Please provide the strings this is reproducible with (i.e. what's in the input when you hit tab), thanks.

**Comment by payonel** [comment] 2016-03-01 19:37
@J0SLAN 
yes please do. OpenOS 1.6 tab completion has a lot of improvements, I'd want to test your use case against it.

**Comment by J0SLAN** [comment] 2016-03-01 20:09
@fnuecke @payonel 
Specifically, I'm pulling NBT from blocks with the Debug Card. The tab completion errors whenever I hit a table that's enumerated (like from an array of arrays), as it finds a number where it wanted a string.

Some labels for the tags have non-alphanumeric characters, like a colon, which works just fine until you try to access the value and it errors because syntax doesn't allow non-alphanumeric chars for dot indexing (=blah.foo.bar:baz doesn't work). I believe that it shouldn't even allow tab-completion here for this reason.

**Comment by payonel** [comment] 2016-03-02 02:54
@J0SLAN I apologize, I'm unsure how to repro and test and fix this. Are you using OpenOS 1.6? If not, please upgrade to latest and retest, I won't be fixing deprecated code. If you do have 1.6, what method is failing? sh.getMatchingFIles? Are you saying filesystem.list() is returning ints and not strings?

Thanks :) I'm quite invested in making this work.

**Comment by gjgfuj** [comment] 2016-03-02 03:00
@payonel it looks like they're looking at "lua.lua" specifically.

**Comment by payonel** [comment] 2016-03-02 03:21
@gjgfuj ah yes...also, in the title :) makes more sense now.

**Comment by payonel** [comment] 2016-03-02 03:27
@J0SLAN would https://git.io/v21k9 work for you?

**Comment by fnuecke** [comment] 2016-03-12 12:41
Given the massive rework/rewrite of OpenOS/term I'm almost certain this isn't an issue anymore. If it does still happen with OC 1.6/OpenOS 1.6, please let us know.

**Comment by Forecaster** [comment] 2016-04-04 17:05
Trying to tab-complete sides in the lua prompt causes this:
http://imgur.com/ZyMKUFv

It's apparently related to this : P

**Comment by payonel** [comment] 2016-04-04 17:09
@fnuecke I'll repro this tonight to confirm, but it sounds legit. If so, we should reopen this and I'll submit a fix for it.

**Comment by fnuecke** [comment] 2016-04-04 19:40
Let me know how it goes :)

**Comment by payonel** [comment] 2016-04-05 04:53
Yes it repros
1. lua -- go to lua prompt
2. =sides -- load sides into env
3. =sides.[tab] -- build hint list for sides
-> crash (sides has number keys that don't play nice with .. )

I decided to just push this fix on top of https://github.com/MightyPirates/OpenComputers/pull/1737 which closes this issue

**Closed as completed** 2016-04-14 21:45 UTC
