### ISSUE TITLE
Robot can't place blocks in the air

### ISSUE THREAD

**Issue by Litvinosss** [MightyPirates/OpenComputers#2573] opened 2017-10-22 15:47 UTC
Robot can't place blocks in the air without a reference block with Angel Upgrade
`robot.place()` returns false. 
I use OC 1.12.1-1.7.1.44, Forge 1.12.2-14.23.1.2566

**Comment by Pizzn** [comment] 2017-10-24 18:08
I quickly tested this, because I haven't had any problems with this so far.
My setup:
OC 1.10.2-1.7.0.124
Forge 1.10.2 2511

Robot
![robot](https://user-images.githubusercontent.com/19887865/31960073-df5c2c86-b8f6-11e7-8a97-83db02fb881e.jpg)

Results
![result_lua](https://user-images.githubusercontent.com/19887865/31960081-e4aa8e80-b8f6-11e7-9b82-bf1be85d7cef.jpg)

![result_blocks](https://user-images.githubusercontent.com/19887865/31960146-16aedfd0-b8f7-11e7-9acf-c5e4cc5f26a1.jpg)

**Comment by Litvinosss** [comment] 2017-10-24 18:49
My version is 1.12.1-1.7.0.20 fn

**Comment by Litvinosss** [comment] 2017-12-19 10:18
Demonstration of the bug:
![1](https://user-images.githubusercontent.com/32991055/34152228-8808acfc-e4b6-11e7-886c-0bfb3b087c87.png)
![2](https://user-images.githubusercontent.com/32991055/34152239-90dd6278-e4b6-11e7-8e2d-1435371bff98.png)
![3](https://user-images.githubusercontent.com/32991055/34152246-964f0806-e4b6-11e7-9f01-1b542d9a789d.png)

**Comment by frozenbrain** [comment] 2018-01-07 01:09
Apparently this change in UpgradeAngel.scala broke the angel upgrade: https://github.com/MightyPirates/OpenComputers/commit/ec6356bbc38e24ab2c074de048f5d2b41e201d53#diff-4f75727781091e2e38e1fdffa1cc6caf
Reverting it (ie. adding back `withComponent("angel")`) fixed the issue in my tests as the AngelUpgradeHandler ignores all nodes which are not components.

**Comment by Vexatos** [comment] 2018-01-07 01:41
It might be nicer to patch AngelUpgradeHandler instead, then.

**Comment by theArhar** [comment] 2018-02-12 18:58
Still not fixed?

**Comment by OvisMaximus** [comment] 2018-03-24 15:26
Tried to create a build locally to fix this bug for my game, but failed:

Warning:<i><b>root project 'OpenComputers': Unable to build Scala project configuration</b>
Details: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':compile'.
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve :ExtraCells:api-1.12.2-2.5.3a25.
Required by:
    li.cil.oc:OpenComputers:MC1.12.2-1.7.2+ac67d8ba3
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve :ExtraCells:api-1.12.2-2.5.3a25.
Caused by: org.gradle.internal.resource.ResourceException: Could not get resource 'http://addons-origin.cursecdn.com/files/2500/596/ExtraCells-api-1.12.2-2.5.3a25.xml'.
Caused by: org.gradle.api.UncheckedIOException: Could not GET 'http://addons-origin.cursecdn.com/files/2500/596/ExtraCells-api-1.12.2-2.5.3a25.xml'. Received status code 403 from server: Forbidden</i>

Could you either fix this or provide a experimental 1.7.3 build so that the Angel Upgrade works again?

**Comment by payonel** [comment] 2018-03-24 17:23
this is marked for 1.7.3, when this ticket closes you'll be able to grab the dev build for it from http://ci.cil.li/

**Comment by ExDomino** [comment] 2018-05-03 15:55
This is still not fixed apparently. I made a robot especialy to place block in air and it doesn't work!

**Comment by skyem123** [comment] 2018-05-03 16:08
@ExDomino, OC 1.7.3 hasn't been released yet though? So this ticket is still open, as it's still not fixed 😜 (yet)

**Comment by payonel** [comment] 2018-09-22 13:57
sorry it took so long, this is fixed now (dev builds https://ci.cil.li/ )

**Closed as completed** 2018-09-22 13:56 UTC
