### ISSUE TITLE
There were errors running the class transformer. Please report this

### ISSUE THREAD

**Issue by SirWoofie** [MightyPirates/OpenComputers#2071] opened 2016-09-27 00:23 UTC
Using a customized version of the 1.10.2 modpack All The Mods (Renamed to Grid)

[CHAT] §aOpenComputers§f: There were §cerrors§f running the class transformer. Please report this, together with your (full!) FML §alatest.log§f/§afml-server-latest.log§f logfile, thank you!

[latest.txt](https://github.com/MightyPirates/OpenComputers/files/494335/latest.txt)

**Comment by magik6k** [comment] 2016-09-27 10:36
Very likely related to #1998

**Comment by Alaberti** [comment] 2016-10-01 13:01
Try the dev builds: http://ci.cil.li/job/OpenComputers-dev-MC1.10/ #maybeunstable

**Comment by RobertLSnead** [comment] 2016-10-02 18:49
Has there been a fix for this yet?  It appears to affect single player, afraid to test on server don't want to crash my world!

**Comment by Vexatos** [comment] 2016-11-14 18:20
Without `fml-client-latest.log`, I won't know what is erroring. It is likely a duplicate of #1998 so I'll be closing this for now. Does this message still appear using the latest release of OpenComputers (1.6.0)?

**Closed as completed** 2016-11-14 18:39 UTC
