### ISSUE TITLE
Crash with OC and AE2

### ISSUE THREAD

**Issue by LizzyTrickster** [MightyPirates/OpenComputers#3169] opened 2019-11-02 21:52 UTC
OC Version: 1.12.2 1.7.4.184
AE2 Version: RV6 Stable 7

When starting a server, after the world has loaded it crashes with the below. 

Crashlog: https://files.lizzian.uk/crash-2019-11-02_12.46.35-server.txt

Weirdly enough, if I strip out all the mods bar OC, AE2, FTBUtils and Forge Essentials (i think the blocks that cause the error are in player-set chunkloaded chunks) the server starts fine. But if I then put all the mods back again it goes back to crashing with the same error.

Mods in the pack: https://pastebin.com/btVita2m

**Comment by PH4DE** [comment] 2019-11-03 12:26
I'm not technical, nor am I familiar with names or anything but I have pretty much the same issue. However on my side, my crash is only from OC. (As far as I am aware so far) but i run my mods out of technic, therefore no crash report. My crashes happen whenever I attempt to load up generally any world that otherwise works fine. I would really like to know what is the cause here, as OpenSecurity apparently cannot run without OpenComputers.

Here are my mods. if useful http://prntscr.com/pru0me (sorry for blurry screenshot, I don't know how to use pastebin or anything like that)

**Comment by payonel** [comment] 2019-11-07 07:24
this is fixed in latest dev builds since the 1.7.4 build, added a check that should stop this inf recursion

**Closed as completed by payonel** 2019-11-07 07:24 UTC
