### ISSUE TITLE
[1.11.2] Galacticraft aluminum wires do not connect to power converter

### ISSUE THREAD

**Issue by ioan-assenov** [MightyPirates/OpenComputers#2482] opened 2017-08-05 16:34 UTC
**Minecraft version:** 1.11.2
**OpenComputers version:** 1.11.2-1.7.0.24
**Forge version:** 13.20.1.2425

On Multiplayer (Dedicated Server)

**Mods Installed:** 
- Galacticraft (Version: 1.11.2-4.0.0.115)
- OpenComputers (Version: 1.11.2-1.7.0.24)
- Just Enough Items (Version: 1.11.2-4.5.0.294)

**Issue Description:**
On the OpenComputers wiki, it says that Galacticraft's aluminum/heavy aluminum wires may be used to provide power to the converter but they don't connect at all. I tried with some other blocks from the OpenComputers mod but the aluminum wires just refuse to connect. I uploaded this issue on the Galacticraft issue tracker but I was sent to ask here instead.

**Screenshot:**
![screen shot 2017-08-05 at 15 34 23](https://user-images.githubusercontent.com/20500877/28995508-919b1814-79f3-11e7-9092-90e7a461573d.png)

**Comment by xarses** [comment] 2017-08-05 21:26
1.11 support is still quite alpha, most of the power does't work, we can consider this a duplicate of #2468

**Comment by purplemonday** [comment] 2017-08-08 05:46
did you actualy check its not transfering energy or are you asuming it doesnt?
i meen there exsamples of this ocurance where the wires wont connect but the energy does flow.

exsample some ic2 addon generators do inject energy into the cable while it looks like not connected.

**Comment by payonel** [comment] 2018-09-24 06:10
this is definitely working now :)
i tested with our latest 1.11 builds and gc's latest, their cables and our converters definitely connect and power is flowing through

**Closed as completed by payonel** 2018-09-24 06:10 UTC
