### ISSUE TITLE
Bug when connecting to a server / join a client world

### ISSUE THREAD

**Issue by ynerant** [MightyPirates/OpenComputers#669] opened 2014-11-13 22:56 UTC
Hello,
When I try to join a world, from my client or a server, which contains the mod, My client says "A fatal error has occured." I run with le latest release (1.4.0-rc2). In the log, there is :

```
[23:37:10] [Client thread/ERROR] [FML/]: There was a critical exception handling a packet on channel NEI
java.lang.NoClassDefFoundError: Could not initialize class li.cil.oc.common.Loot$
    at li.cil.oc.common.init.Items$$anon$1.func_150895_a(Items.scala:103) ~[Items$$anon$1.class:?]
    at codechicken.nei.api.ItemInfo.searchItems(ItemInfo.java:364) ~[ItemInfo.class:?]
    at codechicken.nei.api.ItemInfo.load(ItemInfo.java:97) ~[ItemInfo.class:?]
    at codechicken.nei.NEIClientConfig.bootNEI(NEIClientConfig.java:258) ~[NEIClientConfig.class:?]
    at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:208) ~[NEIClientConfig.class:?]
    at codechicken.nei.NEICPH.handleSMPCheck(NEICPH.java:109) ~[NEICPH.class:?]
    at codechicken.nei.NEICPH.handlePacket(NEICPH.java:23) ~[NEICPH.class:?]
    at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:98) ~[PacketCustom$ClientInboundHandler.class:?]
    at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:75) ~[PacketCustom$CustomInboundHandler.class:?]
    at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:62) ~[PacketCustom$CustomInboundHandler.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2050) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_05]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
```

Can you helpme please ?

**Comment by fnuecke** [comment] 2014-11-13 23:04
Duplicate of #631.

**Closed as completed by fnuecke** 2014-11-13 23:04 UTC
