### ISSUE TITLE
MC client crash when clicking on screen.

### ISSUE THREAD

**Issue by shortybsd** [MightyPirates/OpenComputers#881] opened 2015-02-01 08:47 UTC
Minecraft version: 1.7.10
Forge version: 10.13.2.1286

Steps to replicate this Minecraft crash.
1.) Place down a Tier 1 case
2.) Place on top of case a Tier 2 Screen via shift+right-click
3.) Install Memory Tier 1
4.) Install Memory Tier 1.5
5.) Install CPU Tier 1
6.) Install HDD Tier 1 (with OpenOS installed)
7.) Install LUA Bios
8.) Install Graphics Card Tier 1
9.) Install Keyboard (on left side on screen, via shift+right-click)
10.) Turn on pc
11.) Right click monitor and click anywhere in the black area of the terminal.
CRASH

Pastebin of crash http://www.pastebin.com/QVrK5NEJ

Only things changed in the default OpenComputers.cfg is
line 372 bufferChanges=false to true
line 900 ignorePower=false to true

I can understand the crash being a Tier 1 computer doesn't understand touch events from a Tier 2 screen. Missing checks for it?

**Comment by fnuecke** [comment] 2015-02-01 11:58
Duplicate of #852.

If you have DragonAPI in your pack, remove the OC API from its JAR (the `li` folder). If you don't, hunt down whichever mod it is that ships the outdated OC API and remove it from that.

**Closed as completed by fnuecke** 2015-02-01 11:58 UTC
