### ISSUE TITLE
[1.7.10] Crash on Startup

### ISSUE THREAD

**Issue by Whimsyturtle** [MightyPirates/OpenComputers#2166] opened 2016-12-09 00:39 UTC
Crash Report: `[http://pastebin.com/BAJA7qc2](http://pastebin.com/BAJA7qc2)

**Comment by Vexatos** [comment] 2016-12-10 08:33
This is a very strange error. Could you try re-downloading the jar file?

**Comment by Vexatos** [comment] 2016-12-10 08:34
Looks like a duplicate of #1911. See that issue for a link to a workaround.

**Closed as completed by Vexatos** 2016-12-10 08:34 UTC
