### ISSUE TITLE
io netty detected a severe leak.

### ISSUE THREAD

**Issue by Marfjeh** [MightyPirates/OpenComputers#2879] opened 2018-07-04 08:53 UTC
MC: 1.12.2
Forge: 14.23.4.2705
Opencomputers: 1.7.2.67

Hi. i notiched that my game console is throwing: `SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.`
please forgive me if this is already been reported. i was not able to find the issue on here.

After i enabled the JVM arugment, it showed me this [log.txt](https://github.com/MightyPirates/OpenComputers/files/2162455/log.txt)

**Comment by Vexatos** [comment] 2018-09-10 16:16
Do you know of any way to reproduce this? It does not seem to happen for me.

**Comment by Marfjeh** [comment] 2018-09-10 19:21
Well, this happend out of nothing really. i didnt craft any of the machines yet. do you want t have a modlist parhaps?

**Comment by Vexatos** [comment] 2018-09-10 19:30
So it is not consistent and only happened once?

This should be independent of any mod in the pack, this would be between a change introduced in OpenComputers 1.7.2 and forge; the confusing part is that this should not be happening at all, specifically _because_ of the change fixing this.

**Comment by Marfjeh** [comment] 2018-09-10 19:33
This happend multiple times, even so that our clients started trying GC alot, resulting in lots of lag spikes, i do not know that is coming from this. I allowcated about 6 gigs and sometimes i can play for hours and sometimes for like a half an hour. and i'm not the only one that have this problem pretty much everyone on the server. The server never had any problems with memory at all, and i did even run for weeks with out reboot (because i forgot to do so)

**Comment by Vexatos** [comment] 2018-09-10 20:07
Do you know whether it also happens with OpenComputers 1.7.1? Does the message show up on clients or the server?

This issue does not cause the GC runs, rather, the frequent GC runs will cause this message to appear more often. It's a symptom and and not the cause.

**Comment by Marfjeh** [comment] 2018-09-11 20:32
> Do you know whether it also happens with OpenComputers 1.7.1? Does the message show up on clients or the server?

I updated the pack hoping that it was resoved but no. problem is i'm not sure that is was from 1.7.1 or a 
1.7.2 build, i dont have the history sadly.

> This issue does not cause the GC runs, rather, the frequent GC runs will cause this message to appear more often. It's a symptom and and not the cause.

Yeah, figered.

**Comment by Pizzn** [comment] 2018-11-22 17:17
I have encountered the same behavior.  After enabling the JVM flag I got this output which seems to differ slightly: [log_netty.txt](https://github.com/MightyPirates/OpenComputers/files/2608904/log_netty.txt). Maybe this helps you guys in any way. I tried to find steps to repro but did not really succeed. Tests were done in completely new world in multiplayer using only OC with default settings and these JVM args: jre1.8.0_181\bin\java -Xms4G -Xmx4G -Dio.netty.leakDetection.level=advanced.

OC 1.12.2-1.7.3.146 & 1.12.2-1.7.2.129
Forge 1.12.2-2768

Got these errors while standing beside a computer, typing into the screen; while being out of chunk loading range; while entering or exiting chunk loading range. After getting this error, computers in inactive chunks are _sometimes_ turned off, having their screen frozen. After a server restart, these computers are _very often_ in this state. Additionally, if someone approaches the inactive chunks, containing a computer, sometimes the server shows a gigantic lag spike of >80s per tick (exact number may be due to a moderate number of mods used), happening _mostly_ if the chunk was loaded for the first time.

**Comment by Marfjeh** [comment] 2018-11-29 11:03
interesting, after we used the mod, as i did for my controlling my reactor it didn't shutdown or frooze at all. but i also have a chunkloader nearby so that probably i didnt encounter this

**Comment by Pizzn** [comment] 2018-11-29 17:04
Yeah, it seems that keeping that chunks loaded with chunk loaders reduce the overall emergence of those lag spikes, but does not remove them completely, so I think there may be two independent(?) mechanisms for said exceptions and using chunkloaders removes one of them. The problems with frozen screens however, seem to be fixed that way. At least, I haven't encountered frozen screens since then, even after server restarts.
By the way, you have to keep in mind that this was observed with said netty leak detection flag enabled, which amplifies those lag spikes in intensity and frequency by a factor of at least 10 I'd say.

**Comment by mckuhei** [comment] 2020-05-11 10:13
Hey, I have same problem. I don't know what happend to triggle this problem.But I has some logs.
-rw-r--r--  1 coding coding 3.9M Feb 23 19:25 '[1.12.2]应用能源2-appliedenergistics2-rv6-stable-7.jar'
-rw-r--r--  1 root   root   1.1M Feb 26 17:20 '[1.12.x]原版修复-VanillaFix-1.0.10-99.jar'
-rw-r--r--  1 coding coding  29M Mar 28 18:36  AcademyCraft.jar
-rw-r--r--  1 coding coding 310K Nov 23 11:24  Advanced+Solar+Panels-4.3.0.jar
-rw-r--r--  1 coding coding 4.3M Nov 23 10:49  buildcraft-7.99.19.jar
-rw-r--r--  1 coding coding 310K Nov 23 10:47  CarryOn+MC1.12.2+v1.12.2.jar
-rw-r--r--  1 coding coding 685K Nov 23 10:47 'CodeChickenLib 1.12.2.jar'
-rw-r--r--  1 coding coding 1.3M Apr 12  2019  Computronics-1.12.2-1.6.6.jar
-rw-r--r--  1 coding coding 3.1M Nov 23 10:48  extrautils2-1.12-1.9.9.jar
-rw-r--r--  1 coding coding 207K Apr  4  2019  foamfix-0.10.5-1.12.2.jar
-rw-r--r--  1 coding coding 444K Oct 20  2019  Hwyla-1.8.26-B41_1.12.2.jar
-rw-r--r--  1 coding coding 7.8M Nov 23 11:18  industrialcraft-2-2.8.110-ex112.jar
-rw-r--r--  1 coding coding 631K Jan 31  2019  jei_1.12.2-4.14.4.264.jar
-rw-r--r--  1 coding coding 150K Nov 23 10:47 '[MC1.12.2]DeconTable-3.0.4.jar'
-rw-r--r--  1 coding coding 170K Nov 23 10:47  MCMultiPart-2.5.3.jar
-rw-r--r--  1 coding coding 7.5M Nov 23 10:47  Mekanism-1.12.2-9.8.1.383.jar
-rw-r--r--  1 coding coding 127K Mar 30 14:57  obfuscate-0.4.2-1.12.2.jar
-rw-r--r--  1 coding coding  80K Feb 23 19:24  ocsensors-1.0.4-b23.jar
-rw-r--r--  1 coding coding 3.1M May  5 14:27  OpenBlocks-1.12.2-1.8.1.jar
-rw-r--r--  1 coding coding  15M May  4 18:13  OpenComputers-MC1.12.2-1.7.5.192.jar
-rw-r--r--  1 coding coding 2.6M May  5 14:27  OpenModsLib-1.12.2-0.12.2.jar
-rw-r--r--  1 coding coding 737K Feb 23 19:19  OpenPython-MC1.12.2-OC1.7-1.0.1.jar
drwxr-xr-x  3 coding coding 4.0K Feb 23 19:29  OpenSecurity
-rw-r--r--  1 coding coding 575K Feb 23 19:28  OpenSecurity-1.12.2-1.0-39.jar
-rw-r--r--  1 coding coding 2.2M Oct 20  2019  OptiFine_1.12.2_HD_U_E3_MOD.jar
-rw-r--r--  1 coding coding 3.2M Apr 13 10:02  prefab-1.3.0.26.jar
-rw-r--r--  1 coding coding 1.8M Apr 24  2019  ProjectE-1.12.2-PE1.4.1.jar
-rw-r--r--  1 coding coding 3.2M Jul 31  2019  RandomThings-MC1.12.2-4.2.7.3.jar
drwxr-xr-x  2 root   root   4.0K Feb 26 21:18  rtm
-rw-r--r--  1 coding coding 4.9M Nov 23 10:53 'Shadowfacts&#039; Forgelin 1.9.4_1.10.2_1.12.x.jar'
-rw-r--r--  1 coding coding 133K Mar 14 10:24  spongeforge-1.12.2-2838-7.1.10.jar
-rw-r--r--  1 coding coding 3.9M Nov 23 10:48  TConstruct-1.12.2-2.12.0.157.jar
-rw-r--r--  1 coding coding  14M Apr 12 10:23  tektopia-1.1.0.jar
-rw-r--r--  1 coding coding  40K Nov 23 10:47  torcherino-7.5.jar
-rw-r--r--  1 coding coding 2.2M Apr 10 11:42  vehicle-mod-0.43.5-1.12.2.jar
-rw-r--r--  1 coding coding  31K Nov 23 10:47 'Waila Harvestability 1.12.x.jar'
-rw-r--r--  1 coding coding 329K Nov 23 10:47 'Mekanism Generators 1.12.2.jar'
-rw-r--r--  1 coding coding 925K Nov 23 10:49 'Mantle 1.12.2.jar'
-rw-r--r--  1 coding coding 822K Nov 23 10:53 'IronChest 1.12.2.jar'
-rw-r--r--  1 coding coding 2.2M Mar 28 18:24  Sakura.jar
-rw-r--r--  1 coding coding 914K Mar 29 18:30  WaterPower.jar
-rw-r--r--  1 coding coding 126K Apr  5 14:12  VinerMine.jar
and some mod ONLY can download in Chinese forum
[latest (1).log](https://github.com/MightyPirates/OpenComputers/files/4608929/latest.1.log)

**Comment by Bobcat64** [comment] 2020-07-31 02:19
Saw mine do this twice when I think my base chunk unloaded.

Several of the lines point to [PacketHandler.scala Line 279](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/server/PacketHandler.scala#L279) which suggests the assembler. I do have an assembler built... its actually not connected any more and I haven't ever used it yet.

Log with both instance (they were seconds apart):
[minecraft.log](https://github.com/MightyPirates/OpenComputers/files/5004575/minecraft.log)

Minecraft 1.12.2
Forge 14.23.5.2854
Open Computers MC1.12.2-1.7.5.192.jar

**Comment by asiekierka** [comment] 2022-06-08 23:33
Pretty sure this is fixed now.

**Closed as completed by asiekierka** 2022-06-08 23:33 UTC
Labels: bug
