### ISSUE TITLE
"There were errors running the class transformer."

### ISSUE THREAD

**Issue by deathaplenty** [MightyPirates/OpenComputers#2085] opened 2016-10-06 20:27 UTC
I get this error message in chat whenever I load a world. Here's my latest.log file converted to text so Git would accept it: [latest.txt](https://github.com/MightyPirates/OpenComputers/files/514733/latest.txt)

**Comment by Aleszp** [comment] 2016-10-09 10:45
Same happens to me:
FML log:
http://pastebin.com/4QmXTxWd

**Comment by ccourson** [comment] 2016-10-10 22:43
I am also having this issue. I've placed server and client logs and a screen clipping of the error in this Dropbox folder: https://www.dropbox.com/sh/m5sm3yqt7xjbjuk/AADm-OCfFQT3qCp2Aqb7LBBPa?dl=0 

The server logs begin with "server-", the client logs begine with "client-"

**Comment by th4umiel** [comment] 2016-10-12 06:44
Same for me D:

**Comment by Tradeaux** [comment] 2016-10-21 08:59
yes i'm getting the same error with the HermitPack any fix yet?

**Comment by Vexatos** [comment] 2016-11-14 18:38
Duplicate of #1998 and partially of #2014.

**Closed as completed by Vexatos** 2016-11-14 18:38 UTC
