### ISSUE TITLE
Screen turning other blocks red.

### ISSUE THREAD

**Issue by ErdrickXLII** [MightyPirates/OpenComputers#1648] opened 2016-02-11 03:54 UTC
I have a Tier 2 screen connected to a computer.  The screen is full of commands and such.  I typed a command that doesn't exist, generating a 'file not found' error.  I press escape and now, as long as the screen block is visible, certain blocks around it now have a red tint to them.  They remain red until I enter a commend that does not return 'file not found'.

**Comment by dgelessus** [comment] 2016-02-11 17:51
Do you have Optifine installed? I had the same issue a while back, though I can't remember if removing Optifine fixed it or if I ever reported it.

**Comment by ErdrickXLII** [comment] 2016-02-11 17:59
I do not have Optifine installed or FastCraft or anything like that.  The only mods I have installed are OC, Thaumcraft 5, Chisels and Bits, and JEI.

**Comment by dgelessus** [comment] 2016-02-11 18:02
Hm #1083

**Comment by ErdrickXLII** [comment] 2016-02-11 18:13
Yeah, that's it exactly.
Oh, forgot to mention, I'm using the 1.8.9 build (1.5.22.6), in case that matters.

**Comment by fnuecke** [comment] 2016-02-27 18:38
Please let me know if this is fixed in the latest builds, if it isn't, I have no idea how to fix it >_>

**Comment by ErdrickXLII** [comment] 2016-03-03 06:01
Updated to 1.6.0.14, but it's still doing it.

**Comment by fnuecke** [comment] 2016-03-12 11:42
Well, I can't reproduce it so someone who can will need to investigate this.

**Closed as completed** 2017-10-04 03:14 UTC
