### ISSUE TITLE
Link keyboards to computers, not just screens

### ISSUE THREAD

**Issue by FredMSloniker** [MightyPirates/OpenComputers#509] opened 2014-08-22 06:46 UTC
I was rather surprised to discover that my arrangement of OpenComputers components didn't work--I could turn the computer on, but I couldn't type. Eventually I worked out that the keyboard has to be on, or adjacent to, the screen.

Which was a problem, as I was trying to have the computer and keyboard at one end of a small room and a 40-cube monstrosity screen at the other for folks to watch while I played Hunt the Wumpus or something.

Why do keyboards link to screens anyway? And why can't that link travel through a computer or a cable or something? I should be able to slap the keyboard onto the computer, or adjacent to the computer, and have it and the screen link up.

And while I'm at it, can we make keyboards less fragile? If I left-click on one without pick in hand, it instantly shatters, and I have to make a new one. My REAL keyboard can survive a single punch. Heck, why is a pick required to safely remove it at all?

**Comment by fnuecke** [comment] 2014-08-22 13:45
They have to be next to screens for the screens to know whether to open the GUI or not when right-clicked. I suppose the GUI only being available via the keyboard if it's not directly next to the screen might work, though I feel that'd be somewhat unintuitive.

"Fragile": I can't reproduce this. Are you sure you weren't in creative mode? As for needing a pick, I never gave this much thought, I always have some form of multitool with me anyway at the stage computers become feasible... but it's really just that way because of the material type. I might look into making them harvestable bare handed, we'll see.

**Comment by Wuerfel21** [comment] 2014-08-22 17:20
maybe some kind of keybord-cable that you lay out like rp2 cables, and connect the keyboard to the first screen it finds.

**Comment by FredMSloniker** [comment] 2014-08-23 02:59
I wasn't in creative mode, no. I might have been enchanted with strength from a beacon at the time, though. Still, keyboards should be harvestable bare-handed.

As for the keyboard linking to screen thing: maybe keyboards should be able to follow the same networking rules as other components? So if you place a keyboard adjacent to (or on) a computer that's connected to a screen by cable, it'll link to the screen?

**Comment by SpiritedDusty** [comment] 2014-09-03 23:47
I agree with making the keyboard a regular component because in my opinion, it wouldn't make logical sense that you can't "open" a screen without a keyboard. I think keyboards should act as regular components and have a proximity range that the player needs to be in, in order the computer to receive key events.

**Comment by fnuecke** [comment] 2014-09-04 15:24
All right, so basically what would be required for this is a `bind` logic similar to what GPUs currently have, but on keyboards. And that has to be synchronized to the client to know which GUI to open when the keyboard is right-clicked. I'll see if that's all it takes, but it might get more complicated, so no ETA.

**Comment by FredMSloniker** [comment] 2014-09-05 03:01
Hm. One complication that I just thought of: does this mean that computers would have a 'primary' keyboard and would ignore keystrokes from other keyboards unless they were explicitly made primary? And how would computers decide which keyboards are associated with them?

**Comment by fnuecke** [comment] 2014-09-05 09:25
There already is a primary keyboard, so that wouldn't change. The OS would need some new startup code to bind the primary keyboard to the primary screen, though.

**Comment by Kilobyte22** [comment] 2014-10-24 22:15
The thing is: If keyboard are not assigned to screens, we cannot have multiple seperate screen/keyboard combos without manually telling the computer which keyboard belongs to which screen

**Comment by SoniEx2** [comment] 2014-12-01 21:54
We need a terminal (craft with screen + keyboard), not a different way to hook keyboards to screens.

**Comment by MFernflower** [comment] 2015-01-28 21:50
@SoniEx2 I think that is a way better idea!

**Comment by S0ZDATEL** [comment] 2017-10-23 17:05
#2567

**Closed as completed** 2021-05-11 01:33 UTC
Labels: make-a-pr-if-you-want-this
