### ISSUE TITLE
Internet component crashing in certain situations

### ISSUE THREAD

**Issue by Thorinair** [MightyPirates/OpenComputers#2255] opened 2017-02-03 15:38 UTC
Hello!

I am building a website which will allow me to exchange data via the internet with OpenComputers, and I encountered a bit of an issue. The issue is related with the internet component - it seems to crash from too many connections, but only in some situations. I am using the internet.request() method. It doesn't appear to make a difference which address I am requesting, so in this example, I will request from Google's address.

```lua
local internet = require('internet')

local sleep = 1

function process()
  while true do
    
    print("Requesting.")
    internet.request("https://www.google.com")

    os.sleep(sleep)

  end
end

process()
```
The program above is causing a crash. The program will make a request to the specified address every second. It seems to be able to do this 4-6 times or so, and then it crashes due to "too many open connections" error. The duration of the sleep timer doesn't appear to affect anything. It will crash no matter how long the sleep is. Note that this crash is not a Minecraft server crash, but crash of the program itself within the OC computer.

```lua
local internet = require('internet')

local counter = 1
local interval = 2
local sleep = 0.5

function process()
  while true do
    
    if counter <= 1 then    
      print("Requesting.")
      internet.request("https://www.google.com")
      counter = interval
    else
      counter = counter - 1
    end

    os.sleep(sleep)

  end
end

process()
```
This program on the other hand does not crash, ever. It does essentially exactly the same thing, except that in every loop, it skips requesting a connection. However, due to the 0.5 second sleep, it still makes a request every second, exactly like the previous program.

I am not sure why the first program doesn't work, but the second one does. As far as I know, there should be no difference. Is there something weird going on under the hood?

**Comment by Vexatos** [comment] 2017-02-03 16:49
`internet.request` returns a userdata object. Calling `close()` on that object will make sure the connection doesn't stay open.

**Comment by Thorinair** [comment] 2017-02-03 16:59
I have tried that already, as I found it in the official documentation. However, I get the error: "attempt to index local 'handle' (a function value)".

**Comment by Vexatos** [comment] 2017-02-03 17:17
@payonel This seems to be related to the internet API not closing internet handles if nothing is ever read from them. Anything you can do about it?

**Comment by Thorinair** [comment] 2017-02-03 17:56
I had a growing suspicion that the following code will work. And without any surprise, it does in fact work. Using 2 sleeps instead of one seems to prevent the too many open connections error.

```
local internet = require('internet')

local sleep = 0.5

function process()
  while true do
    
    print("Requesting.")
    internet.request("https://www.google.com")

    os.sleep(sleep)
    os.sleep(sleep)

  end
end

process()
```

**Comment by payonel** [comment] 2017-02-03 18:25
I wonder if gc is closing the unused handle (note that we gc when there are sufficient yields (e.g. 20))
Perhaps the extra sleep is allowing the unused user data to release

As for what openos can do, I'll look into that.

**Comment by payonel** [comment] 2017-02-03 18:26
I'll also look into allowing `handle:close()`

**Closed as completed** 2017-02-04 22:56 UTC

**Comment by payonel** [comment] 2017-02-04 23:14
I confirmed that the sleeps are calling gc on the userdata, which closes the connection
We cannot call the gc ourselves, so your code example cannot be fixed as is (without the extra sleeps)
But, I have added access to the userdata on request result

so now you can:

```
local internet = require('internet')
while true do
    
  print("Requesting.")
  local request = internet.request("https://www.google.com")
  print(request()) -- or otherwise use the request results
  request.close()

  os.sleep(0) -- not necessary! just adding this here in case you want to abort the inf loop
  -- os.sleep throws an exception if you hold control+shift+c

end
```

**Comment by Thorinair** [comment] 2017-02-05 00:04
Awesome stuff, thank you!
