### ISSUE TITLE
minecraft crashes when computer reaches bios eof

### ISSUE THREAD

**Issue by etnpce** [MightyPirates/OpenComputers#1348] opened 2015-08-03 04:17 UTC
only tested on server in server rack, letting the computer reach eof in bios causes minecraft to hard crash

crash report:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  TransformerLoader (OpenComputers-MC1.8-1.5.14.32-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  CCCDeobfPlugin (unknown)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 8/2/15 8:55 PM
Description: Ticking block entity

java.util.NoSuchElementException: head of empty list
    at scala.collection.immutable.Nil$.head(List.scala:422)
    at scala.collection.immutable.Nil$.head(List.scala:419)
    at scala.collection.mutable.Stack.top(Stack.scala:132)
    at li.cil.oc.server.machine.Machine.update(Machine.scala:425)
    at li.cil.oc.common.tileentity.ServerRack$$anonfun$updateEntity$2.applyOrElse(ServerRack.scala:237)
    at li.cil.oc.common.tileentity.ServerRack$$anonfun$updateEntity$2.applyOrElse(ServerRack.scala:232)
    at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:136)
    at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:135)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at scala.collection.TraversableLike$class.collect(TraversableLike.scala:282)
    at scala.collection.mutable.ArrayOps$ofRef.collect(ArrayOps.scala:186)
    at li.cil.oc.common.tileentity.ServerRack.updateEntity(ServerRack.scala:232)
    at li.cil.oc.common.tileentity.traits.TileEntity$class.update(TileEntity.scala:39)
    at li.cil.oc.common.tileentity.ServerRack.func_73660_a(ServerRack.scala:31)
    at net.minecraft.world.World.func_72939_s(World.java:1735)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
    at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at scala.collection.immutable.Nil$.head(List.scala:422)
    at scala.collection.immutable.Nil$.head(List.scala:419)
    at scala.collection.mutable.Stack.top(Stack.scala:132)
    at li.cil.oc.server.machine.Machine.update(Machine.scala:425)
    at li.cil.oc.common.tileentity.ServerRack$$anonfun$updateEntity$2.applyOrElse(ServerRack.scala:237)
    at li.cil.oc.common.tileentity.ServerRack$$anonfun$updateEntity$2.applyOrElse(ServerRack.scala:232)
    at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:136)
    at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:135)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at scala.collection.TraversableLike$class.collect(TraversableLike.scala:282)
    at scala.collection.mutable.ArrayOps$ofRef.collect(ArrayOps.scala:186)
    at li.cil.oc.common.tileentity.ServerRack.updateEntity(ServerRack.scala:232)
    at li.cil.oc.common.tileentity.traits.TileEntity$class.update(TileEntity.scala:39)
    at li.cil.oc.common.tileentity.ServerRack.func_73660_a(ServerRack.scala:31)

-- Block entity being ticked --
Details:
    Name: oc:serverRack // li.cil.oc.common.tileentity.ServerRack
    Block type: ID #223 (tile.oc.serverRack // li.cil.oc.common.block.ServerRack)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-31,64,56), Chunk: (at 1,4,8 in -2,3; contains blocks -32,0,48 to -17,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #223 (tile.oc.serverRack // li.cil.oc.common.block.ServerRack)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1735)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)

-- Affected level --
Details:
    Level name: tis
    All players: 1 total; [EntityPlayerMP['etnpce'/226092, l='tis', x=-30.13, y=65.90, z=54.24]]
    Chunk stats: ServerChunkCache: 710 Drop: 0
    Level seed: -665930327309777182
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: 44.00,64.00,68.00 - World: (44,64,68), Chunk: (at 12,4,4 in 2,4; contains blocks 32,0,64 to 47,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 107812 game time, 5000 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 27303 (now: false), thunder time: 13582 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 641635792 bytes (611 MB) / 1420296192 bytes (1354 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1496 11 mods loaded, 11 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAAAAAAA  mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAAAAAAA  FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1496.jar) 
    UCHIJAAAAAAAAA  Forge{11.14.3.1496} [Minecraft Forge] (forge-1.8-11.14.3.1496.jar) 
    UCHIJAAAAAAAAA  CodeChickenCore{1.0.5.36} [CodeChicken Core] (minecraft.jar) 
    UCHIJAAAAAAAAA  NotEnoughItems{1.0.5.104} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.104-universal.jar) 
    UCHIJAAAAAAAAA  OpenComputers|Core{1.5.14.32} [OpenComputers (Core)] (minecraft.jar) 
    UCHIJAAAAAAAAA  bspkrsCore{7.01} [bspkrsCore] ([1.8]bspkrsCore-universal-7.01.jar) 
    UCHIJAAAAAAAAA  Treecapitator{1.8} [Treecapitator] ([1.8]Treecapitator-universal-2.0.5.jar) 
    UCHIJAAAAAAAAA  MouseTweaks{2.5.0} [Mouse Tweaks] (MouseTweaks-2.5.0-mc1.8.jar) 
    UCHIJAAAAAAAAA  OpenComputers{1.5.14.32} [OpenComputers] (OpenComputers-MC1.8-1.5.14.32-universal.jar) 
    UCHIJAAAAAAAAA  Waila{1.6.0_B1} [Waila] (Waila-1.6.0_B1_1.8.1.jar) 
    Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
TransformerLoader (OpenComputers-MC1.8-1.5.14.32-universal.jar)
  li.cil.oc.common.asm.ClassTransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
CCCDeobfPlugin (unknown)

NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['etnpce'/226092, l='tis', x=-30.13, y=65.90, z=54.24]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by etnpce** [comment] 2015-08-03 14:58
after a little testing, it appears to crash when reaching bios eof

**Comment by fnuecke** [comment] 2015-08-04 20:04
Uhh, reaching eof in bios? What do you mean by that? This looks more like some kind of race condition. Do you have some Lua code you can reproduce this reliably with?

**Comment by etnpce** [comment] 2015-08-04 22:05
ok, so it wasn't just reaching the end of file, I hadn't done much testing, so based of what I remember, it must be when the bios ends with the gpu still doing tasks

**Comment by fnuecke** [comment] 2015-08-04 22:37
The BIOS isn't a "file", so I'm still not quite understanding what you mean? Do you mean the function defined in the BIOS returns, thus stopping the computer? The GPU won't be "doing tasks" then, though, because there is no such thing as scheduled calls - all of them would have finished before the computer stops.

Either way, please see if you can reproduce this on the latest [dev-build](http://ci.cil.li), since there have been some changes/fixes in that area.

**Comment by etnpce** [comment] 2015-08-04 22:46
sorry, I was referring to the code in the eeprom as bios because that's what its called in errors when you use the analyzer, also from what I've read, the gpu has a delay before outputting to the screen which doesn't pause the computer, I probably misinterpreted something if it does.  Ill check the dev-build now

**Comment by etnpce** [comment] 2015-08-04 23:16
Still crashes with the dev build
code that crashes consistently:

``` lua
local scr=component.list("scr")()
local gpu=component.proxy(component.list("gpu")())
component.invoke(scr,"turnOn")
gpu.bind(scr)
dx,dy=gpu.maxResolution()
gpu.setResolution(dx,dy)
gpu.setPaletteColor(0,0)
gpu.setPaletteColor(1,0xFF0000)
gpu.setBackground(0,true)
gpu.setForeground(1,true)
gpu.fill(1,1,dx,dy," ")
gpu.set(dx/2-7,dy/2,"COMMUNICATION")
gpu.set(dx/2-3,dy/2+1,"ERROR")
gpu.setBackground(1,true)
gpu.fill(1,1,dx,1," ")
gpu.fill(1,1,1,dy," ")
gpu.fill(1,dy,dx,1," ")
gpu.fill(dx,1,1,dy," ")
gpu.fill(dx/10,dy/5,dx-2*dx/10,2," ")
gpu.fill(dx/10,dy-dy/5-1,dx-2*dx/10,2," ")
```

just adding computer.shutdown() to the end causes it not to crash

**Comment by fnuecke** [comment] 2015-08-04 23:54
Thanks, that helped narrow it down! Should be fixed in the next dev build.

(For the record, yes the location was clear from the trace, but I didn't see the code path that could actually end up there with the state being as it had to be for the error to occur, and I dislike "blind" fixes :P)

**Closed as completed** 2015-08-04 23:53 UTC
