### ISSUE TITLE
[feature-suggested] Bitmapped/pixel graphics

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1901] opened 2016-06-21 21:00 UTC
I'd like to request a bitmapped/pixel graphics mode for graphics cards (maybe tier 2+?) and screens. I have an API proposal:
- `gpu.setMode(graphical: boolean): boolean`: Switches the GPU between graphical and text modes. Returns `true` on success.
- `gpu.getDepth()` and `gpu.setDepth()` work like text mode.
- `gpu.maxResolution()`, `gpu.getResolution()`, and `gpu.setResolution()` work like text mode, but with pixels rather than character cells.
- `gpu.copy()` works like text mode, but with pixels rather than character cells.
- `gpu.setPixel(x: number, y: number, color: number, [isPaletteIndex: boolean]): boolean`: Sets the pixel (`x`, `y`) to `color`. Returns `true` on success.
- `gpu.getPixel(x: number, y: number): number or number, number`: Returns the color of the pixel (`x`, `y`); if the color is from the palette, the second value is the palette index.
- `gpu.plotLine(xa: number, ya: number, xb: number, yb: number, color: number, [isPaletteIndex: boolean])`: Plots a line from (`xa`, `ya`) to (`xb`, `yb`) in `color`. Returns `true` on success.
- `gpu.plotTriangle(xa: number, ya: number, xb: number, yb: number, xc: number, yc: number, fill: boolean, color: number, [isPaletteIndex: boolean])`: Plots a triangle between (`xa`, `ya`), (`xb`, `yb`), and (`xc`, `yc`) in `color`, filled if `fill` is true, or left as-is otherwise. Returns `true` on success.
- `gpu.plotRect(xa: number, ya: number, xb: number, yb: number, color: number, fill: boolean, [isPaletteIndex: boolean])`: Plots a rectangle between (`xa`, `ya`) and (`xb`, `yb`) in `color`, filled if `fill` is true, or left as-is otherwise. Returns `true` on success.
- `gpu.clear(color: number, [isPaletteIndex: boolean]): boolean`: Sets all pixels to `color`. Returns `true` on success.

All graphics operations fail if the GPU is in text mode. All text operations fail if the GPU is in graphics mode (or maybe they could overwrite the graphics under them and leave it in graphics mode?). Switching modes clears the screen automatically.

All `plot` operations (and `setPixel()`) assume `color` is an RGB color by default, or a palette color if `isPaletteIndex` is `true`.

`touch`, `drag`, and `drop` signals that occur on screens in graphics mode specify pixel coordinates rather than cell coordinates.

Here is a list of possible maximum graphics resolutions:
- Tier 1: No graphics; text mode only.
- Tier 2: Max resolution 320x200, ~~16~~ 4 colors.
- Tier 3: Max resolution 640x480, ~~256~~ 16 colors.

**Comment by Techokami** [comment] 2016-06-21 23:02
Duplicate of #779

**Comment by ghost** [comment] 2016-06-21 23:14
@Techokami #779 (at least, the original issue) is for text, not full pixel graphics. I think having a separate issue for pixel/raster graphics would be good, but it's up to @fnuecke.

**Comment by skyem123** [comment] 2016-06-22 07:10
Pixels would need form of shades... Also #779 has become the area to talk about all graphics reworks. xD

**Comment by skyem123** [comment] 2016-06-22 07:11
*shaders (small programs that run on the GPU)

**Comment by ghost** [comment] 2016-06-22 17:14
Well, this is just a preliminary spec. We could add shaders, maybe:
- `gpu.addShader(code: string, name: string): number`: Takes a string of lua code (`code`) and the `name` of the shader and returns the shader's ID, which can be used in later shader operations.
- `gpu.deleteShader(id: number): boolean or boolean, string`: Deletes the shader `id` and returns `true` if successful, else `false` and an error message.
- `gpu.executeShader(id: number, ...): boolean or boolean, string`: Executes the shader `id`, passing it all other arguments (which must be strings or numbers, since the shader runs in a different Lua context), and returns `true` on success or `false` and an error message on failure (e.g. shader throws an error, error message is the error thrown; shader doesn't exist, message is "no such shader").

Shaders run in an environment with the full GPU proxy available as the global variable `gpu`, and the `math`, `table`, `string`, and maybe some other APIs (coroutine?), and the global API except `print()`, `collectgarbage()`, `loadfile()`, and `dofile()`.

**Comment by ghost** [comment] 2016-06-22 17:44
Sounds great but what's about network traffic? I think sending 640x480 screen with 256 colors will be hard for server.

**Comment by ghost** [comment] 2016-06-22 18:09
@LeshaInc Mmm. Point. Hang on... Yeah. 300 KB per frame. Bit too much. Four and sixteen colors? Mmm, still 150 KB/frame. We could add simple video compression...

**Comment by skyem123** [comment] 2016-06-22 18:16
It's worth noting that someone was already working on shadera , using the MIPS instruction set.

**Comment by ghost** [comment] 2016-06-22 18:22
@skyem123 Yeah, there should be more flexibility then 'you must use lua', but that is a preliminary.

**Comment by ghost** [comment] 2016-06-22 18:24
It should be finalized by @fnuecke or another maintainer (if such people exist).

**Comment by skyem123** [comment] 2016-06-22 18:27
The problem is that everything is in gridlock, as everyone disagrees! However, you've come the closet to actually defining something. :P

Personally, I think you should be able to mix graphics and text in layers, though different incompatible "modes" would be a good idea so we don't need to get trapped in backwards compatibility hell.

**Comment by ghost** [comment] 2016-06-22 18:28
Want to use graphics? You'll need to render text yourself.

**Comment by skyem123** [comment] 2016-06-22 18:29
Well, layering would allow fancy tricks

**Comment by ghost** [comment] 2016-06-22 18:29
Yes, but might result in backwards compatibilty hell.

**Comment by LeshaInc** [comment] 2016-06-22 18:35
@alexbuzzbee, okay... let me explain you why it's expensive for network. Just imagine, 10 computers update data every 200 ms. 300KB per frame, 300 * 10 = ~3MB. 15MB each second. :confused:

**Comment by ghost** [comment] 2016-06-22 18:46
Yes, I know why it's problematic. I'm trying to think of ways to fix it.

**Comment by ghost** [comment] 2016-06-22 18:46
Video compression is probably necessary.

**Comment by ghost** [comment] 2016-06-22 18:55
@alexbuzzbee, exactly.
For example, if we'll send all data without compression and we'll have 10 users, which update data every 200ms, server will send **15MB each second**. :open_mouth:

**Comment by skyem123** [comment] 2016-06-22 18:56
Well... It's possible to use shaders to have the drawing code run on the client

**Comment by ghost** [comment] 2016-06-22 18:58
@skyem123, and we'll need to send shaders too. What if shader is big?

**Comment by ghost** [comment] 2016-06-22 18:59
Simple video compression would be things like:
- Nothing changed this frame.
- Only this area of the screen changed this frame
- This group of pixels moved this frame
- Too much to effectively compress changed this frame (resend everything)

**Comment by ghost** [comment] 2016-06-22 19:01
@alexbuzzbee, I think we should definitely group lines/cols of pixels.

**Comment by ghost** [comment] 2016-06-22 19:03
Yeah.

**Comment by ghost** [comment] 2016-06-22 19:04
We definately need some kind of compression.

**Comment by ghost** [comment] 2016-06-22 19:04
And I think we do not need to change 256 colors into 16 colors. 1 byte, you won't get less.

---

@alexbuzzbee, something like _deflate_?

**Comment by ghost** [comment] 2016-06-22 19:10
@LeshaInc No, with 16 colors, you can pack 2 pixels per byte. And by 'compression', I mean video compression. It's a dedicated type of compression that uses the previous frames as a basis on which to diff, thus decreasing the amount of data that needs to be sent. Pretty much all video formats and video streaming services use it.

**Comment by ghost** [comment] 2016-06-22 19:14
And with 4 colors, you can pack 4 pixels in a byte. 4 values -> 2 bits -> 8 bits/byte -> 4 pixels/byte; 16 values -> 4 bits -> 8 bits/byte -> 2 pixels/byte.

**Comment by ghost** [comment] 2016-06-22 19:16
Yeah, I understand.

**Comment by ghost** [comment] 2016-06-22 19:19
Also I see another problem. Where will programs store graphics. We probally need something like VRAM.

**Comment by payonel** [comment] 2016-06-22 19:22
this "issue" is becoming far too chatty. move to forums?
also, "compression" is not the golden ticket. Don't expect 4x, and even then, it can be easily abused.

**Comment by payonel** [comment] 2017-12-04 08:05
it would take a new set of classes (screens, buffers, new gpu card) to support this. it's absolutely an interesting idea and the api defined is well thought out, but it's not in the direction we'd like to take the mod. this would be a good suggestion for an addon

**Closed as completed by payonel** 2017-12-04 08:05 UTC

**Comment by atirutw** [comment] 2022-01-31 02:25
I recently learned of a VGA text mode where you can temporarily redefine fonts, effectively turning characters into bitmap tiles. Could this be a viable option? I know it's not full-on bitmap but at least it allow more advanced graphics.
