### ISSUE TITLE
Prevent Computer/Server from "fake" tile ticks

### ISSUE THREAD

**Issue by feldim2425** [MightyPirates/OpenComputers#1968] opened 2016-07-16 11:24 UTC
Some mods like Torcherino, Roots and I think Project E can speed up the ticks of a Tile Entity. And I tested it with Torcherino and it can also speed up the ticks in a computer and might break some programms (especially programs with sleep() and uptime).
In my thest I just saw that the cursor on the screen blinks much faster than it should.

**Comment by gjgfuj** [comment] 2016-07-18 07:09
Mods shouldn't speed up ticks. Mods /rely/ on the 20tps for timing. Mods
should NOT fake ticks.

**Comment by feldim2425** [comment] 2016-07-18 11:32
I know that they SHOULD not do it but they do. I looked in the source code from Torcherino & Roots. They call the update() method multiple times per tick

**Comment by gjgfuj** [comment] 2016-07-20 07:11
Sigh... Such mods should do so with a whitelist, to not bugger up TEs that
rely on things with timing.

**Comment by feldim2425** [comment] 2016-07-20 11:04
Torcherino has at least a blacklist. 
The way I prevent TEs from fake ticks is checking if the update() method is called from the World Object by getting the Stack trace.
In theory this would also be possible with counting the time between two ticks.

EDIT: Or make your own tick handler by using the WorldTick Event

**Comment by payonel** [comment] 2018-02-01 23:05
won't fix/by design
We'll allow fake ticks to interfere/interact with the machine behavior

**Closed as completed by payonel** 2018-02-01 23:05 UTC
