### ISSUE TITLE
"not enough energy" bug

### ISSUE THREAD

**Issue by applejag** [MightyPirates/OpenComputers#45] opened 2014-01-01 18:01 UTC
Really annoying, and frustrating. You see sometimes the computer doesn't realize it got power flowing into it.

This is my setup: I quickly smash down a thermal expansion creative energy cube (unlimited redstone flux) and next to it a converter and right next to that the computer.
Now trying to start the computer it just yells "not enough energy". Somehow sometimes we get it to work but do not know how really.
The setup in picture form:
![alt text](http://i.imgur.com/qCxgVzH.png?1)

**Comment by fnuecke** [comment] 2014-01-01 18:24
What's the Analyzer output (when used on the computer)? It'd be interesting whether there's any energy in the internal network and the computer just fails to realize that, or if the converter itself fails.

I have to ask because I can't reproduce the issue.

Just to be sure, which exact version of TE and OC are you using?

**Comment by applejag** [comment] 2014-01-01 19:27
The analyzer just says 0 energy stored.
TE v3.0.0.b11a
OC v1.1.0

**Comment by fnuecke** [comment] 2014-01-01 19:30
Mmm, then it'd have to be something with the converter. Could you check again with TE 3.0.0.0 final, before I investigate this, though? Because that's what I tested it with when it worked (built that setup over 20 times with no issues).

**Comment by applejag** [comment] 2014-01-01 19:34
Ok found a temp fix: I placed an IC2 generator at the converter and gave it some fuel, at that point I could remove the generator again because it now took energy from the TE cube.

**Comment by applejag** [comment] 2014-01-01 19:39
_sigh_ or not, when it ran out of ic2 energy it shut off

**Comment by applejag** [comment] 2014-01-01 19:42
On this computer setup it works
![alt text](http://i.imgur.com/7ISUpCE.png?1)
Oh yea btw, thats a bug too, the screens fuck themselves up if you leave the area. I think its client side

**Comment by fnuecke** [comment] 2014-01-01 21:03
Just so I get this right: there are occasions when the converter _does_ accept TE energy? It's not a matter of 'it simply doesn't work', but one of 'it only works very rarely'? Have you been able to test this with TE 3 final? Because if BC/IC2 works (reliably?) it makes me wonder if it maybe isn't an issue on the TE side of things.

As for the screens... that's new. I've never seen this before. Could it be that the screen crosses a chunk border? With the one being on the right of the screenshot being the one that was unloaded/reloaded? If so I might have an idea what may have caused that.

By the way, thanks a lot for finding and reporting all these issues, I really do appreciate it!

**Comment by applejag** [comment] 2014-01-01 22:57
![alt text](http://i.imgur.com/QiQhFyJ.jpg?1)
Haha yep would you look at that, right on the edge of a chunk :P

**Comment by fnuecke** [comment] 2014-01-01 23:07
And I heroically forgot to include that in pre2... oh well. As for TE, once you confirm this still happens for you in 3.0.0.0 non-beta I'll have another look at that.

**Comment by applejag** [comment] 2014-01-01 23:10
Just noticed this setup with IC2 stopped working
![alt text](http://i.imgur.com/rJeZkab.png?1)
It got 2 capacitors, worked when I set it up but now a server restart later it doesn't. The generators have stopped because they don't have place to send their power. If I place another capacitor on top of the others the generators do nothing. If I break and place the converter the generators run for like half a second, I guess filling the converters buffer.

The computer still says "not enough energy", until I broke the capacitor and placed it back. I think the path to the computer is messed up somehow.

**Comment by applejag** [comment] 2014-01-01 23:13
By the way this is the chunk grid. Nothing is cut off except the keyboard and the repeaters (which shouldn't make any difference)
![alt text](http://i.imgur.com/nDOGKod.jpg?1)

**Comment by fnuecke** [comment] 2014-01-01 23:14
Pretty sure that is actually the same thing as #46, seems the block updates aren't properly triggered on server restart... I'll see if I can reproduce it, in the worst case I'll have to have them tile entities tick, too. Or possibly in a world load event handler explicitly for the blocks that don't have ticking tile entities (cable, keyboard, capacitor and a few more I think).

**Comment by Vexatos** [comment] 2014-01-03 16:11
ticking tileEntities==Lag, I really hope you can avoid that.

**Comment by applejag** [comment] 2014-01-05 02:34
@fnuecke I should note that this does not happen after a server reboot, once you get it going it works until you break the chain manually, it doesn't act up after a reboot.

**Comment by applejag** [comment] 2014-01-05 02:37
This works _sometimes_, often it maybe struggles a little but I noticed that trying to approach the converter from different angles can solve it... Donno whats up with that

**Comment by fnuecke** [comment] 2014-01-05 14:25
Please re-test with prerelease 3, and if you still have issues summarize them or close this issue and open a new one. It's gotten somewhat diluted with other bugs so I'm not sure anymore what the remaining issues you are having are. Thanks!

**Closed as completed** 2014-01-12 21:14 UTC

**Comment by hacker104** [comment] 2017-09-05 17:44
open computers only accepts eu power form ic2

**Comment by emilyvans** [comment] 2017-09-05 17:46
open computer only accept EU power from ic2

**Comment by xarses** [comment] 2017-09-05 18:25
If you are having problems you should create your own bug, this isn't going to be regression of this issue.
If you are having problems, please include your Minecraft, forge, and OpenComputers versions that you are having problems with. 

Finally, if this is related to 1.11, see #2468
