### ISSUE TITLE
Bug: Diamond Chip doesn't exist.

### ISSUE THREAD

**Issue by tia79** [MightyPirates/OpenComputers#2397] opened 2017-05-22 19:06 UTC
I have other mods on my server that turns diamonds into Nuggets. However i cant make chips because of this reason. Any way the recepies can we tweaked to allow nuggets instead?

The item collides with Actually Additions i found.

-

**Comment by xarses** [comment] 2017-05-22 19:19
Dupe of #1852

You can either edit the opencomputers recipes to your liking, or use something like minetweaker to resolve the conflict

**Closed as completed** 2017-05-22 20:48 UTC
