### ISSUE TITLE
[1.10.2] Crashing System

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2926] opened 2018-08-18 21:11 UTC
Hello, Ive some problems when I have a running program.
Sometimes the computer stops working.
The case's "lamps" arnt glowing, the switch is off but the screen still shows what he shows while running.
The result: All my systems are down. My stargates dont work, the DNS server is down ...
Yes: Ive enough and constant energy
Yes: The chunks are loaded (Chickenchunks Chunkloader)
No: I didnt modified the system (Adding, removing components...)
Forge: Newest 1.10.2
OC: newest 1.10.2

Thanks for help!

**Comment by payonel** [comment] 2018-09-27 23:15
> Sometimes the computer stops working.

This isn't sufficient repro. I have run computers with custom user programs, managing reactor power, for months (real life months)

If are you able to reproduce this with specifics about what causes the computer to crash, that would be helpful

**Comment by ghost** [comment] 2018-09-28 09:08
What are the triggers? :
-> When I leave (and return) a Dimension without any other players left and chunkloader (adding one solves this)
-> Sometimes after the daily server reboot
-> when moving the server (with all, including configs, saves, ...) to another server (host is mchost24.de)
How the problem loks like:
-> Sometimes I get the "too long without yielding" error
-> Sometimes the screen freezes while the computer is turned off

-> I know that the "too long without yielding" error shouldnt be caused while using event.pull()
-> I dont wait for input with io.read()
-> I dont have any sleeping routines
-> It looks like this:
`while(not shutdown)
  _, charID, _, _. = event.pull("key_down");
  ProcessKeyEvent(charID);
end`

**Comment by payonel** [comment] 2018-09-28 14:25
Keeping the chunk loaded resolves this? Then you're saying chunk unload/reload can trigger this. Okay

Server reboot? same as chunk reload
Moving the server? Same as server reboot

We also have a known limitation on heavy loaded systems (servers) that well behaved machines may throw the TLWY (too long without yielding) when a tick takes ~5 seconds or more
btw, io.read and sleep both call event.pull which calls computer.pullSignal.

at any rate, this is a duplicate of this: #2926
and if it is an incompatibility of galaticraft, could be related to this: #2735

**Closed as completed by payonel** 2018-09-28 14:25 UTC
