### ISSUE TITLE
Graphics card server crash

### ISSUE THREAD

**Issue by applejag** [MightyPirates/OpenComputers#59] opened 2014-01-05 12:37 UTC
I accidentally shift clicked 3 superior graphics cards into a computer and the server crashed.

Heres the crash log

```
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 1/5/14 12:30 PM
Description: Ticking tile entity

java.lang.NullPointerException
    at li.cil.oc.server.component.GraphicsCard.update(GraphicsCard.scala:37)
    at li.cil.oc.common.tileentity.Computer$$anonfun$updateEntity$1.apply(Computer.scala:106)
    at li.cil.oc.common.tileentity.Computer$$anonfun$updateEntity$1.apply(Computer.scala:105)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at li.cil.oc.common.tileentity.Computer.func_70316_g(Computer.scala:105)
    at net.minecraft.world.World.func_72939_s(World.java:2787)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:887)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:663)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at li.cil.oc.server.component.GraphicsCard.update(GraphicsCard.scala:37)
    at li.cil.oc.common.tileentity.Computer$$anonfun$updateEntity$1.apply(Computer.scala:106)
    at li.cil.oc.common.tileentity.Computer$$anonfun$updateEntity$1.apply(Computer.scala:105)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at li.cil.oc.common.tileentity.Computer.func_70316_g(Computer.scala:105)

-- Tile entity being ticked --
Details:
    Name: oc:case // li.cil.oc.common.tileentity.Case
    Block type: ID #3651 (tile.null // li.cil.oc.common.block.SimpleRedstoneDelegator)
    Block data value: 2 / 0x2 / 0b0010
    Block location: World: (-19,65,-130), Chunk: (at 13,4,14 in -2,-9; contains blocks -32,0,-144 to -17,255,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Actual block type: ID #3651 (tile.null // li.cil.oc.common.block.SimpleRedstoneDelegator)
    Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2787)

-- Affected level --
Details:
    Level name: plotworld
    All players: 1 total; [EntityPlayerMP['jag_e_nummer_ett'/1103064, l='plotworld', x=-18.59, y=65.00, z=-131.51](jag_e_nummer_ett at -18.5854505172982,65.0,-131.51237771499527)]
    Chunk stats: ServerChunkCache: 580 Drop: 0
    Level seed: -385662433044132455
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (3,66,3), Chunk: (at 3,4,3 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 84224022 game time, 129511304 day time
    Level dimension: 3
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 23155 (now: false), thunder time: 63992 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:887)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:663)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Linux (amd64) version 3.2.0-40-generic
    Java Version: 1.7.0_21, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 583418088 bytes (556 MB) / 2128740352 bytes (2030 MB) up to 2128740352 bytes (2030 MB)
    JVM Flags: 2 total; -Xmx2048M -Xms2048M
    AABB Pool Size: 1921 (107576 bytes; 0 MB) allocated, 701 (39256 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 6, tallocated: 62
    CraftBukkit Information: 
   Running: MCPC+ version git-MCPC-Plus-jenkins-MCPC-Plus-184 (MC: 1.6.4) (Implementing API version 1.6.4-R2.1-SNAPSHOT) true
   Plugins: { GroupManager v2.0 (2.12.1) (Phoenix) org.anjocaido.groupmanager.GroupManager [AnjoCaido, Gabriel Couto, ElgarL], WorldEdit v5.5.8-1.6.2 com.sk89q.worldedit.bukkit.WorldEditPlugin [], ChatProtectionPlus v1.0.1 net.willhastings.ChatProtectionPlus.ChatProtectionPlus [bill1993], CoreProtect v2.0.8 net.coreprotect.CoreProtect [Intelli], Anti-Potion v0.1.0 com.akajag.antipotion.main [], PlotMe v0.13b com.worldcretornica.plotme.PlotMe [ZachBora], WorldGuard v5.8 com.sk89q.worldguard.bukkit.WorldGuardPlugin [], MCBans v4.21 com.mcbans.firestar.mcbans.MCBans [Firestar, Syamn], Essentials v2.12.1 com.earth2me.essentials.Essentials [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally], EssentialsXMPP v2.12.1 com.earth2me.essentials.xmpp.EssentialsXMPP [snowleo], EssentialsProtect v2.12.1 com.earth2me.essentials.protect.EssentialsProtect [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], EssentialsSpawn v2.12.1 com.earth2me.essentials.spawn.EssentialsSpawn [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], EssentialsGeoIP v2.12.1 com.earth2me.essentials.geoip.EssentialsGeoIP [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology], EssentialsChat v2.12.1 com.earth2me.essentials.chat.EssentialsChat [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally], Multiverse-Core v2.5-b676 com.onarandombox.MultiverseCore.MultiverseCore [Rigby, fernferret, lithium3141, main--], EssentialsAntiBuild v2.12.1 com.earth2me.essentials.antibuild.EssentialsAntiBuild [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, Iaccidentally], Multiverse-Portals v2.5-b699 com.onarandombox.MultiversePortals.MultiversePortals [Rigby, fernferret], Multiverse-SignPortals v2.5-b657 com.onarandombox.MultiverseSignPortals.MultiverseSignPortals [Rigby, fernferret],}
   Warnings: DEFAULT
   Threads: ***this was super long and made me cut out cause github got a max char count on their issues ***
   Recent tasks from 992881-992911{WorldEdit:com.sk89q.worldedit.bukkit.SessionTimer@992909,}
    FML: MCP v8.11 FML v6.4.45.953 Minecraft Forge 9.11.1.953 52 mods loaded, 52 mods active
    mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.4.45.953} [Forge Mod Loader] (mine1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.11.1.953} [Minecraft Forge] (mine1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.9.0.6} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MobiusCore{1.0.4} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.6.1.7} [Not Enough Items] (NotEnoughItems 1.6.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics-Core{rv14.finale3} [AppliedEnergistics Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.5.4} [BiblioCraft] (BiblioCraft[v1.5.4].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ChickenChunks{1.3.3.3} [ChickenChunks] (ChickenChunks 1.3.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{2.0.0.b11a} [CoFH Core] (CoFHCore-2.0.0.b11a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHLoot{2.0.0.b11a} [CoFH Loot] (CoFHCore-2.0.0.b11a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHMasquerade{2.0.0.b11a} [CoFH Masquerade] (CoFHCore-2.0.0.b11a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHSocial{2.0.0.b11a} [CoFH Social] (CoFHCore-2.0.0.b11a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHWorld{2.0.0.b11a} [CoFH World] (CoFHCore-2.0.0.b11a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ComputerCraft{1.58} [ComputerCraft] (ComputerCraft1.58.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CCTurtle{1.58} [ComputerCraft Turtles] (ComputerCraft1.58.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderStorage{1.4.3.5} [EnderStorage] (EnderStorage 1.4.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transmission{1.0} [ProjRed|Transmission] (ProjectRedIntegration-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.0.0.227} [Forge Multipart] (ForgeMultipart-universal-1.6.4-1.0.0.227.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{4.2.1} [BuildCraft] (buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{3.0.0.b11a} [Thermal Expansion] (ThermalExpansion-3.0.0.b11a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{4.2.1} [BC Energy] (buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{2.0.336-experimental} [IndustrialCraft 2] (industrialcraft-2_2.0.336-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers{1.1.0} [OpenComputers] (OpenComputers-1.1.0pre2a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{4.2.1} [BC Builders] (buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{4.2.1} [BC Factory] (buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Railcraft{8.3.1.0} [Railcraft] (Railcraft_1.6.4-8.3.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics{rv14.finale3} [Applied Energistics] (appeng-rv14-finale3-mc16x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenPeripheral{0.2.1} [OpenPeripheral] (OpenPeripheral-0.2.1-snapshot-109-forge9.11.1.953.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MapWriter{2.0.1} [MapWriter] (Opis_1.1.2_alpha.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Opis{1.1.2_alpha} [Opis] (Opis_1.1.2_alpha.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Core{4.2.2.19} [ProjectRed] (ProjectRedBase-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Compatibility{1.0} [ProjRed|Compatibility] (ProjectRedCompat-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Integration{1.0} [ProjRed|Integration] (ProjectRedIntegration-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Illumination{1.0} [ProjRed|Illumination] (ProjectRedLighting-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Expansion{1.0} [ProjRed|Expansion] (ProjectRedMechanical-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transportation{1.0} [ProjRed|Transportation] (ProjectRedMechanical-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Exploration{1.0} [ProjRed|Exploration] (ProjectRedWorld-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Redstone Arsenal{1.0.0.b2} [Redstone Arsenal] (RedstoneArsenal-1.0.0.b2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    JAKJ_RedstoneInMotion{2.3.0.0} [Redstone In Motion] (RedstoneInMotion_2.3.0.0_mc1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Translocator{1.1.0.13} [Translocator] (Translocator 1.1.0.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TrussMod{beta} [Truss Mod] (TrussMod-beta-1.6.4-31.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|Core{1.4.0.6} [WR-CBE Core] (WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|Addons{1.4.0.6} [WR-CBE Addons] (WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|Logic{1.4.0.6} [WR-CBE Logic] (WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{4.2.1} [BC Transport] (buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{4.2.1} [BC Silicon] (buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ccscanner{1.0} [CCScanner] (ccscanner-1.0.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisCore{57.1.6} [Immibis Core] (immibis-core-57.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisPeripherals{57.0.0} [Immibis's Peripherals] (immibis-peripherals-57.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.0.0.227} [Minecraft Multipart Plugin] (ForgeMultipart-universal-1.6.4-1.0.0.227.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.0.0.227} [Forge Microblocks] (ForgeMultipart-universal-1.6.4-1.0.0.227.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 7 (392 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 3 / 30; [EntityPlayerMP['masterdisasterHD'/1102869, l='world', x=-1015.34, y=57.00, z=-50.62](masterdisasterHD at -1015.3449238788747,57.0,-50.617744960639484), EntityPlayerMP['jag_e_nummer_ett'/1103064, l='plotworld', x=-18.59, y=65.00, z=-131.51](jag_e_nummer_ett at -18.5854505172982,65.0,-131.51237771499527), EntityPlayerMP['grabie2'/1108915, l='world', x=-1020.30, y=50.58, z=-39.30](grabie2 at -1020.3000000119207,50.575000047683716,-39.30000001192094)]
    Is Modded: Definitely; Server brand changed to 'mcpc,craftbukkit,fml,forge'
    Type: Dedicated Server (map_server.txt)
```

**Comment by applejag** [comment] 2014-01-05 12:49
This basically caused a world corruption, either delete the world, change the ID in the configs (so the graphics card gets removed) or go into mcedit or similar editor and delete the computer or its content

**Comment by fnuecke** [comment] 2014-01-05 13:02
Duplicate of #37.

**Closed as completed by fnuecke** 2014-01-05 13:02 UTC

**Comment by applejag** [comment] 2014-01-05 13:04
The computer was off when I put them in...

**Comment by fnuecke** [comment] 2014-01-05 13:05
Do you still have the corrupt world? Can you upload it somewhere?

**Comment by applejag** [comment] 2014-01-05 13:22
I dunno, our nuthead admin changed the ID's and didn't backup... sooooo we have to like go and replace all the disk drives lost now...

**Comment by fnuecke** [comment] 2014-01-05 13:26
Well that sucks, sorry about that :/

Please see the other issue and let's continue the discussion there.
I think it may have to do with MCPC+.
