### ISSUE TITLE
[1.11 1.7.2] command oc_nanomachines in multipleplayer fails to create chat message

### ISSUE THREAD

**Issue by lena-kze** [MightyPirates/OpenComputers#2792] opened 2018-03-25 19:02 UTC
Hmm. Stumbled over that one. Commands were unuseable.

> [20:56:33] [Server thread/WARN]: Couldn't process command: 'oc_nanomachines'
> java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting
> 	at li.cil.oc.common.nanomachines.NeuralNetwork.li$cil$oc$common$nanomachines$NeuralNetwork$$colored$1(NeuralNetwork.scala:130) ~[NeuralNetwork.class:?]
> 	at li.cil.oc.common.nanomachines.NeuralNetwork$$anonfun$print$1.apply(NeuralNetwork.scala:136) ~[NeuralNetwork$$anonfun$print$1.class:?]
> 	at li.cil.oc.common.nanomachines.NeuralNetwork$$anonfun$print$1.apply(NeuralNetwork.scala:134) ~[NeuralNetwork$$anonfun$print$1.class:?]
> 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[ResizableArray$class.class:?]
> 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) ~[ArrayBuffer.class:?]
> 	at li.cil.oc.common.nanomachines.NeuralNetwork.print(NeuralNetwork.scala:134) ~[NeuralNetwork.class:?]
> 	at li.cil.oc.common.nanomachines.ControllerImpl.print(ControllerImpl.scala:337) ~[ControllerImpl.class:?]
> 	at li.cil.oc.server.command.LogNanomachinesCommand$.func_184881_a(LogNanomachinesCommand.scala:25) ~[LogNanomachinesCommand$.class:?]
> 	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [k.class:?]
> 	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [k.class:?]
> 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:904) [mi.class:?]
> 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:883) [mi.class:?]
> 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [ip.class:?]
> 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [ip.class:?]
> 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

**Comment by payonel** [comment] 2018-03-25 19:49
with any bug report you need to provide a lot more information than this, please
oc version (full)
does it repro with oc alone?
does it repro in sp?
what are the repro steps (minimal and detailed)

**Comment by lena-kze** [comment] 2018-03-26 13:47
Sorry, my excuse. I'll test things out.

**Comment by lena-kze** [comment] 2018-03-26 14:43
Version: MC1.11.2-1.7.2.97

SP: full modpack - no command response (Error 1 below)
SP: only OC - no command response (Error 2 below)

Error 1
`EDIT`

Error 2
`EDIT`

MP: full modpack - Command error in chat (can't execute command), and the error from above in the log
MP: only OC - Command error in chat (can't execute command), and the error from above in the log

**Comment by payonel** [comment] 2018-03-26 14:59
your "second command error" has pams harvest craft in the stack, so it isn't "oc only"; I don't know what  you mean by "oc only" in those cases

secondly, you haven't provided any repro steps
i dont know what blocks you are using
i dont know what commands you tried to run, i don't what you tried to run those commands in, i dont know how you tried to run the commands, i dont know what you were expecting the commands would do

if you've run this before in a previous version and it worked, that would be helpful to know as well

**Comment by payonel** [comment] 2018-03-26 15:03
edit: i do appreciate your effort to improve the bug report

**Comment by lena-kze** [comment] 2018-03-26 15:59
MC: 1.11.2
Forge: 1.11.2 - 13.20.1.2386

Ver. 1.7.1.79:
[MC1.11.2-1.7.1.79-SP_only_OC.log](https://github.com/MightyPirates/OpenComputers/files/1848531/MC1.11.2-1.7.1.79-SP_only_OC.log)
[MC1.11.2-1.7.1.79-MP_only_OC.log](https://github.com/MightyPirates/OpenComputers/files/1848533/MC1.11.2-1.7.1.79-MP_only_OC.log)

[MC1.11.2-1.7.1.79-SP_Modpack.log](https://github.com/MightyPirates/OpenComputers/files/1848535/MC1.11.2-1.7.1.79-SP_Modpack.log)
[MC1.11.2-1.7.1.79-MP_Modpack.log](https://github.com/MightyPirates/OpenComputers/files/1848537/MC1.11.2-1.7.1.79-MP_Modpack.log)


Ver. 1.7.2.97:
[MC1.11.2-1.7.2.97-SP_only_OC.log](https://github.com/MightyPirates/OpenComputers/files/1848538/MC1.11.2-1.7.2.97-SP_only_OC.log)
[MC1.11.2-1.7.2.97-MP_only_OC.log](https://github.com/MightyPirates/OpenComputers/files/1848532/MC1.11.2-1.7.2.97-MP_only_OC.log)

[MC1.11.2-1.7.2.97-SP_Modpack.log](https://github.com/MightyPirates/OpenComputers/files/1848534/MC1.11.2-1.7.2.97-SP_Modpack.log)
[MC1.11.2-1.7.2.97-MP_Modpack.log](https://github.com/MightyPirates/OpenComputers/files/1848536/MC1.11.2-1.7.2.97-MP_Modpack.log)

**Comment by payonel** [comment] 2018-03-26 16:02
yes these are all the logs
but what item in oc are you using?
what code are you running on them?
give basic repro steps, please

**Comment by lena-kze** [comment] 2018-03-26 16:02
These commands don't work:

/oc_nanomachines
/oc_debugNanomachines

I didn't tested others so far... But maybe the error gets fixed on them too.
I only try to use these commands.

**Comment by lena-kze** [comment] 2018-03-26 16:18
If you need the mod-list tell me.

**Comment by payonel** [comment] 2018-03-26 16:38
This bug report does not tell me what you are doing. Let me try to explain how confusing your bug report is:

1.
MC1.11.2-1.7.1.79-SP_only_OC.log
In the first log are you spamming the /oc commands multiple times? I don't know, I'm guessing, you didn't explain this in the bug report, I'm just seeing CHAT messages in your logs. Is spamming the commands needed repro the bug? I don't know, you didn't explain this. Does it happen when you spam the command a certain number of times? Does the crash happen consistently? you are not explaining basic bug reports things such as how often this repro's nor what steps you are taking to try to repro

And it appears in that first log that your game does not crash.

```
[17:09:36] [Client thread/INFO]: [CHAT] �7/oc_setclipboard�r, /oc_debugNanomachines, /oc_debugWhitelist, /oc_dn, /oc_nanomachines, /oc_nm, /oc_nodis, /oc_prevdis, /oc_preventDisassembling, /oc_renderWirelessNetwork, /oc_sc, /oc_sdbg, /oc_sendDebugMessage, /oc_spawnComputer, /oc_wlan
[17:09:36] [Client thread/INFO]: [CHAT] �7/oc_setclipboard�r, /oc_debugNanomachines, /oc_debugWhitelist, /oc_dn, /oc_nanomachines, /oc_nm, /oc_nodis, /oc_prevdis, /oc_preventDisassembling, /oc_renderWirelessNetwork, /oc_sc, /oc_sdbg, /oc_sendDebugMessage, /oc_spawnComputer, /oc_wlan
[17:09:37] [Client thread/INFO]: [CHAT] �7/oc_setclipboard�r, /oc_debugNanomachines, /oc_debugWhitelist, /oc_dn, /oc_nanomachines, /oc_nm, /oc_nodis, /oc_prevdis, /oc_preventDisassembling, /oc_renderWirelessNetwork, /oc_sc, /oc_sdbg, /oc_sendDebugMessage, /oc_spawnComputer, /oc_wlan
[17:09:37] [Client thread/INFO]: [CHAT] �7/oc_setclipboard�r, /oc_debugNanomachines, /oc_debugWhitelist, /oc_dn, /oc_nanomachines, /oc_nm, /oc_nodis, /oc_prevdis, /oc_preventDisassembling, /oc_renderWirelessNetwork, /oc_sc, /oc_sdbg, /oc_sendDebugMessage, /oc_spawnComputer, /oc_wlan
[17:09:38] [Client thread/INFO]: [CHAT] �7/oc_setclipboard�r, /oc_debugNanomachines, /oc_debugWhitelist, /oc_dn, /oc_nanomachines, /oc_nm, /oc_nodis, /oc_prevdis, /oc_preventDisassembling, /oc_renderWirelessNetwork, /oc_sc, /oc_sdbg, /oc_sendDebugMessage, /oc_spawnComputer, /oc_wlan
```

2.
MC1.11.2-1.7.1.79-MP_only_OC.log
In the next log i see a crash, and again it looks like you spam the commands perhaps 5 times before it crashes? I'm not sure because your CHAT messages also include using commas "," such as
`[17:19:01] [Client thread/INFO]: [CHAT] /oc_debugNanomachines, /oc_debugWhitelist`
And that doesn't even run a command, but instead you would see an error in the chat and no crash

Also, if this is the crash, and it happens on 1.7.1, you never mentioned that in the bug report. So this is not a new issue? When was the last time this worked for you?


3.
MC1.11.2-1.7.1.79-SP_Modpack.log
again i see multiple attempts in your chat log to run commands, but no crash

4. 
MC1.11.2-1.7.1.79-MP_Modpack.log
no crash, 5 chat lines of spamming the commands

5.
MC1.11.2-1.7.2.97-SP_only_OC.log
no crash in log

6.
MC1.11.2-1.7.2.97-MP_only_OC.log
no crash in log

7.
MC1.11.2-1.7.2.97-SP_Modpack.log
no crash in log

8.
MC1.11.2-1.7.2.97-MP_Modpack.log
no crash in log



So from your logs I would guess (i don't know, you never explained it) that it only crashes with
MC1.11.2-1.7.1.79-MP_only_OC.log
And never with 1.7.2? So, solution is use 1.7.2?

**Comment by lena-kze** [comment] 2018-03-26 17:25
I used Tab for the Commands, that's not spamming, it's autocomplete.

Every time i started the game, and ran /oc_nanomachines and then /oc_debugNanomachines.
Then I closed the game, to get the log.

**Comment by lena-kze** [comment] 2018-03-26 17:28
No it seems MP is the problem. 1.7.2 doesn't fix it.

**Comment by lena-kze** [comment] 2018-03-26 17:40
I looked into the logs and what I see is that MP ist the problem.

Fine (SP!):
MC1.11.2-1.7.2.97-SP_only_OC
MC1.11.2-1.7.2.97-SP_Modpack
MC1.11.2-1.7.1.79-SP_only_OC
MC1.11.2-1.7.1.79-SP_Modpack

Error:
MC1.11.2-1.7.2.97-MP_only_OC
MC1.11.2-1.7.2.97-MP_Modpack
MC1.11.2-1.7.1.79-MP_only_OC
MC1.11.2-1.7.1.79-MP_Modpack

Chat-Message (German):

> Bei der Ausführung dieses Befehls trat ein unbekannter Fehler auf

**Comment by lena-kze** [comment] 2018-03-26 17:54
OC only means OpenComputers only. No other mods.

**Comment by payonel** [comment] 2018-03-26 20:14
there is no crash information in the 1.7.2 log files

**Comment by payonel** [comment] 2018-03-26 20:21
let me give you an example bug report
```
1. oc version 1.11.2-1.7.2.97
2. start server, forge version 1.11.2-13.20.1.2588
3. start client
4. join server world
5. from client, run chat command /oc_nanomachines -- it works and i have nano machines installed on my person
6. from the client i run chat command /oc_debugNanomachines

expected result:
i see nano machine information

actual result:
the game crashes
```
can you give this type of information? what is happening and what do you expect to happen
your client logs do not give this information
if this happens only in mp, then the server logs would also be good to include

**Comment by payonel** [comment] 2018-03-26 20:26
I am also testing this with 1.7.2 on 1.11, and all the commands work without crashes and they work as expected

**Comment by lena-kze** [comment] 2018-03-26 20:30
SP:
1. I join world
2. I run command /oc_Nanomachines
3. It works. Prints Inputs to the chat as expected.

MP:
1. I join world (server)
2. I run command /oc_Nanomachines
3. A error message occures.
"Bei der Ausführung dieses Befehls trat ein unbekannter Fehler auf"

-> Version of OpenComputers isn't the problem
-> Modpack does no harm, maybe some other error from other mods
-> MP is the problem, because it only occures when I join the ForgeServer

**Comment by payonel** [comment] 2018-03-26 20:33
from the original post in this bug report i see
`java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting
at `

but that crash also seems to include `net.minecraft.server.MinecraftServer`
Is that a message  you see on the server?
do you have a client-side-only mod in your mod pack on the server?

where did you get that crash report from? client or server?

**Comment by Timsuper** [comment] 2018-03-26 20:35
All

**Comment by lena-kze** [comment] 2018-03-26 20:36
Hmm ofc. You need the server log! Sooory:


[19:41:34] [Server thread/INFO]: Timsuper2 joined the game
[19:41:47] [Server thread/WARN]: Couldn't process command: 'oc_nanomachines'
java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting
	at li.cil.oc.common.nanomachines.NeuralNetwork.li$cil$oc$common$nanomachines$NeuralNetwork$$colored$1(NeuralNetwork.scala:130) ~[NeuralNetwork.class:?]
	at li.cil.oc.common.nanomachines.NeuralNetwork$$anonfun$print$1.apply(NeuralNetwork.scala:136) ~[NeuralNetwork$$anonfun$print$1.class:?]
	at li.cil.oc.common.nanomachines.NeuralNetwork$$anonfun$print$1.apply(NeuralNetwork.scala:134) ~[NeuralNetwork$$anonfun$print$1.class:?]
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[ResizableArray$class.class:?]
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) ~[ArrayBuffer.class:?]
	at li.cil.oc.common.nanomachines.NeuralNetwork.print(NeuralNetwork.scala:134) ~[NeuralNetwork.class:?]
	at li.cil.oc.common.nanomachines.ControllerImpl.print(ControllerImpl.scala:337) ~[ControllerImpl.class:?]
	at li.cil.oc.server.command.LogNanomachinesCommand$.func_184881_a(LogNanomachinesCommand.scala:25) ~[LogNanomachinesCommand$.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [k.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [k.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:904) [mi.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:883) [mi.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [ip.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [ip.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.ClassNotFoundException: com.mojang.realmsclient.gui.ChatFormatting
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
	... 23 more
Caused by: java.lang.NullPointerException
[19:41:49] [Server thread/INFO]: Timsuper2 lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[19:41:49] [Server thread/INFO]: Timsuper2 left the game

**Comment by lena-kze** [comment] 2018-03-26 20:44
Hmm.

> but that crash also seems to include net.minecraft.server.MinecraftServer
> Is that a message you see on the server?

No. There is no other message than the one in german. The server also doesn't crash. It just don't run it.

I ran the server without any other mods. So only OC was in the /mods/1.11.2/ folder. No OptiFine, no nothing.

**Comment by payonel** [comment] 2018-03-26 20:44
ok thank you. i've been able to reproduce the issue

**Comment by payonel** [comment] 2018-03-26 20:48
note that with this bug, you are still getting the nanomachine

**Comment by lena-kze** [comment] 2018-03-26 20:57
jup

**Comment by Vexatos** [comment] 2018-09-10 15:58
Closed via https://github.com/MightyPirates/OpenComputers/commit/225e907c49af61c8c3357ebd1ca8a43ea96127d4.

**Closed as completed by Vexatos** 2018-09-10 15:58 UTC
