### ISSUE TITLE
Relay exception 'li.cil.oc.common.tileentity.traits.Hub$Plug' threw an error while being connected to the component network.

### ISSUE THREAD

**Issue by sigmasoldi3r** [MightyPirates/OpenComputers#3156] opened 2019-09-12 15:03 UTC
Using Minecraft 1.12.2 along with:
```
OpenComputers 1.7.4.153
forge 14.23.5.2846
spongeforge 2825-7.1.6
```

Additional mods: (Might not be related)
```
astralsorcery  1.10.20
Baubles 1.12 1.5.2
BiblioCraft[v2.4.5][MC]
BiomesOPlenty  7.0.1.2439 universal
Bountiful 2.2.0
forestry  5.8.1.322
Forgelin 1.8.3
Mekanism  9.8.1.383
MekanismGenerators  9.8.1.383
Pam's HarvestCraft 1.12.2ze
Patchouli 1.0-20
twilightforest  3.9.984 universal
worldedit forge mc 6.1.10 SNAPSHOT dist
Xaeros Minimap 1.17.9
XaerosWorldMap 1.4.9
```
## What happens
The console starts spamming very long traces. Only stops if you break the cable that started the spam. Also the server starts becoming slow.
If you wait long enough, the server crashes.

### Steps to reproduce
Placing many (About 16) Relays and connecting them together seems to start producing this at random, in fact that might happen before connecting all.
All 16 had (Each one) one computer connected. Also there is a 17th relay connected that is powered with a creative power source of Mekanism. (Maybe unrelated?)

* * *
### Trace
```
[16:46:55] [Server thread/WARN] [opencomputers]: A component of type 'li.cil.oc.common.tileentity.traits.Hub$Plug' threw an error while being connected to the component network.
java.lang.StackOverflowError: null
        at scala.collection.mutable.HashTable$class.$init$(HashTable.scala:41) ~[scala-library-2.11.1.jar:?]
        at scala.collection.mutable.HashMap.<init>(HashMap.scala:41) ~[scala-library-2.11.1.jar:?]
        at scala.collection.mutable.HashMap.<init>(HashMap.scala:56) ~[scala-library-2.11.1.jar:?]
        at scala.collection.mutable.HashMap$.empty(HashMap.scala:154) ~[scala-library-2.11.1.jar:?]
        at scala.collection.mutable.HashMap.empty(HashMap.scala:52) ~[scala-library-2.11.1.jar:?]
        at scala.collection.mutable.HashMap.empty(HashMap.scala:40) ~[scala-library-2.11.1.jar:?]
        at scala.collection.mutable.MapLike$class.newBuilder(MapLike.scala:59) ~[scala-library-2.11.1.jar:?]
        at scala.collection.mutable.AbstractMap.newBuilder(Map.scala:80) ~[scala-library-2.11.1.jar:?]
        at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:257) ~[scala-library-
...
  (Trace log collapsed)
...
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[scala-library-2.11.1.jar:?]
        at li.cil.oc.server.network.Network$$anonfun$10.apply(Network.scala:290) ~[Network$$anonfun$10.class:?]
        at li.cil.oc.server.network.Network$$anonfun$10.apply(Network.scala:274) ~[Network$$anonfun$10.class:?]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[scala-library-2.11.1.jar:?]
```
Full stacktrace (+1000 lines): https://pastebin.com/mkXQPdT9

**Comment by payonel** [comment] 2019-11-15 04:52
definitely unable to reproduce this. note that this code path should only happen when addresses of nodes are duplicated (such as via world edit) or a mod that is editing the nbt data of our nodes. but, even in that case we should *not* get this stackoverflow. 

I'm going to close this as no repro BUT if you get a repro, something I can load and repro for testing, that would be quite helpful. I have some ideas that might help but I need a repro to test it. Please comment on this ticket with a world zip of a repro if you have one and I can re-open the ticket.

**Closed as completed by payonel** 2019-11-15 04:52 UTC

**Comment by sigmasoldi3r** [comment] 2019-11-15 14:53
Might be related to world edit copy and paste then?

**Comment by payonel** [comment] 2019-11-15 16:03
were you using word edit copy+paste?

**Comment by sigmasoldi3r** [comment] 2019-11-17 12:00
Stack operation which more or less is the same
