### ISSUE TITLE
Stuck on 1.12

### ISSUE THREAD

**Issue by Velcro3** [MightyPirates/OpenComputers#3541] opened 2022-07-28 10:30 UTC
Please update to 1.19

**Comment by th3impasta** [comment] 2022-07-28 22:32
i dont even work on this program, but i have 4 words for you: read the curseforge page

**Comment by PublicVoidUpdate** [comment] 2022-08-21 15:34
it's a lot more difficult than just "Oh I want to go 1.19 now 😜 

you have to use different libraries and even different versions of Java, i.e. Minecraft 1.12.2 required Java 8, Minecraft 1.19 required at least Java 13 as far as I am aware.

overall it is a lot of work especially when working on bugs in existing versions of Open computers. It would be easier to add arm7 support than 1.19

**Comment by th3impasta** [comment] 2022-08-23 03:53
arm 7 support would be cooler than newer versions ngl

**Comment by PublicVoidUpdate** [comment] 2022-08-23 05:09
dude if that happens I would freaking...  idfk but I would be soooo happy

**Comment by th3impasta** [comment] 2022-08-25 22:41
plus open computers 2 is a thing. it's most likely gonna go 1.18.2 and beyond

**Comment by th3impasta** [comment] 2022-08-25 22:42
1.18.2 and 1.16 are the most modern versions i use, and i wont go to any more modern versions

**Comment by asiekierka** [comment] 2022-08-27 08:40
The current "development" "team" for OC1 consists of two retired modders (myself and payonel) who occasionally take a peek at this repository to see if there are any new critical issues.

We do not have the time to devote to update this mod to any version past 1.12.2. If someone else steps up to do it, sure, but I personally think efforts would be better invested in getting an OC1-like environment running on top of OC2.

**Comment by asiekierka** [comment] 2022-08-28 08:27
Duplicate of https://github.com/MightyPirates/OpenComputers/issues/3450

**Closed as completed by asiekierka** 2022-08-28 08:27 UTC
