### ISSUE TITLE
Microcontrollers crashing after last player leave the server.

### ISSUE THREAD

**Issue by funmaker** [MightyPirates/OpenComputers#1932] opened 2016-07-03 12:40 UTC
MC: 1.7.10
OC: OpenComputers@1.5.22.46
FTB: 1.4.12
Modpack: Space Astronomy

Few minutes after last player leaves the server some of microcontrollers crashes with message "no such component". It used to be one particular microcontroller but now more of them do it as well.

Console:

```
[04:24:32] [Server thread/INFO]: funmaker left the game
[04:24:34] [Server thread/WARN] [OpenComputers]: A component of type 'eeprom' disappeared (5c10e7c9-2642-4699-b195-8f0cb385fab3)! This usually means that it didn't 
save its node.
[04:24:34] [Server thread/WARN] [OpenComputers]: A component of type 'modem' disappeared (87632f8b-1913-43a0-b8ea-a5daa9ad4ca3)! This usually means that it didn't s
ave its node.
[04:24:34] [Server thread/WARN] [OpenComputers]: A component of type 'modem' disappeared (69b02875-976c-4358-8561-0acd909f79ae)! This usually means that it didn't s
ave its node.
[04:24:34] [Server thread/WARN] [OpenComputers]: A component of type 'eeprom' disappeared (4b4ccd38-a994-486c-a97b-0b24ceb5c963)! This usually means that it didn't 
save its node.
[04:24:34] [Server thread/WARN] [OpenComputers]: A component of type 'eeprom' disappeared (dd08ffdc-ee27-4b7c-9e76-4e9a4f02c72b)! This usually means that it didn't 
save its node.
[04:24:34] [Server thread/WARN] [OpenComputers]: A component of type 'modem' disappeared (16e604a2-2962-484a-8364-ff72ce5217bf)! This usually means that it didn't s
ave its node.
[04:24:34] [Server thread/WARN] [OpenComputers]: A component of type 'eeprom' disappeared (75d610b5-4e8f-47f6-a2c6-2690f24444ed)! This usually means that it didn't 
save its node.
[04:24:34] [Server thread/WARN] [OpenComputers]: A component of type 'modem' disappeared (61a26f48-c8ee-4649-9724-225d31066014)! This usually means that it didn't s
ave its node.
```

All my microcontroller run the same script which loads on boot one script via network. They all only have wireless/wired network card and eeprom.

**Comment by payonel** [comment] 2018-03-12 02:41
scheduling for 1.7.3
if no repro, i'll close

**Comment by payonel** [comment] 2018-03-21 18:08
@funmaker this ticket is next up on my list
I know this ticket is nearly 2 years old :) but, from what you remember....or are you still seeing this issue?

I can see from the log that it happens 2 seconds after you leave, which is odd because the chunk would normally be saving and closing. Were you using chunk loaders? Did this happen only on a specific dimension? Can you repro this? Do you still have the map?

**Comment by payonel** [comment] 2018-03-22 03:33
I tried to simulate this, using cables that are known to request block info on adjacent blocks that could be in a chunk that is unloading, made a very long line of microcontrollers, flew out of range to unload the chunks, teleported out of range to unload the chunks, left the server ... the microcontrollers never crashed

do note that we've made save/load fixes related to this types of issues over the last two years, so it is possible we have fixed this (as opposed to just my failure to reproduce it)

if this issue is seen again, please open a new ticket with version details and minimal repro steps (such as testing with 1 or 2 mods, in a server flatworld)

**Closed as completed by payonel** 2018-03-22 03:33 UTC
