### ISSUE TITLE
Still no support for power mods? (1.11.2)

### ISSUE THREAD

**Issue by davv1** [MightyPirates/OpenComputers#2468] opened 2017-07-21 09:52 UTC
![obraz](https://user-images.githubusercontent.com/13569795/28458620-b59c7c98-6e0a-11e7-8787-ab626c640a37.png)

Minecraft: 1.11.2

Using:
Buildcraft (7.99.5)
Industrialcraft2 (2.7.76-ex111)
OpenComputers (MC1.11.2-1.7.0.35)

Logs:
[logs.zip](https://github.com/MightyPirates/OpenComputers/files/1165106/logs.zip)

Savefile:
[Testowo01.zip](https://github.com/MightyPirates/OpenComputers/files/1165108/Testowo01.zip)

**Comment by pPkMnh4to8994h** [comment] 2017-07-22 05:20
same. even with power converter, i can't attach energy pipes or cables.

**Comment by davv1** [comment] 2017-07-23 18:31
Okay. I have some more info. For unknown reason, Forestry engine connects to OC case and powers it.

![obraz](https://user-images.githubusercontent.com/13569795/28501884-c1a0bd38-6fe5-11e7-833c-03cf0d7b0a19.png)

But still IC2 and BC can't connect...

![obraz](https://user-images.githubusercontent.com/13569795/28501886-cdb42074-6fe5-11e7-8e1e-b52a8abc6242.png)

But for BC is reason because of their Energy API is still not upgraded to newest version and they're working on it.

Also, I upgraded my mods to newest versions:

buildcraft-7.99.6
forestry_1.11.2-5.3.4.138
industrialcraft-2-2.7.79-ex111
OpenComputers-MC1.11.2-1.7.0.39

One more thing: bug about class transformer disappeared.

**Comment by davv1** [comment] 2017-07-23 18:32
One more thing: bug about class transformer disappeared.

**Comment by Cysioland** [comment] 2017-09-08 11:04
Same on 1.7.0.40

**Comment by BlasterIN** [comment] 2017-10-04 16:12
I got a huge proble in connect IC 2 cables or Buildcraft engines with power converters or directly with my computer...

See this....

![2017-10-04_21 32 24](https://user-images.githubusercontent.com/32519907/31186345-025e7820-a94c-11e7-9c26-f547a3ca44a9.png)

Please fix this bug ,As Soon as possible because it ruining the desire for playing OpenComputer 1.11.2 version....

I playing OC version 1.7.0.40

But I also created same problem in OC version 1.7.0.6

Please help or people stop using OpenComputer.....:(

**Comment by asiekierka** [comment] 2017-10-04 17:59
I suppose OpenComputers for 1.11.2 supports Forge Energy, but not MJ or EU.

**Comment by Cysioland** [comment] 2017-10-04 18:00
The problem is, that a power converter is supposed to convert power to a format better suited for OpenComputers, yet it doesn't.

**Comment by asiekierka** [comment] 2017-10-04 18:02
Yes, but many power APIs were dropped in Minecraft 1.7.

**Comment by Vexatos** [comment] 2017-10-04 18:09
IC2 EU support is back on Minecraft 1.12 (https://github.com/MightyPirates/OpenComputers/commit/151ddecb2c305d6827c183d384690761272d5e16).

**Comment by Vexatos** [comment] 2017-10-04 18:13
...and 1.11 now (https://github.com/MightyPirates/OpenComputers/commit/795762df858a6288e8b9e176baa4c81b70d93efb). Together with Forge Energy, that should do for now, no? Try the latest build.

**Comment by asiekierka** [comment] 2017-10-04 18:59
Assuming BuildCraft is dead, yes.

**Comment by Cysioland** [comment] 2017-10-04 19:00
Ain't that your fault, @asiekierka?

**Comment by payonel** [comment] 2017-10-04 19:00
@Cysioland please try http://ci.cil.li/job/OpenComputers-dev-MC1.11/50/artifact/build/libs/OpenComputers-MC1.11.2-1.7.0.50.jar

**Comment by Cysioland** [comment] 2017-10-04 19:08
@payonel IC2 works, BC doesn't

**Comment by Vexatos** [comment] 2017-10-04 19:13
Adding support for BuildCraft isn't very easy; noone really knows how much one MJ is supposed to be worth, I'd have to do some testing first.

**Comment by payonel** [comment] 2017-10-04 19:52
we may or may not support BC, but closing this ticket for IC2 sake

**Closed as completed by payonel** 2017-10-04 19:52 UTC

**Comment by asiekierka** [comment] 2017-10-04 20:03
@Vexatos Officially speaking, I believe pre-RF-conversion rates remain in effect.
