### ISSUE TITLE
Charger drains all neighbors in network before pulling energy from others

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1823] opened 2016-05-27 18:34 UTC
I have the below networks set up

```
                                                                        +-------+-------+
     +-----------------------------------------------------------+------+Power  |       |
     |                                                           |      |Adapter| GT5   |
+----+----+                                                      |      |       | Buffer|
|         |                                                      |      +-------+-------+
| Power   +----+----------+----------+----------+                |
| Dist    |    |          |          |          |            +---+-----+
+---------+    |      +---+---+  +---+---+  +---+---+        | T2 CPU  |
               |      |       |  |       |  |       |        |upstream |
 +------+      |      | T2 CPU|  | Assem |  | DisAss|        |         |
 |Capaci|      |      |       |  |       |  | embler|        +---------+
 |tor   +------+      +-------+  +-------+  +-------+        | Screen  |
 |      |      |                                             |         |
 +------+      |                                             +---------+
               |
               |
               |
               |
               |     +-----+  +------+
               |     |Scre |  |Motion|
               |     |en   |  |Sensor|
 +------+      |     +--+--+  +--+---+
 |      |      |        |        |
 | Charg+------+--------+--------+
 | er   |
 |      |
 +------+
```

in the Network North of the distributor I have a single computer as well as the power adapter being provided a lot of GT5 LV power

in the network south of the distributor I have a charger, and when given a high charge load (two robots) It removes all of the power buffer from every device in the network (capacitor, case, assembler, disassembler) before it takes power from the distributor. After turning on the charger this can occur in about 2 seconds, about 5-10 seconds later, all of the equipment starts to get charge again. This leads me to beleave that we are finally getting power from the distributor and live can go on.

The computer on the north bound network does loose some power, but not much and never turns off.

The worst part of this is that this cause the case to loose all of its buffer and turn off (#1824)

**Comment by fnuecke** [comment] 2016-05-28 13:32
There is no "reserved energy" in OC, any machine has the same "rights" to power in a subnet as any other. So this is pretty much working as expected. Throw another distributor in there to avoid this / redesign your network.

Also keep in mind that a distributor will try to level the energy in the networks it is connected to in such a way that each connected network gets the same _relative_ amount of energy. So according use of capacitors can help, too.

Unless there's something else to this I'm not seeing, I'll be closing this as not a bug.

**Comment by xarses** [comment] 2016-05-31 06:07
to update, one robot charging on the network (as apposed to two) will still cause all of the all of the energy to leave the network, including the case (it reads 0/500) but the case will stay on

**Comment by xarses** [comment] 2016-06-20 20:49
Adding another power distributor into the network does prevent the network from turning off the computer, even though it does still read `0/500` power. In this configuration I can also charge 3 robots at the same time.

I'm not sure what to say here there clearly isn't enough power in the network to charge that many robots at once since they charge at a substantially higher rate then other devices, but at the same time, I'd expect that the case shouldn't shut off at the same time.

I think this comes down to a docs issue, better documentation of the power network and how much the produces can provide and consumption of some of the out-layers  would be helpful here.

**Comment by payonel** [comment] 2018-03-12 01:43
will add info in docs

**Closed as completed by payonel** 2018-03-12 01:43 UTC
