### ISSUE TITLE
1.7.2 Screen orientation

### ISSUE THREAD

**Issue by Snakybo** [MightyPirates/OpenComputers#150] opened 2014-03-08 01:00 UTC
The left and right side of a screen seem to have the wrong orientation.

Not using any other mods, Minecraft video settings on max, forge 1024

![2014-03-08_01 58 49](https://f.cloud.github.com/assets/3172140/2363997/cfa584f0-a65c-11e3-8fc1-1aa845d1afa7.png)
![2014-03-08_01 56 25](https://f.cloud.github.com/assets/3172140/2363998/cfa68df0-a65c-11e3-976f-f4df8933d232.png)

**Comment by fnuecke** [comment] 2014-03-08 12:40
Duplicate of #114 (which I intentionally left open, oh well :P).

**Closed as completed by fnuecke** 2014-03-08 12:40 UTC
