### ISSUE TITLE
TileEntity description packet

### ISSUE THREAD

**Issue by payonel** [MightyPirates/OpenComputers#538] opened 2014-09-04 18:19 UTC
OpenComputers-MC1.7.10-1.3.3.54-universal.jar

We see in the server log:

```
[19:04:24] [Server thread/WARN] [OpenComputers]: There was a problem writing a TileEntity description packet. Please report this if you see it!
java.lang.NullPointerException
        at li.cil.oc.server.network.Node$class.connect(Node.scala:35) ~[Node$class.class:?]
        at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.connect(Network.scala:549) ~[Network$ComponentConnectorBuilder$$anon$1.class:?]
        at li.cil.oc.common.inventory.ComponentInventory$class.connectItemNode(ComponentInventory.scala:141) ~[ComponentInventory$class.class:?]
        at li.cil.oc.common.tileentity.Case.connectItemNode(Case.scala:16) ~[Case.class:?]
        at li.cil.oc.common.inventory.ComponentInventory$$anonfun$connectComponents$3.applyOrElse(ComponentInventory.scala:60) ~[ComponentInventory$$anonfun$connectComponents$3.class:?]
        at li.cil.oc.common.inventory.ComponentInventory$$anonfun$connectComponents$3.applyOrElse(ComponentInventory.scala:59) ~[ComponentInventory$$anonfun$connectComponents$3.class:?]
        at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:136) ~[PartialFunction$$anonfun$runWith$1.class:?]
        at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:135) ~[PartialFunction$$anonfun$runWith$1.class:?]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[IndexedSeqOptimized$class.class:?]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[ArrayOps$ofRef.class:?]
        at scala.collection.TraversableLike$class.collect(TraversableLike.scala:282) ~[TraversableLike$class.class:?]
        at scala.collection.mutable.ArrayOps$ofRef.collect(ArrayOps.scala:186) ~[ArrayOps$ofRef.class:?]
        at li.cil.oc.common.inventory.ComponentInventory$class.connectComponents(ComponentInventory.scala:59) ~[ComponentInventory$class.class:?]
        at li.cil.oc.common.tileentity.Case.connectComponents(Case.scala:16) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.ComponentInventory$class.writeToNBTForClient(ComponentInventory.scala:28) ~[ComponentInventory$class.class:?]
        at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$Rotatable$$super$writeToNBTForClient(Case.scala:16) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.Rotatable$class.writeToNBTForClient(Rotatable.scala:195) ~[Rotatable$class.class:?]
        at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$RedstoneAware$$super$writeToNBTForClient(Case.scala:16) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.RedstoneAware$class.writeToNBTForClient(RedstoneAware.scala:107) ~[RedstoneAware$class.class:?]
        at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$AbstractBusAware$$super$writeToNBTForClient(Case.scala:16) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.AbstractBusAware$class.writeToNBTForClient(AbstractBusAware.scala:72) ~[AbstractBusAware$class.class:?]
        at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$Computer$$super$writeToNBTForClient(Case.scala:16) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.Computer$class.writeToNBTForClient(Computer.scala:165) ~[Computer$class.class:?]
        at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$Colored$$super$writeToNBTForClient(Case.scala:16) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.Colored$class.writeToNBTForClient(Colored.scala:43) ~[Colored$class.class:?]
        at li.cil.oc.common.tileentity.Case.writeToNBTForClient(Case.scala:16) ~[Case.class:?]
        at li.cil.oc.common.tileentity.traits.TileEntity$class.getDescriptionPacket(TileEntity.scala:70) [TileEntity$class.class:?]
        at li.cil.oc.common.tileentity.Case.func_145844_m(Case.scala:16) [Case.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:540) [mw.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:276) [mw.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2019) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) [mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1983) [ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1836) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[19:04:24] [Server thread/WARN] [OpenComputers]: There was a problem writing a TileEntity description packet. Please report this if you see it!
java.lang.NullPointerException
        at li.cil.oc.server.network.Node$class.connect(Node.scala:35) ~[Node$class.class:?]
        at li.cil.oc.server.network.Network$NodeBuilder$$anon$4.connect(Network.scala:514) ~[Network$NodeBuilder$$anon$4.class:?]
        at li.cil.oc.common.inventory.ComponentInventory$class.connectItemNode(ComponentInventory.scala:141) ~[ComponentInventory$class.class:?]
        at li.cil.oc.common.tileentity.DiskDrive.connectItemNode(DiskDrive.scala:14) ~[DiskDrive.class:?]
        at li.cil.oc.common.inventory.ComponentInventory$$anonfun$connectComponents$3.applyOrElse(ComponentInventory.scala:60) ~[ComponentInventory$$anonfun$connectComponents$3.class:?]
        at li.cil.oc.common.inventory.ComponentInventory$$anonfun$connectComponents$3.applyOrElse(ComponentInventory.scala:59) ~[ComponentInventory$$anonfun$connectComponents$3.class:?]
        at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:136) ~[PartialFunction$$anonfun$runWith$1.class:?]
        at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:135) ~[PartialFunction$$anonfun$runWith$1.class:?]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[IndexedSeqOptimized$class.class:?]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[ArrayOps$ofRef.class:?]
        at scala.collection.TraversableLike$class.collect(TraversableLike.scala:282) ~[TraversableLike$class.class:?]
        at scala.collection.mutable.ArrayOps$ofRef.collect(ArrayOps.scala:186) ~[ArrayOps$ofRef.class:?]
        at li.cil.oc.common.inventory.ComponentInventory$class.connectComponents(ComponentInventory.scala:59) ~[ComponentInventory$class.class:?]
        at li.cil.oc.common.tileentity.DiskDrive.connectComponents(DiskDrive.scala:14) ~[DiskDrive.class:?]
        at li.cil.oc.common.tileentity.traits.ComponentInventory$class.writeToNBTForClient(ComponentInventory.scala:28) ~[ComponentInventory$class.class:?]
        at li.cil.oc.common.tileentity.DiskDrive.li$cil$oc$common$tileentity$traits$Rotatable$$super$writeToNBTForClient(DiskDrive.scala:14) ~[DiskDrive.class:?]
        at li.cil.oc.common.tileentity.traits.Rotatable$class.writeToNBTForClient(Rotatable.scala:195) ~[Rotatable$class.class:?]
        at li.cil.oc.common.tileentity.DiskDrive.writeToNBTForClient(DiskDrive.scala:70) ~[DiskDrive.class:?]
        at li.cil.oc.common.tileentity.traits.TileEntity$class.getDescriptionPacket(TileEntity.scala:70) [TileEntity$class.class:?]
        at li.cil.oc.common.tileentity.DiskDrive.func_145844_m(DiskDrive.scala:14) [DiskDrive.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:540) [mw.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:276) [mw.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2019) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) [mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1983) [ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1836) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by Wuerfel21** [comment] 2014-09-04 19:27
Seems to be caused by some disk drive

**Comment by fnuecke** [comment] 2014-09-04 20:35
Thanks. I'm _pretty_ sure this is fixed in the latest dev builds. Feel free to give those a try (they should be pretty stable now), or wait for 1.3.4. If you see this again, then, please let me know and I'll re-open the issue!

**Closed as completed by fnuecke** 2014-09-04 20:35 UTC
