### ISSUE TITLE
[Suggestion] Remote Control

### ISSUE THREAD

**Issue by TinkerWorX** [MightyPirates/OpenComputers#872] opened 2015-01-30 12:37 UTC
# Suggestion

Here's a suggestion for a remote control system. This would serve as a system to remote control robots and drones. This could possibly be handled by the Tablet, but the point of the Remote Control is to use less power than the tablet and possibly have a slightly better range while providing a much more limited, and only one-way, subset of wireless configuration. Also, the Remote Control would not take up the screen, allowing you to see the robot/drone move around while controlling it.
## Items
- Receiver Upgrade, Tier 1, exposes the `receiver` component.
  - ´receiver.setchannel(channel:number)`, sets the channel, possibly with a limited range like 1-16.
  - Triggers a `receiver_command` event which holds a single value, which is the command sent from the transmitter.
- Remote Control (handheld item)
  - Right-click switches to control mode, which captures all player input, until another right-click is performed.
  - Shift+Right-click opens up a channel configuration screen.
  - Tier 1, captures movement keys (WASD+Space), very low power usage.
  - Tier 2, captures the above + all numeric keys.
  - Tier 3, captures the above + all keyboard keys.

**Comment by Vexatos** [comment] 2015-01-30 12:55
The remote should be made using a T2 CPU, a wireless network card, tablet case (?) and one of the keyboard components (the arrow keys I'd say).

**Comment by MyNameIsKodos** [comment] 2015-01-30 15:51
Maybe you'd have to right click with it in your hand for it to override your inputs, and then a certain key combo to break out of the override?

EDIT: Actually thinking about it, I wonder how difficult it would be to just make the RC act like you're mounted in a vehicle, and just need to sneak to break out of that.

**Comment by fnuecke** [comment] 2015-05-23 11:51
Having an extra receiver seems somewhat overkill, as do the tiers, but having a simple device that sends wireless network messages of a predefined format could be useful, I guess. Essentially something like a wireless keyboard, but sending network messages?

**Comment by TinkerWorX** [comment] 2015-05-23 12:27
That is a possible solution. The main reason for the separate receiver was that this would be a very low-tech and low-power component, meant for simple remote control tasks.

**Comment by KurikAmudnil** [comment] 2015-06-24 16:12
What about allowing a remote terminal to be linked to robot/drones? or to anything with a wireless network card?

**Comment by SaphireLattice** [comment] 2015-06-25 04:43
You realize that you can use tablet/robot/computer for remote control? And
drones don't even have a gpu.

**Comment by fnuecke** [comment] 2015-06-25 10:09
Yeah, "full" remote control is already possible via WLAN + some coding. The idea of this feature would be to add a much more limited/hardcoded but also much easier to set up way of sending commands to devices.

**Comment by lordjoda** [comment] 2015-06-25 10:14
I like the idea a lot! This should be made in a way, that a not programming experienced player still can use some features! Of course to some expenses bit still!

**Comment by OmegaHaxors** [comment] 2015-11-28 10:58
I had a simple setup with this sort of thing when I was first learning. It was very ugly and went through many revisions, but at the end it worked like:

local command = "idle"
local looping = true
modem.open(69) -- Don't judge, that's my port and don't you forget it!

while looping == true do

if keyboard.isAltDown() then command = "swing" end
if keyboard.isKeyDown(" " then command = "up"' end
if keyboard.isControll() then command = "down" end
if keyboard.isKeyDown("a") then command = "left" end
if keyboard.isKeyDown("d") then command = "right" 
if keyboard.isKeyDown("s") then command = "back" end
if keyboard.isKeyDown("w") then command = "forward" end

if command == "idle then else
modem.broadcast(69,command)
command = idle
end

Then all I have to do is parse the inputs on the other end and turn them into commands.

Also, please allow flashing directly onto eeproms installed in drones. It's so tedious to constantly have to re-flash my code to test it because I have a bad habit of not closing brackets, strings, and statements.

(I guess I could always close my brackets, but who has time for that?

**Comment by fnuecke** [comment] 2015-11-28 11:20
Just run the bios on a computer once (don't even need to flash it) to catch syntax errors.

**Comment by OmegaHaxors** [comment] 2015-11-30 03:19
The issue is that running the bios as a program means you have to require everything or else it will cause errors. And if you try to run the require code as a bios, it will cause errors.

If you could use the same code on both without having to change it, that would be great, but as it stands that's just not the case.

**Comment by fnuecke** [comment] 2015-11-30 07:43
It doesn't matter if the _code_ errors; you'd still be able to test for syntax errors simply by seeing whether it complains about syntax errors _before_ even running it. Which as I understood was the issue.

**Comment by OmegaHaxors** [comment] 2015-12-01 08:36
That isn't viable when the first error it runs into is lacking the requirement. I'm never going to get any info on my syntax when 2 lines in it crashes because either there was a require on the bios or there wasn't a require on the os.

The only solution through that is to include the unnecessary requirement and remove it when you're done, but then when changes need to be made that's even more adding and removing.

Is there a way to check if it's being ran as a bios so I can just put the requires in an if statement? That would solve every issue and wouldn't require constant editing of the code nor changes to the mechanics of the mod.

**Comment by gjgfuj** [comment] 2015-12-02 07:21
Syntax is checked before anything else though?

**Comment by OmegaHaxors** [comment] 2015-12-04 18:08
Oh! It does. Very nice. Thanks for the info.

**Comment by S0ZDATEL** [comment] 2017-10-24 14:45
I like the idea of a handheld device that can send wireless messages. It should work with EEPROM only, no hard drive. Perhaps it will be able to receive messages, not send only? I offer to make it with a small status-screen, like in the drones, so it can display some information.

**Comment by payonel** [comment] 2017-10-24 15:22
[Tablets](http://ocdoc.cil.li/item:tablet) can do this, just added a wireless modem to them and you're good to go

**Closed as completed by payonel** 2017-10-24 15:22 UTC
