### ISSUE TITLE
Total Fail in dev version...

### ISSUE THREAD

**Issue by SeniorFight** [MightyPirates/OpenComputers#802] opened 2015-01-11 12:34 UTC
"computer.getBootAddress() is a nil value, init.lua error"

my dreams became false...
To make a gui based operating system....

**Comment by fnuecke** [comment] 2015-01-11 12:35
Duplicate of #801. Use the edit functionality.

**Closed as completed** 2015-01-11 12:34 UTC

**Comment by SeniorFight** [comment] 2015-01-11 13:10
Sorry doubleposted delete this please.
