### ISSUE TITLE
Crash when looking up commands on pages with OC commands.

### ISSUE THREAD

**Issue by nanakisan** [MightyPirates/OpenComputers#2207] opened 2016-12-29 05:52 UTC
Hey there! This was an issue reported over at the FTB subreddits discord by a user named Foxie.

Initially they handed me this crash log
http://pastebin.com/DFWyg31Q

Showed nothing of interest. However when shown their client log this came out of the wood works.
```
[00:38:39] [Server thread/WARN]: Couldn't process command: 'help 7'
java.lang.NullPointerException
    at li.cil.oc.server.command.package$.getOpLevel(package.scala:18) ~[package$.class:?]
    at li.cil.oc.server.command.DebugWhitelistCommand$.isOp(DebugWhitelistCommand.scala:16) ~[DebugWhitelistCommand$.class:?]
    at li.cil.oc.server.command.DebugWhitelistCommand$.func_71518_a(DebugWhitelistCommand.scala:19) ~[DebugWhitelistCommand$.class:?]
    at net.minecraft.command.CommandHelp.func_184881_a(SourceFile:104) ~[al.class:?]
    at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
    at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
    at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
    at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
    at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[00:38:42] [Server thread/INFO]: Stopping server
```
Just posting this here in the likely chance it was not reported.

**Comment by Vexatos** [comment] 2016-12-29 10:31
Duplicate of #2155.

**Closed as completed by Vexatos** 2016-12-29 10:31 UTC
