### ISSUE TITLE
error when loading into world OpenComputers-MC1.9.4-1.6.0.1-beta.2

### ISSUE THREAD

**Issue by SDUBZ** [MightyPirates/OpenComputers#1854] opened 2016-06-07 10:12 UTC
loaded up world after adding open computers then i got a error in chat telling me to give you my full log file
[fml-client-latest.txt](https://github.com/MightyPirates/OpenComputers/files/302329/fml-client-latest.txt)
[latest.txt](https://github.com/MightyPirates/OpenComputers/files/302330/latest.txt)

**Comment by fnuecke** [comment] 2016-06-07 14:28
Thanks! Duplicate of #1849.

**Closed as completed by fnuecke** 2016-06-07 14:28 UTC

**Comment by SDUBZ** [comment] 2016-06-07 14:30
but my game freezes up after this message so i had to disable OC for now

**Comment by fnuecke** [comment] 2016-06-07 14:44
Hmm, are you sure that's due to OC?

FWIW, other things in the log that seem suspect:

AbyssalCraft:

```
java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not exist in BlockStateContainer{block=abyssalcraft:darkbrickslab2, properties=[variant]}
```

Quark:

```
[20:06:35] [Client thread/ERROR] [JEI/]: Found a broken recipe: net.minecraftforge.oredict.ShapedOreRecipe@719eff0d
Output ItemStacks: [[1xquark:ender_watcher@0]]
Output Fluids: []
Input ItemStacks: Found an itemStack with a null item. This is an error from another mod.
Input Fluids: []
```

???:

```
[20:06:53] [Netty Local Client IO #0/ERROR] [FML/]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(4) exceeds writerIndex(4): SlicedByteBuf(ridx: 4, widx: 4, cap: 4/4, unwrapped: UnpooledHeapByteBuf(ridx: 0, widx: 5, cap: 256))
```

EnchantingPlus (likely follow-up error):

```
[20:06:53] [Netty Local Client IO #0/ERROR] [FML/]: There was a critical exception handling a packet on channel EnchantingPlus
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(4) exceeds writerIndex(4): SlicedByteBuf(ridx: 4, widx: 4, cap: 4/4, unwrapped: UnpooledHeapByteBuf(ridx: 0, widx: 5, cap: 256))
```

**Comment by SDUBZ** [comment] 2016-06-07 19:05
okay let me check without enchntingplus and quark and see if it makes a
difference :D

**Comment by SDUBZ** [comment] 2016-06-07 20:10
it was actually enchanting plus causing it not to work
