### ISSUE TITLE
Crash with recipe in NEI

### ISSUE THREAD

**Issue by Stette** [MightyPirates/OpenComputers#967] opened 2015-03-21 19:07 UTC
Tried to search for a recipe in NEI and the client crashed. Posted to Applied Energistics Github, but they said the problem was with OpenComputers, so I'm just posting this here for you!

It happened when I pressed "U" on a recipe for AE2.

http://pastebin.com/SRXQ0j1w

**Comment by CaitlynMainer** [comment] 2015-03-21 19:09
`java.lang.NoSuchFieldError: instance`
Usually means that some mod you're running is forcing a old API for OC.

**Comment by fnuecke** [comment] 2015-03-21 19:40
Update OpenComputers, this was fixed ages ago.
Duplicate of #847.

**Comment by Vexatos** [comment] 2015-03-21 19:41
Make sure to also update Computronics, it will have a similar crash if you don't.

**Closed as completed by fnuecke** 2015-03-21 19:40 UTC
