### ISSUE TITLE
[Issue?] Unable to read from Tanks

### ISSUE THREAD

**Issue by accessdenied0** [MightyPirates/OpenComputers#2063] opened 2016-09-20 16:12 UTC
Hello MightyPirates-crew,

I might run in a issue and I need approval. I set up to to try out the OC-API a simple setup to read from Inventories and Tanks:
https://imgur.com/a/rbE3v

For each task I used the appropriate module (eg. Tank I use the _"Tank Controller Upgrade"_). The Inventory Controller Upgrade worked fine, but I run into some issue with the Tank one. The program returns, what ever what side (4 or north in this case) or method I use nil or {n, 0}. 

 I used both versions the recommend version on curse and the dev version on  http://ci.cil.li/job/OpenComputers-dev-MC1.10/. (which fixed the transformer bug)

I need now approval for my bug! Thank you for your help and time,

access_denied

**Comment by Belgabor** [comment] 2016-09-20 17:58
I can confirm that. Neither the tank controller upgrade nor the translocator seems to be able to read tanks in 1.6.0.3 for MC 1.10.2.

**Comment by accessdenied0** [comment] 2016-09-20 18:10
@Belgabor , thank you. 
Now that this is confirmed and I'm not totally bad in lua (hehe) I hope for a fix soon.

**Comment by mzx987** [comment] 2016-09-22 00:22
Not quite the same issue, but I have a similar problem with Ender IO Capacitors. I cannot seem to read from those. Could this be happening due to an outdated API?

**Comment by Vexatos** [comment] 2016-09-22 08:40
@mzx987 That is not related at all.

**Comment by Vexatos** [comment] 2016-11-14 17:35
I cannot reproduce the issue on OpenComputers 1.6.0. Could you test using the latest release?

My setup:
![2016-11-14_18 29 43](https://cloud.githubusercontent.com/assets/4135064/20275466/f5d80b1e-aa98-11e6-872d-90e3380095f8.png)

Code working as expected:
![2016-11-14_18 29 39](https://cloud.githubusercontent.com/assets/4135064/20275469/f718405c-aa98-11e6-8026-6e71d65fea59.png)

**Comment by BikerEleven** [comment] 2016-11-19 21:02
I tested this with several mods using OpenComputers-MC1.10.2-1.6.0.4

I will list the mod and version along with a link to my testing setups:
TConstruct-1.10.2-2.5.6b [Gallery](http://imgur.com/a/Ym8Bt)
Mekanism-1.10.2-9.2.0.294 [Gallery](http://imgur.com/a/Ldi1d)
deepresonance-1.10-1.3.0 [Gallery](http://imgur.com/a/hcPvX)
extrautils2-1.10.2-1.0.0 [Gallery](http://imgur.com/a/eyoIL)
EnderIO-1.10.2-3.0.1.135_beta [Gallery](http://imgur.com/a/pv0Mm)

For the blocks that can be configured I did try most of the configurations and I tried all of the sides of the blocks pictured above. 

And here is my computer setup
[http://imgur.com/a/Jd9Jr](http://imgur.com/a/Jd9Jr)

In my testing I found that the thinkers smeltery drain worked in [1.7.10](http://imgur.com/a/pzcbS) with OpenComputers-MC1.7.10-1.6.0.9-universal 
but [1.9](http://imgur.com/a/lZ19n) and onward it stopped working 

Here is the Client-2 log [http://pastebin.com/hpyEmd4A](http://pastebin.com/hpyEmd4A)
And here is the full log [https://dl.dropboxusercontent.com/u/16655497/Misc/fml-client-latest.log](https://dl.dropboxusercontent.com/u/16655497/Misc/fml-client-latest.log)

I hope this helps.

**Comment by Vexatos** [comment] 2016-11-19 22:31
Would you mind testing if it works for you with IC2 experimental blocks?

**Comment by Vexatos** [comment] 2016-11-19 22:46
I was only able to test with EnderIO, but https://github.com/Vexatos/OpenComputers/commit/533648909b9a9b5fbc8d075e96c7d79b0ac99af2 adds support to that at least (IFluidHandler capabilities in general). Would you mind testing all those mods using ~~this build~~[URL removed]? It contains the aforementioned addition to OC.

**Comment by BikerEleven** [comment] 2016-11-19 23:10
I have confirmed using OpenComputers-MC1.10.2-1.6.0-dev+5336489 that the mods I listed before have started working with the transposer as expected. The industrialcraft-2-2.6.96-ex110 blocks worked before this version using OpenComputers-MC1.10.2-1.6.0.4 and still function normally after. 

[Gallery](http://imgur.com/a/nIQFb)

**Comment by Vexatos** [comment] 2016-11-19 23:15
Thank you very much, so it was, indeed, just a missing feature, basically.

**Comment by Vexatos** [comment] 2016-11-19 23:20
Fixed via https://github.com/MightyPirates/OpenComputers/commit/b7e03cae44ebcfa17baf309d6c1b29a17fe5321a.

**Closed as completed by Vexatos** 2016-11-19 23:20 UTC
