### ISSUE TITLE
I Really Want Laptops in Opencomputers

### ISSUE THREAD

**Issue by igorkll** [MightyPirates/OpenComputers#3669] opened 2023-10-05 19:55 UTC
as far as I understand, laptops do not fit the style of the mod?
it seems to me that they do not contradict the concept or style of the mod, but on the contrary complemented the mod and will cause an influx of fresh air into this mod.
there are tasks where it is not very easy without a laptop, for example, if you need to set up a repeater that is shared by other repeaters and you cannot get direct access to it, you cannot interact with its API with a tablet and it is not very convenient to carry a computer in the inventory...

**Comment by asiekierka** [comment] 2023-10-05 19:57
As much as I understand your enthusiasm, this is still a duplicate of https://github.com/MightyPirates/OpenComputers/issues/2203 . Please keep all discussion to that issue, or one of the many other issues about adding laptops to OpenComputers.

There's always the possibility of making an add-on mod for this purpose.

**Closed as completed by asiekierka** 2023-10-05 19:57 UTC

**Comment by igorkll** [comment] 2023-10-05 20:00
> There's always the possibility of making an add-on mod for this purpose.

I can't handle creating an addon, but I would really like it to be created.

also, what about the ability to configure restrictions in the collector? can this be added?

**Comment by igorkll** [comment] 2023-10-05 20:06
according to my idea, laptops were supposed to be a hybrid of a tablet and a computer so that it could be used from the inventory, as well as by putting it on the terrain it would have access to external components.

I hope that someone from the community will be able to bring my idea to life
