### ISSUE TITLE
File randomly blank after a while.

### ISSUE THREAD

**Issue by sulljason** [MightyPirates/OpenComputers#3040] opened 2019-02-06 02:33 UTC
This is a fun one because there's probably like 20 places the bug could be including OpenOS text editor or shell! I'll log-in the next real world day and some files will just be blank. So far ones that I had been working on the night before. I'll try and do process of elimination to try and cull possible causes.

DETAILS:
OC vers: 1.12.2-1.7.3.146
Host OS: Ubuntu Server 18.04 LTS
JVM: Azul's OpenJDK Zulu 1.8_202
JVM options: -Xms4G -Xmx4G -XX:+TieredCompilation -XX:+AggressiveOpts -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxGCPauseMillis=50
Small server with 2 people I do all the programming.
Computers chunk loaded 24/7 using FTB Utils.
In game computer is a server in a rack.
In game computer is left on just sitting at a shell.
Blank on hosts physical disk as well.
No error on the physical server.

IDEAS:
Could be G1s string deduplication misbehaving since OC HDD contents are cached in ram I'm guessing as large strings.
Aggressive optimizations are experimental and could be misbehaving.
Bug in OC's persistence library.
Bug in OC's writing through to disk.
Bug in OpenOS shell or editor.

**Comment by payonel** [comment] 2019-02-06 07:24
please try our lateset dev build
https://ci.cil.li/job/OpenComputers-MC1.12/
duplicate of #3031

**Closed as completed by payonel** 2019-02-06 07:24 UTC

**Comment by sulljason** [comment] 2019-02-07 00:15
I saw that one a while ago, but I wasn't sure if it was related. I'll give the dev build and let you know. Reading further, ya it does fit what I'm running very specifically. Thanks @payonel
