### ISSUE TITLE
New Versions

### ISSUE THREAD

**Issue by Leonardo5681** [MightyPirates/OpenComputers#3562] opened 2022-09-22 14:22 UTC
Hi, I would like an answer from the developer of the mod, but why don't you update the mod for new versions like 1.16 or 1.17 or even 1.18 or 1.19? It doesn't make sense because it's a fantastic mod, but I want to use it on a new version and I don't know how to do it.Please I want response from the developer

**Comment by asiekierka** [comment] 2022-09-22 20:35
Short answer: No time budget.

Duplicate of https://github.com/MightyPirates/OpenComputers/issues/3450

**Closed as completed by asiekierka** 2022-09-22 20:35 UTC

**Comment by PublicVoidUpdate** [comment] 2022-09-22 22:16
(Not a contributor, but lurker) It's really difficult to port mods to different versions of Minecraft, it often takes a rewrite of the mod. MC 1.12.2 and under needs Java Jdk/Jre 8, MC 1.16 and over needs at least Java Jdk/Jre 15 and up. So that alone needs accounting for, plus version difference like 1.13's new chunk rendering setup. There are some spiritual successors to OC, that exist for 1.16 and up if they fit what you need

**Comment by Leonardo5681** [comment] 2022-09-23 06:26
A ok, I'm sorry but I will have to settle, I wanted it updated because I wanted to make a modpack tech with the cc-tweaked and the opencomputer, and I wanted to do it in 1.16.3, and this means that I will not be able to do it anymore and my dream it will always remain a dream

**Comment by PublicVoidUpdate** [comment] 2022-09-23 06:28
there's this spiritual successor that might be what your looking for, it's available for 1.18.2 if you want to check it out. https://www.curseforge.com/minecraft/mc-mods/oc2

**Comment by Leonardo5681** [comment] 2022-09-23 07:04
Thanks, however when you have time to do it you could update it right?

**Comment by asiekierka** [comment] 2022-09-23 18:17
I hypothetically could, but it is not something I am interested in doing at this time.
