### ISSUE TITLE
strange crash on server

### ISSUE THREAD

**Issue by kreezxil** [MightyPirates/OpenComputers#1189] opened 2015-05-30 00:42 UTC
"strange crash on dedicated forge server"
server crash report: http://pastebin.com/B9VM1B6r
server fml latest: http://pastebin.com/E353FskP
I'm currently using b1419

lexmanos said to contact the coremod authors, you are one of them

**Comment by dgelessus** [comment] 2015-05-30 01:53
The crash seems to be while loading entity data from the world. The only entities that OC adds are drones, have you used any of those? If not, then OC is probably not the cause of the crash.

**Comment by kreezxil** [comment] 2015-05-30 02:45
No drones yet so it must not be oc.

Thks

-----Original Message-----

**Comment by fnuecke** [comment] 2015-05-30 09:02
Looking at the code of the trace, where it's actually crashing is when loading scheduled block ticks. OC only even uses these in two cases: as a safeguard for cleaning up robot "afterimages" (used for transitioning a robot's bounding box from one block to another when it is moving) and for the 3D prints' button mode (same logic as for vanilla buttons). I've not run into this yet, and I've had a bunch of prints and a few moving robots in my 1.8 test world, so I'm doubtful it's OC.

What I can say is that OC's class transformer does not even go near the involved logic.

Until you can reproduce this with OC only, I'll be closing this. If you _can_ reproduce it with OC only, please do let me know here, ideally with a stable way to reproduce (one can dream).

**Closed as completed by fnuecke** 2015-05-30 09:02 UTC

**Comment by kreezxil** [comment] 2015-05-30 13:37
Ok, the good news is there are no robots involved, so for you this is
closed. :) Do you have a patreon account?

**Comment by fnuecke** [comment] 2015-05-31 12:22
Thanks for asking! But no, I don't.
