### ISSUE TITLE
Error on World Creation (Forge 1448)

### ISSUE THREAD

**Issue by Amaxter** [MightyPirates/OpenComputers#1243] opened 2015-06-24 20:38 UTC
http://hastebin.com/fobufomuno.vhdl

**Comment by Techokami** [comment] 2015-06-24 22:13
According to this log, the problem is not with OpenComputers, but with Balkan's Weapon Mod. (See lines 184 to 264)

**Comment by Amaxter** [comment] 2015-06-24 22:15
Ok, I'll look into that thank you.

**Comment by fnuecke** [comment] 2015-06-25 10:06
The only mention of OC

> §aOpenComputers§f: There were §cerrors§f running the class transformer.

actually just means OC gracefully avoided crashing and burning. It's probably due to the new Project Red version changing the screwdriver API, and that has been fixed in 1.5.13.

As for the BWM thing just seems to be an issue in a MineTweaker script, so that also shouldn't crash / be a real issue.

**Closed as completed by fnuecke** 2015-06-25 10:06 UTC
