### ISSUE TITLE
Wireless network card does not receiving messages

### ISSUE THREAD

**Issue by hantagu** [MightyPirates/OpenComputers#3290] opened 2020-05-06 21:54 UTC
Tier 1 Wireless network card does not receiving messages, but "Wake message" is working

**Comment by payonel** [comment] 2020-05-07 00:08
https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by payonel** [comment] 2020-05-07 00:33
get latest dev builds from https://ci.cil.li/
duplicate of #3195

**Closed as completed by payonel** 2020-05-07 00:33 UTC
