### ISSUE TITLE
Someting wrong with the screen's GUI.

### ISSUE THREAD

**Issue by zyt20001205** [MightyPirates/OpenComputers#3363] opened 2020-10-04 06:07 UTC
![open computers](https://user-images.githubusercontent.com/26330271/95008229-8abe3580-064a-11eb-9a65-4182bc0a9e1c.JPG)
 When I right-click a screen, I have an issue with its GUI. Instead of an interface with a black background, my interface has grey and white margin. Is there anything wrong with my resolusion configuration?

**Comment by payonel** [comment] 2020-10-05 16:22
try reloading textures (F3+t i believe), could be a conflict with shaders or other graphics mods.

**Comment by WarPlexTech** [comment] 2020-10-18 23:23
Duplicate of #3350

Solution from #3350 :
> @Nagispace
> This is **_NOT_** a bug of OpenComputers. This is bug in the texture.
> I guess that you're using Faithful32 texture pack.
> If so, go and delete `assets/opencomputers/textures/gui/borders.png` in your F32.zip resourcepack (_or modify this texture: one should have small black square in the middle; these middle pixels define color of screen_).

**Closed as completed** 2020-10-19 23:59 UTC
