### ISSUE TITLE
[Feature Request] Virtual GPU buffer (delay drawing to bound screens)

### ISSUE THREAD

**Issue by SDPhantom** [MightyPirates/OpenComputers#2418] opened 2017-06-08 10:25 UTC
Currently, every GPU call updates the bound screen immediately. What a GPU buffer does is make it so each call applies to a portion of its video memory and when a program is ready to show the frame, it signals the GPU to send it out. Fortunately, everything needed to implement this is already in the code as-is. We are capable of polling any pixel of the GPU to get its background, foreground, and displayed character. This means we already have a buffer. The only thing to change is when connected screens get updated. To do this, we would set a flag on the GPU when we make a change to the buffer via a GPU call. When the program performs a sysyield, the GPU pushes out the frame if the flag was set. Not only does this allow more complex visual effects like text updating under other UI elements, but should improve performance of the mod overall by limiting the number of updates pushed out to screens.

**Comment by skyem123** [comment] 2017-06-08 11:16
A problem I see with that is how it would interact with GPU call limits and in general avoiding sending too much data at once to clients. I do think that if possible, buffering would be useful.

**Comment by Techokami** [comment] 2017-06-08 13:10
Isn't this a duplicate of #779?

**Comment by magik6k** [comment] 2017-06-08 16:11
It sounds more like double-buffering, but there have been at least few issues on that too(referenced in #779)

**Closed as completed by magik6k** 2017-06-08 16:11 UTC

**Comment by SDPhantom** [comment] 2017-06-09 20:11
VRAM implementation is a more complicated request. Double buffering is the focus of this and I don't see how this would have anything to do with GPU call limits. They'd work the exact same as they always do, just don't show changes on the screen immediately. I'm not looking for faster runtimes, just stopping screen flicker while the program is actively making GPU calls.

A point I made would be the effect of possibly making it easier on the minecraft server by not updating the display so often. This would have no effect on the Lua environment.

**Comment by xarses** [comment] 2017-06-09 21:31
We've had some extensive conversations, including double-buffering on older requests so I'll repeat my self from #2279 

> Feature requests should include several use cases to help understand what you are attempting to accomplish, you should also describe why the existing implementation doesn't meet these uses case for you. Finally, please identify how this feature would be different from the existing graphics feature requests, #779 #1901

**Comment by SDPhantom** [comment] 2017-06-10 03:28
Here's what I'm asking for, filtering out the nonsense making the idea fit with the concept of the mod. Change the screen rendering code outputting to screen blocks so that it doesn't update the display until a program performs a sysyield. In short, this is when **_machine.lua_**, calls **coroutine.yield()**.

Currently, when the screen updates, it's either per GPU call or at random times that are often in the middle of a program trying to make them. This causes screen flickering by pushing out incomplete frames.

I'm not asking for VRAM, buffer manipulation, or any changes to GPU call limits. Sorry for the confusion, I have difficulty describing my ideas sometimes. Now that I've had time to brew on this, it feels like I'm trying to pitch the idea of G-Sync/FreeSync.

**Comment by skyem123** [comment] 2017-06-11 15:23
Hmm... I see, but that it has an issue in that it would probably break stuff like @asiekierka's video playing? Maybe if it was an optional thing it could work...

**Comment by Ocawesome101** [comment] 2020-09-04 20:00
Neat that (basically) this is now implemented. How the times have changed, eh? :upside_down_face:
