### ISSUE TITLE
Robot keyboard input not working after disconnect/reconnect to Minecraft server [1.3.6]

### ISSUE THREAD

**Issue by jpastuszek** [MightyPirates/OpenComputers#630] opened 2014-10-27 23:51 UTC
I have this problem with my robot that when I leave it running and disconnect from Minecraft server and connect back in I can access it's GUI and slots but I cannot type on the screen any more.
Also screen goes black but new messages are being displayed.

Turning it off and on does not help. Only when I brake the robot and place it again it works OK until I leave and then join the game.

I don't have any users created on the robot and OS was installed on another computer (not robot) before I have assembled it.

Both server and client run on W7.

**Comment by fnuecke** [comment] 2014-10-28 12:26
Hmm, sounds like the init info isn't transferred properly... could you check your log for any warnings directly after logging in, please?

**Comment by jpastuszek** [comment] 2014-10-28 23:18
I didn't see any warnings that look related.

Also it looks like that after some time (couple of minutes) when I came back to click on the robot I could still see only new messages but I was able to terminate the program. I wonder if robot is in sleep (I put it to sleep for a minute) it blocks killing the foreground program with CTRL+ALT+C?
Still I would expect the screen to redraw any message that was displayed before I have disconnected as normal computer screen does.

Here is the client log (since start until I have tried to get the robot GUI to respond):
https://gist.github.com/jpastuszek/e875446058dd8639f46b
And corresponding server log (very, very long):
https://gist.github.com/jpastuszek/19cefcc673b05ca862eb

And here is the screenshot where all old messages are gone and only few new are printed:
![2014-10-28_19 35 16](https://cloud.githubusercontent.com/assets/20052/4818809/64ceb19c-5ef8-11e4-8fd1-df3b685418a3.png)

**Comment by fnuecke** [comment] 2014-10-29 11:33
Hmm, it _should_ properly request the state from what I can see (and does in my tests), not exactly sure how, yet, but might be a timing issue with network messages getting processed in the wrong order...

As for the keyboard, does it work after you manually reboot the robot (power off and on again)? In that case it should also be working before rebooting and I'd assume it's some Lua side issue.

**Comment by jpastuszek** [comment] 2014-10-30 00:24
I did some experiments and the issue is very funny since it looks like it is happening in 2 particular chunks (-2/15, -3/15 in this case).

There is nothing particular in this chunks; just IC2 cables, battery, charger with converter, some stone blocks from RailCraft...

No particular program needs to be running (just OpenOS prompt) for this to brake after disconnect/reconnect.
Stop/start does reboot the robot but still no access with keyboard.
Looks like the VM is running since it is running all the code; the cursor is blinking, my program is running if left running, stop/start reload the OS.

**Comment by fnuecke** [comment] 2014-10-30 15:32
Hmm just double checked if it might be a coordinate screwup so that the -/+ quadrant doesn't work, but it does for me... could you tell me the composition of the robot, please? (i.e. exactly which parts were used to build it)

Also, since it sounds like this is 100% reproducible for you, could you see if this also happens if OC is the only mod installed? Thanks.

**Comment by jpastuszek** [comment] 2014-10-30 23:17
Here is the composition:
![2014-10-30_23 15 38](https://cloud.githubusercontent.com/assets/20052/4853887/cb2a4792-608a-11e4-97dc-e78f0b7c9ad4.png)

I will try it out without other mods over weekend.

**Comment by fnuecke** [comment] 2014-10-31 15:44
Thanks. Another angle, if there's a chance the robot is moving while you get back to it, could place another robot (same chunk, preferably) that doesn't move, and when this happens again check if the stationary robot behaves the same? I doubt that's what it is if you can reproduce this reliably, but maybe something gets sent in the wrong order if the robot is currently moving while the chunk data is being sent to the client.

Edit: oh, and just to be 100% sure it's not that either (which I'm 99% sure it isn't), mind testing this on Forge 1230, so we're on the same page there?

**Comment by jpastuszek** [comment] 2014-11-02 23:04
I have updated to 1230 (I was on 1217) and at first I thought that this was fixed since I could access my robot just after log in but any next time the issue has manifested.
The issue does not manifest if I run same world in single player mode no matter if I run it on my MBA or W7 PC.
If I connect with my server (that normally is at localhost (W7 PC)) form my Mac laptop the problem is still observable.

**Comment by jpastuszek** [comment] 2014-11-02 23:31
If I run OpenComputers and OpenComponents mods only the issue is not there any more.

**Comment by jpastuszek** [comment] 2014-11-02 23:55
Looks like industrialcraft-2-2.2.489-experimental causes the issue. If I remove it I can no longer reproduce the issue.
The thing I did not check is if I leave IC2 and OC and remove everything else... perhaps I can try that later.

**Comment by fnuecke** [comment] 2014-11-03 01:31
Thanks a lot for digging into this. No clue how IC2 might be related to this however... I'm pretty sure I had it present when trying to reproduce this, too.

**Comment by jpastuszek** [comment] 2014-11-19 18:18
So now I am on build 234 and my server does not crash :) but I still see the issue.
Now if I log in to my server the robot is accessible but if I disconnect and connect back in I get the same issue as described above.
If I restart my client and connect in all is good again!
So now the issue only happens when I disconnect/re-connect again without restarting the client.

At this time my server is on Linux platform and I am still with IC 489 (migration bug prevents me to go to any newer version).

**Comment by fnuecke** [comment] 2014-11-19 19:10
Did you ever get around to testing if this also happens if it's just OC + IC2 (no other mods)? Because I still can't reproduce this.
This might also be related to which blocks are adjacent to the robot. Could you post a screenshot?

If restarting the client helps it's apparently something being cached somewhere... there's only one such list in OC that I think might be related, and I don't see how that wouldn't be properly cleaned up anyway, but I'll look into adding an explicit clear() on disconnect just to make sure.

**Comment by fnuecke** [comment] 2014-11-20 07:19
Please try build 236 when it's done to see if the explicit clearing helped.

**Comment by jpastuszek** [comment] 2014-11-20 14:54
Nope... still there with 237.
Now I have two robots and both have the same problem:

![2014-11-20_14 48 04](https://cloud.githubusercontent.com/assets/20052/5126431/d3f329f8-70c4-11e4-9269-c7af4ecf6378.png)
![2014-11-20_14 48 08](https://cloud.githubusercontent.com/assets/20052/5126434/d616dc0c-70c4-11e4-92ce-3c806f67f361.png)
![2014-11-20_14 49 31](https://cloud.githubusercontent.com/assets/20052/5126435/d7ec73fc-70c4-11e4-847d-270a4e7fbdc9.png)

**Comment by fnuecke** [comment] 2014-11-20 20:09
I'm afraid I still cannot reproduce this, building both of these setups. So it'd be really helpful to know if this also happens for you when OC and IC2 are the only mods present, or if it might in fact be an interaction with yet another mod (although I really don't quite see how).

**Comment by fnuecke** [comment] 2014-12-23 02:38
Any update on this? Does this still happen? If so,

> it'd be really helpful to know if this also happens for you when OC and IC2 are the only mods present

**Comment by jpastuszek** [comment] 2015-01-11 22:58
Sorry for not responding... I started new world and just managed to build some computer stuff.
I am on 1.4.3 Beta 1 and build T2 computer.
When I log in sometimes I get it in bad state:
![2015-01-09_19 44 52](https://cloud.githubusercontent.com/assets/20052/5697312/d96e3a14-99e4-11e4-9715-4a7d64610140.png)
The screen only shows the cursor and no input is accepted.
This time I only need to disconnect and reconnect to the game to get it fixed.

Sometimes I get the screen to render:
![2015-01-09_19 45 12](https://cloud.githubusercontent.com/assets/20052/5697314/e18f9c92-99e4-11e4-9994-692d9c48b9fb.png)
But no input is accepted.

I will soon upgrade to latest version.
This time I have no IC2 at all but added other mods like Botania (I use mana to power the computers via redflux) or Taumcraft.

**Comment by fnuecke** [comment] 2015-01-12 15:20
When this happens again, please grab a Debugger (the item, Analyzer in magenta-ish) and
- Shift-rightclick the screen with it.
- Type on the screen with it in hand.
- Tell me what it says in both the server and the client log.

**Comment by jpastuszek** [comment] 2015-01-12 20:15
This time I can see text on the screen but no input is working:

```
[20:10:26] [Client thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] Sending packet to node ce4de990-b93a-4751-9c33-ea655d844acd: {type = keyDown, char = d, code = 32}
[20:10:26] [Client thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] Sending packet to node ce4de990-b93a-4751-9c33-ea655d844acd: {type = keyUp, char = d, code = 32}
[20:10:26] [Client thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] Sending packet to node ce4de990-b93a-4751-9c33-ea655d844acd: {type = keyDown, char = d, code = 32}
[20:10:27] [Client thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] Sending packet to node ce4de990-b93a-4751-9c33-ea655d844acd: {type = keyUp, char = d, code = 32}
[20:10:27] [Client thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] Sending packet to node ce4de990-b93a-4751-9c33-ea655d844acd: {type = keyDown, char = d, code = 32}
```

```
[20:10:42] [Server thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] Node removed from network: {address = eebdd0ea-37e4-4af1-aa3d-247ddc4457b0, reachability = Network()}
[20:10:42] [Server thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] New node in network: {address = eebdd0ea-37e4-4af1-aa3d-247ddc4457b0, reachability = Network()}
[20:10:42] [Server thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] New node in network: {address = 39a1afa3-7b51-4c2f-ab63-2e32fc9a041d, reachability = Network, type = component, name = keyboard, visibility = Network}
[20:10:42] [Server thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] New node in network: {address = a85939b9-7903-4140-b880-b70e2d5e1dfc, reachability = Network, type = component, name = computer, visibility = Neighbors, type = connector, buffer = 500.0, bufferSize = 50
0.0}
[20:10:42] [Server thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] New node in network: {address = 1720a758-840f-41d7-b82a-f82e5fdfd272, reachability = Network, type = component, name = assembler, visibility = Network, type = connector, buffer = 0.0, bufferSize = 1000.
0}
[20:10:42] [Server thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] New node in network: {address = ce4de990-b93a-4751-9c33-ea655d844acd, reachability = Network, type = component, name = screen, visibility = Network, type = connector, buffer = 0.0, bufferSize = 0.0}
[20:10:42] [Server thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] New node in network: {address = 99afb3d7-aacb-4f95-a289-b8f6876c4160, reachability = Network, type = component, name = modem, visibility = Neighbors}
[20:10:42] [Server thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] New node in network: {address = 063492db-f08c-49aa-854c-7bd19afc56e4, reachability = Network, type = component, name = filesystem, visibility = Neighbors, type = connector, buffer = 0.0, bufferSize = 0.
0}
[20:10:42] [Server thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] New node in network: {address = 75b6007e-585a-4554-af9d-ecb23adfcb15, reachability = Network, type = component, name = microcontroller, visibility = Network, type = connector, buffer = 0.0, bufferSize =
 0.0}
[20:10:42] [Server thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] New node in network: {address = fc33090c-86e2-47a1-8200-de7564969277, reachability = Network, type = component, name = filesystem, visibility = Neighbors, type = connector, buffer = 0.0, bufferSize = 0.0}
[20:10:42] [Server thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] New node in network: {address = d1e56975-7e78-4e29-8064-2c0a1dc228a7, reachability = Network, type = connector, buffer = 1000.0, bufferSize = 1000.0}
[20:10:42] [Server thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] New node in network: {address = f0671874-347f-4abd-85b6-5c1021a35a39, reachability = Network, type = component, name = eeprom, visibility = Network, type = connector, buffer = 0.0, bufferSize = 0.0}
[20:10:42] [Server thread/INFO] [OpenComputers]: [NETWORK DEBUGGER] New node in network: {address = 3ccb917e-17cf-47bb-aefd-1cb0288413f1, reachability = Network, type = connector, buffer = 1454.5177539062454, bufferSize = 1600.0}
```

**Comment by fnuecke** [comment] 2015-01-13 12:24
Thanks! That's... interesting. So the address of the screen gets sent to the client correctly, and the key presses are sent back to the server, but the server appears to fail mapping them back to the screen.

Assuming that's the case it _might_ also explain the black screens - the screen init request would simply fail because it couldn't be mapped properly. Will see if anything looks like it could incorrectly kill off mappings.

**Comment by fnuecke** [comment] 2015-01-13 12:52
Well, not much to be found, honestly. But do give [build 333](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/) a go, please, and let me know if there's any change or not. Otherwise I'll have to extend the Debugger item a bit to allow dumping the server-side mappings to get a better idea of what's going on.

**Comment by jpastuszek** [comment] 2015-01-18 11:59
OK, with build 333 I could not reproduce the issue. I will keep trying and let you know if this shall happen again.

**Comment by fnuecke** [comment] 2015-01-18 12:00
OK, thanks!

**Closed as completed** 2015-02-13 14:01 UTC
