### ISSUE TITLE
[Request] (Re-)Add MCMultiPart Support for cables

### ISSUE THREAD

**Issue by JFBM** [MightyPirates/OpenComputers#2846] opened 2018-05-26 21:55 UTC
#1634 states that MCMultiPart is added, but from #oc I learned today that wasn't ported to MC 1.12.2  
May I request for it to be added?

**Comment by brisingraerowing** [comment] 2018-06-27 02:00
This is a duplicate of #2652, FWIW. AFAIK the MCMP2 API is much easier to use.

**Closed as completed** 2018-06-27 17:30 UTC
