### ISSUE TITLE
No Inventory Issue

### ISSUE THREAD

**Issue by daddyboy2001** [MightyPirates/OpenComputers#1878] opened 2016-06-12 22:38 UTC
So my code is shown in the screenshots but the inventory controller and transposer always return no inventory. it's a vanilla chest as seen.

http://i.imgur.com/PGEYivY.png
http://i.imgur.com/aGpUUIs.png

**Comment by tenten8401** [comment] 2016-06-12 23:19
I am experiencing the same problem as well.

**Comment by xarses** [comment] 2016-06-13 01:11
versions?

**Comment by daddyboy2001** [comment] 2016-06-13 01:15
OpenComputers-MC1.7.10-1.5.22.46-universal

**Comment by daddyboy2001** [comment] 2016-06-14 18:50
Any update?

**Comment by payonel** [comment] 2016-06-14 22:33
just fyi, sangar is taking a short break. we worked pretty hard getting beta 3 out the door of 1.6 -- we will have updates and fixes for 1.6 (that is, beta 3 is not the final version). Can you retest this using oc 1.6 beta 3? if repro, post here - thanks

**Comment by fnuecke** [comment] 2016-06-15 19:49
As payonel mentioned, could you please see if this works on latest 1.6 for you? Because at least in dev in cannot reproduce it. Thanks.

(And yes, I'm not on much currently, and probably won't be next week, in the middle of moving.)

**Comment by danyi-david** [comment] 2016-12-28 14:32
Have this issue with v1.6.1.6 right now.

I've got an adapter with an inventory controller, there is a mass_fab an mfe and a hopper touching its 3 sides, but I get "no inventory" for all sides with the following test code:

```lua
local component = require("component")
local inv = component.inventory_controller

for i=0,5 do
  print(fabinv.getInventorySize(i))
end
```

This is the only inventory controller in the small computer setup, and if I remove the upgrade from the adapter it does throw an error when running the same program.

Using the direwolf20 1.10 modpack with its latest version that I just upgraded a few days ago, this computer setup was working fine before the upgrade running with OC v1.6.0.4 back then.

**Comment by bhuffstutler** [comment] 2017-01-15 22:01
I have noticed this happens when the chunk containing my transposer is claimed using FTB utils chunk claiming.  This is occuring with FTBUtilities 3.2.4 and OpenComputers 1.6.1.6.  If I unclaim the chunk the normal behavior is restored.

**Comment by thiakil** [comment] 2017-01-16 01:54
@bhuffstutler in that case, you may need to enable fake players
`/ftb team config ftbu.fake_players true`

**Comment by bhuffstutler** [comment] 2017-01-16 20:20
@thiakil that did indeed resolve my issue.  Thank you for pointing that out.

**Comment by payonel** [comment] 2017-01-16 21:06
@bhuffstutler issue closed?

**Comment by bhuffstutler** [comment] 2017-01-16 21:58
@payonel I can't speak for the OP or others, but the command @thiakil suggested did resolve the issue for me.

**Comment by payonel** [comment] 2017-01-16 22:03
@daddyboy2001 please try `/ftb team config ftbu.fake_players true`

**Comment by tenten8401** [comment] 2017-01-16 22:59
I'm friends with @daddyboy2001 in real life, and I can confirm that the server he was having the issue on is long gone. You can probably just close it now.

**Closed as completed** 2017-01-17 05:08 UTC

**Comment by GHXX** [comment] 2021-02-14 20:25
Just leaving this as a note here for anyone who might also run into this issue.
It seems that chests which are protected by Pneumaticcraft's Security station, also cannot be found. 
So if you run into the issue, check if there are any mods which protect the chest(s) in question.
