### ISSUE TITLE
i cant craft a drone with my eeprom

### ISSUE THREAD

**Issue by JulianWogersien** [MightyPirates/OpenComputers#2770] opened 2018-03-07 20:26 UTC
i have written a wireless control script and flashed it on an eeprom then i wantet installing it in the drone that should be done with crafting the drone with your eeprom but if i try that it dont work ist like the recipe dont exist but jei tell me that the recipe exists

**Comment by payonel** [comment] 2018-03-07 22:47
please always include OC versions (the full jar name is best, such as OpenComputers-MC1.12.2-1.7.1.63.jar) in your bug reports

**Comment by JulianWogersien** [comment] 2018-03-08 07:46
OpenComputers-MC1.12.1-1.7.1.43

**Comment by payonel** [comment] 2018-03-11 18:08
confirmed duplicate of #2685

**Closed as completed by payonel** 2018-03-11 18:08 UTC
