### ISSUE TITLE
Computer in Minecarts

### ISSUE THREAD

**Issue by lordjoda** [MightyPirates/OpenComputers#465] opened 2014-08-04 20:08 UTC
I had a little discussion with Sangar about this, talking about a Computer that sits in a Minecart (just like a Minecart with chest or with TNT, well not exactly like that ;) )  and is able to do basically everything a computer can do (for example send and receive redstone signals, if this is possible both performance and code wise). The Computer however can not itself control the Minecart directly (accelerate, brake) but of course indirectly.
This would allow to allow basic "routing" from within without any other mods, but at the same time could be improved with options from other mods...
Additional ideas and feedback about this would be very much appreciated and also I would like to open the discussion if the computer should be able for example with the the appropriate card(?) be able to steer the cart itself.

**Comment by Wuerfel21** [comment] 2014-08-04 20:23
you would first need to craft an computer-cart and trow it in the assembler.
Also it should drain power from railcraft mfsu/mfe/cesu/batbox-carts.
Also it should be able to accept upgrades like navigation or inventory controller(it could then acces chest-carts).

**Comment by Kilobyte22** [comment] 2014-08-04 20:25
I was actually working on a plugin for this. And i will continue it at some point. ATM technical issues (namely ForgeGradle misbehaving) prevent any progress sadly. And yes, the main part would be the ability to control the cart. For details see my brainstorm gist: https://gist.github.com/Kilobyte22/344d4b67a523d3419f8d

**Comment by Eunomiac** [comment] 2014-09-14 05:33
> The Computer however can not itself control the Minecart directly (accelerate, brake) ...

My first reaction to reading this was:  Why not?    

I think having a sort of electric, computer-controlled minecart would be really cool!  And as for balance... well, I think it's hard to make _any_ feature related to minecarts OP:  You already need to set up a system of tracks, which requires figuring out how you want your pathing to work in advance (as opposed to, say, robots who can move anywhere).  

So I think any feature that would make them more appealing is gravy, and I'd err on the side of making them too easy to get and use, as opposed to being high-end (e.g. I'd argue against the need for an assembler---after all, a computer-controlled minecart could be thought of as a weaker version of a robot; making them easier to get than robots would turn them into an early-game alternative that's more restrictive but very cool and fun to play with)

**Comment by Vexatos** [comment] 2014-09-14 05:55
Railcraft integration: Make it consume power like the electric locomotive does.

**Comment by fnuecke** [comment] 2014-09-17 07:17
>  Why not?

Partially to to invalidate Kilo's addon mod. Some simple form of accelerating the cart would probably still make sense, though, yeah (similar to how a player can nudge the cart while sitting in it maybe).

What I really wanted to mention, though: with the new support of custom 'templates' for the assembler, this would also be built in it. The base part would be something like a case crafted together with a case or so. That would allow building a screen and keyboard into it, similar as with robots, to allow interacting with it when desired.

**Comment by Xfel** [comment] 2014-10-17 18:33
It doesn't need to be self propelled, but if it isn't, it should at least be able to control Railcraft's locomotives if they're in one train.

So in general, I see two scenarii here: One with railcraft, where the computer cart would only have control functions, and a StevesCarts-like single entity version.

**Comment by Kilobyte22** [comment] 2014-10-17 18:35
It was intended to control itself, but you gotta put in a motor module. However currently i paused the project because i gotta figure out how to get the cart moving. If anyone can help me with that, please let me know.

**Comment by Vexatos** [comment] 2014-10-18 05:52
@Xfel I think that would be pretty overpowered and remove the need for using Railcraft's routing system entirely. That's why the support I added for Railcraft in Computronics only made computers able to access certain things like setting the destination of the locomotive.

**Comment by Xfel** [comment] 2014-10-18 08:39
My primary intent was to set the speed of the locomotive and allow to couple/decouple. Routing would have to be done separately (eg. using wireless communication and a stationary track control computer)

**Comment by Vexatos** [comment] 2014-10-18 09:55
@Xfel Computronics already allows advanced computer-controlled routing with Railcraft, you might want to check that out.
Regarding speed and (de)coupling: I think those are exactly the features I would not want to be controllable, because those would entirely remove the need for the Limiter and coupling tracks. I would not want any part of RC to become useless due to computers.

**Comment by Xfel** [comment] 2014-10-18 10:13
Hmm, the first use of the computer cart I thought of would be some kind of shunting yard, where these features would come in handy. If the computer cart can't move on it's own or control the locomotives in its train, it doesn't really make sense to use it at all... 
This is like saying "Don't add computers from the game, they would entirely remove the need for redstone circuits". True, there are places where a limiter track or similar would be obsolete. But then, I have to program the computer if I want this to work; if I just want to low down in some places, I would just put the limiter tracks there because that is simpler.

**Comment by Vexatos** [comment] 2014-10-18 11:38
Anyways, a Computer minecart should be very heavy and thus slow, just like for example the Energy Storage carts from Railcraft if it's installed, so ~a fifth of the normal speed. This would be a good balance point.
@Xfel One idea would be to just place limiter tracks frequently and only activating them using OC redstone signals when needed. Also, you just gave me an idea: I will add support for limiter and locomotive tracks to Computronics so you can set the locomotive mode and the speed limit using computers. (See https://github.com/asiekierka/Computronics/issues/66)

**Comment by LordFokas** [comment] 2014-10-18 13:29
I completely agree with @Xfel on this one, I just don't see the need to make computer carts slow and heavy. I think computers have their own balance: They can do extremely powerful stuff, but the more powerful they become the more you have to code in order for it to get there. I don't think it makes sense at all for a cart with a computer to be heavier and slower, it just makes the cart less usable. We could even call the "realism" card here and say computers are lighter than humans or crates loaded with rocks, though the "realism" argument never had much of a place in Minecraft :p

**Comment by tekikai** [comment] 2015-02-25 02:43
I've been pointed to the discussion by Sangar from IRC since I was thinking along similar lines as you guys (Computer carts and described above features). What I'd love to see too would be:
- wireless modem for a computer cart (with possible range booster upgrade at the cost of energy for long range communication)
- a way for the computer to sense the contents of the carts (also for steam locos, i. e. sense the fuel level, water level)
  Controlling speed indirectly via the existing tracks sounds pretty cool to me too - I like the idea of not making existing solutions by other mods (RC in that case) obsolete. _If_ there was such an option, it would have to be prohibitively expensive, i. e. using 'endgame' items.

Is there currently some way of knowing which API commands the computronics<->railcraft API supports?

**Comment by fnuecke** [comment] 2015-02-25 20:10
@Vexatos should know if there's textual documentation anywhere; if you're not afraid of browsing through code, the [Railcraft driver classes can be found here](https://github.com/asiekierka/Computronics/tree/master/src/main/java/pl/asie/computronics/integration/railcraft).

**Comment by tekikai** [comment] 2015-02-26 00:08
thanks @fnuecke! I cloned it with SourceTree and had a look at the source - it is fairly readable and there even is a little explanation for each function, I think that will work!

**Comment by fnuecke** [comment] 2015-03-22 12:37
So after recent discussions on this topic, and based on the fact that these carts could not emit redstone signals, I'm closing this, as it seems to be not really worth the effort based on the limited gain it would provide.

**Closed as completed by fnuecke** 2015-03-22 12:37 UTC
