### ISSUE TITLE
Compatibility with Shader Mod

### ISSUE THREAD

**Issue by Shazuli** [MightyPirates/OpenComputers#2486] opened 2017-08-08 20:15 UTC
You read the title. This isn't a very important thing as it doesn't break anything.
When you got any shadow manipulating shader pack (every shader pack ever) the screen goes so dim it just barely can be seen or if any, it's like this even in a completely dark room. I was using [KUDA Shaders](http://shadersmods.com/kuda-shaders-mod/#comment-6317) for this particular screenshot:

![oc shaders](https://user-images.githubusercontent.com/9884180/29092503-d090adfa-7c86-11e7-9d49-b8732bfa303a.png)

**Comment by kotbehemot53** [comment] 2018-05-06 18:23
Yeah, that would be awesome to see things on screen with shaders!

**Comment by SquidDev** [comment] 2018-05-06 18:31
There was a similar issue on the ComputerCraft issue tracker (dan200/ComputerCraft#534) which was fixed by dan200/ComputerCraft@b7950a4209ef8b50a73f2ba2be8bea9baa90c23a. Basically one adds a call to:

```java
OpenGlHelper.setLightmapTextureCoords( OpenGlHelper.lightmapTexUnit, 0xFF, 0xFF );
```

at the same time as `RenderState.disableLighting()`.

I don't know if this is the same root cause as CC's issue, and so cannot comment on if it'll actually solve anything for OC. It's an ugly (and rather flawed) workaround, but shaders seem to ignore every other hint you can drop about lighting.

**Comment by kotbehemot53** [comment] 2018-05-07 21:58
For 1 second I thought about trying to fix it myself according to your suggestion @SquidDev , but I've never programmed in Java or made/edited Minecraft mods so sourcecode of OpenComputers looks a bit intimidating to me :-| I don't have a clue where to look.

**Comment by kotbehemot53** [comment] 2018-05-07 22:22
After some experiments, I've also noticed that it's not happening with same intensity with all shader packs. With SEUS Renewed 1.0.0 it's very visible (screens are completely unreadable) but it doesn't seem to happen with newest Chocapic 13 V6 (here screens are nice and readable), and with Continuum the screens are half dimmed. Unfortunately, of them all SEUS is the prettiest by far...

**Comment by skyem123** [comment] 2018-05-09 21:01
https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/client/renderer/tileentity/ScreenRenderer.scala
The could would probably have to be changed in here? 
(sadly I don't have the time to setup a build environment, but this seems like the place, it has lots of opengl stuff here...)

**Comment by samsonsin** [comment] 2018-06-18 22:06
Would really love a fix for this too, as i love shaders and will have to live with barely visible screens or maybe go to computercraft if it is not fixed. Hoping for a beta build or something!

**Comment by skyem123** [comment] 2018-06-26 18:09
I've been poking around a bit. Sadly I can't seem to setup a development environment due to annoying errors.

**Comment by paulhobbel** [comment] 2018-07-10 19:08
I got a development environment up and running for OpenComputers, want me to try it out?

**Comment by paulhobbel** [comment] 2018-07-10 19:47
That line fixed the lighting issue
![2018-07-10_21 51 46](https://user-images.githubusercontent.com/20015650/42533908-80264678-848b-11e8-9b1b-a3483b820b28.png)

Running on 1.12.2 with Sildurs Vibrant Shaders v1.17 Extreme.
Will make a PR asap, need to see if it causes any harm

**Comment by asiekierka** [comment] 2018-07-10 20:02
Does it work as intended at night, though?

**Comment by SquidDev** [comment] 2018-07-10 20:05
@asiekierka It didn't on CC (monitors have a reddish tint), but I'm not sure that's possible to resolve. Shaders appear to ignore pretty much every lighting hint you throw at them, so this seemed the best work around.

**Comment by paulhobbel** [comment] 2018-07-10 20:09
It has indeed a little reddish tint in night.
Day:
![2018-07-10_22 07 23](https://user-images.githubusercontent.com/20015650/42534747-c6084888-848d-11e8-860d-b989b1f94e3f.png)
Night:
![2018-07-10_22 07 39](https://user-images.githubusercontent.com/20015650/42534766-ce569d6e-848d-11e8-8802-628431431e5f.png)

**Comment by paulhobbel** [comment] 2018-07-10 20:30
Made a PR, it's only one like but still 😂

**Comment by kotbehemot53** [comment] 2018-07-11 06:18
Looks great to me! Cheers!

**Comment by MrSmith3101** [comment] 2018-11-04 00:12
I would really appreciate if this little change could be pushed to the public mod version =)
Thx for checking it out!

**Closed as completed** 2018-11-15 03:44 UTC
