### ISSUE TITLE
Robots ignore Cauldron's (Bukkit) interact event

### ISSUE THREAD

**Issue by oleg599** [MightyPirates/OpenComputers#656] opened 2014-11-06 01:43 UTC
Good day!

When robots use a tool who spawning throwable entity/fire/lightning/etc. (robot.use/swing) - his ignores cauldron/bukkit interact event.

For example i deny mining laser or another griefing tool in worldguard, when use player - it works and cancel event, but when use robot - his ignores PlayerInteractEvent and shoot, next, using the movements of the robot and this bug robot can break players regions.

Example snippet:

```
@EventHandler(priority = EventPriority.HIGHEST)
public void onPlayerInteract(PlayerInteractEvent event) {
    if (configUtils.BannedItemsID.contains(Integer.toString(item))) {
        event.setCancelled(true);
        event.setUseInteractedBlock(Event.Result.DENY);
        event.setUseItemInHand(Event.Result.DENY);
        event.getPlayer().sendMessage(ChatColor.RED + event.getItem().getType().name() + " is denied on this server");
    }
}
```

I guess you need add Forge's PlayerInteractEvent.

**Comment by LizzyTrickster** [comment] 2014-11-06 08:31
did you look at Sanger's response to #636? This issue seems to be a duplicate of that one

**Comment by fnuecke** [comment] 2014-11-06 11:53
Unless this is also sign related, it's something else; however, OC already makes use of these events, see [here](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/component/robot/Player.scala#L205) and [here](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/component/robot/Player.scala#L175). Not sure what `item` is in that `if`, though? Shouldn't that be something pulled from the event?

**Comment by tbbw** [comment] 2014-11-07 03:47
That looks like the banned items list in worldguard.
You can ban spesific items to be used and right ( or left ) clicked with by the player as in you can prevent someone from using a flint and steel in a server to prevent players from burning down someones wooden house or ban someone from been able to pour a bucket of lava but they can still pick lava up and put it in a tank... just not right click it on the "world".
This is also used to block some players from placing some blocks and unless my memory fails you could also configure this so it was allowed in Overworld but not in the Nether and such.

So the "item" in the "if" would be the item id written in the world guard config ( i have not done this since 1.6.4 so i'm speaking from memory ).

**Comment by fnuecke** [comment] 2014-11-07 11:53
> So the "item" in the "if" would be the item id written in the world guard config

But that would mean there's only a single item ID (`item` must be an integer, given the signature of `Integer.toString`)... I have a hard time believing the config is that limited?

**Comment by tbbw** [comment] 2014-11-07 18:31
Hmm all the info i managed to dig up is the wiki link listed in one of my old 1.6.4 servers:
http://wiki.sk89q.com/wiki/WorldGuard/Blacklist

**Comment by oleg599** [comment] 2014-11-07 20:14
fnuecke, it's from 1.6.4, also works on 1.7.10, if using material - nothing will change.

**Comment by fnuecke** [comment] 2014-11-08 02:09
"Material"? What do you mean?

**Comment by oleg599** [comment] 2014-11-08 05:54
I mean Material ID  (ID replacement 1.7+, example: minecraft:diamond_block)

**Comment by fnuecke** [comment] 2014-11-08 11:47
I'm still missing some pieces of the puzzle. Is there one instance for each blocked item of whatever contains the above code? How does that work in combination with the EventHandler, i.e. how is that filtered? It just doesn't make any sense to me out of context as it is (keep in mind, I have zero clue about Bukkit dev). Have you tested if that event handler is really not called at all for robots, and it's not just the `if` failing?

**Comment by oleg599** [comment] 2014-11-08 18:35
I mean this puzzle has three pieces:
1) Forge doesn't transform PlayerInteractEvent
2) Bukkit event method event.getPlayer().getItemInHand() is null

But I'm more inclined to the second.

Is it possible to imitate a item in hand on OC side?

**Comment by fnuecke** [comment] 2014-11-08 19:53
1. Well, Forge doesn't have to transform anything. If Cauldron is failing to do so that's really nothing I can fix on my end.
2. OC [overrides `getCurrentItem`](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/component/robot/Inventory.scala#L21) for the robot's inventory, and therefore `Player.getCurrentEquippedItem` (or `getHeldItem` in MC1.6) returns the equipped tool. This works perfectly fine in Forge, so again, if this doesn't work in Bukkit I suspect it's also a mapping issue, which, again, I cannot do anything about.

**Comment by fnuecke** [comment] 2014-11-19 12:03
So yeah, considering I'm doing all I can from the Forge side (AFAICT) I think the most reasonable approach here would be for someone to write a Bukkit plugin that uses the [robot events](https://github.com/MightyPirates/OpenComputers/tree/master-MC1.7.10/src/main/java/li/cil/oc/api/event) to specifically handle this.

**Closed as completed by fnuecke** 2014-11-19 12:03 UTC

**Comment by oleg599** [comment] 2014-11-19 17:13
fnuecke, bukkit can't wrap forge custom events into bukkit.

**Comment by fnuecke** [comment] 2014-11-19 17:53
Cauldron doesn't forward them / make them available in any way at all?

Hmm, well, then I guess someone will have to fork OC and add the Bukkit specific handling in there. Unless that's doable in a soft-dependency-ish manner, in which case I'd be happy to merge a pull request adding such functionality.

**Comment by oleg599** [comment] 2014-11-19 21:14
Look at plugin channels, maybe it's solution.

**Comment by fnuecke** [comment] 2014-11-20 05:20
What do you mean?

**Comment by oleg599** [comment] 2014-11-23 22:11
http://wiki.vg/Plugin_channel

**Comment by fnuecke** [comment] 2014-11-24 07:56
I don't see how network channels have anything to do with permission checks ?(and manually sending data on these sounds like a bad idea to me)

If you can point me at actual code examples I can have a look. Otherwise you'll have to find someone with Bukkit experience to code this, because I won't be digging into that.

**Comment by oleg599** [comment] 2014-11-30 05:32
After 5 hours analyze OC code, I can say the following: is RobotPlaceBlockEvent & RobotBreakBlockEvent wrap's forge's block break events? While I'm trying to make Bukkit support please add option in config which disable robot interaction with items and blocks. 

PS I hope will soon be a Sponge and we forget this how terrible dream :)

**Comment by fnuecke** [comment] 2014-11-30 13:35
Those events are sent in addition to Forge's own events. If you have a look at where they're fired, for the place event, `ItemStack.tryPlaceItemIntoWorld` is called, which handles the Forge event (`ForgeHooks.onPlaceItemIntoWorld`), and that's after an earlier `ForgeEventFactory.onPlayerInteract`.
For the break event the Forge events are dispatched a few lines up in the code (`ForgeEventFactory.onPlayerInteract`, followed by `MinecraftServer.getServer.isBlockProtected` followed by a `BlockEvent.BreakEvent`).

As for settings, you can set `allowActivateBlocks` to false, `swingRange` and `useAndPlaceRange` to zero, that should effectively disable block activation, breaking and placement. If there are any items that, when used by a robot, are gamebreaking they should probably be blacklisted in general, so let me know if that's the case.
