### ISSUE TITLE
Newest Native libraries (released sometime between 8-11th feb) break OC v1.7.1 on 1.7.10

### ISSUE THREAD

**Issue by StargateMC** [MightyPirates/OpenComputers#3047] opened 2019-02-12 03:39 UTC
Hi There,

I've had a series of players on multiple servers running OC v1.7.1 have hard drives corrupt in the past few days. These are 1.7.10 (1614) servers, both Thermos and regular Forge.

The only change I have been able to see is a new version of the native library was downloaded... though im not fully sure what that does.

Symptoms are:

All files on HDD's get blanked. The hard drive also will not allow any files to persist after it has been reflashed/formatted..... and server restarts do not solve the problem. Checking the files on the file system also shows  them as blank. Crafting a new drive exhibits the same behavior.

Resolution 1: Replacing the native files from backup doesn't restore the files... but it does allow the drives to function again.

Resolution 2: Updating to OC v1.7.4 fixes the problem also, without recovery of files and with the newest native library files.

Please allow us to disable automatic downloads of new library files if possible ? And alert us when they are available?

Kind Regards,

Bysokar

**Comment by payonel** [comment] 2019-02-12 07:13
duplicate of #3031, #3040, and #3046 .... and I'm sure there will be more
I'm very sorry you've lost your data! this is pretty bad news. Our latest release fixes this: https://minecraft.curseforge.com/projects/opencomputers/files

We thought it was a version/update of openjdk that caused this. Our latest build definitely fixes it, but, what do you mean "Newest Native libraries", new native lib of what? OC has native lua libs, but we haven't changed those in many years, and this bug is orthogonal  (it is affecting old OC versions and newer ones, all at the same time)

**Closed as completed by payonel** 2019-02-12 07:13 UTC

**Comment by payonel** [comment] 2019-02-12 07:25
also, reread your bug report. what native lib are you restoring from backups and seeing this bug stop? the lua libs having nothing to do with our file savings

btw, you can disable bufferChanges in the configs to bypass this issue in older versions
