### ISSUE TITLE
Robot unable to activate blocks

### ISSUE THREAD

**Issue by rahul-pisharody** [MightyPirates/OpenComputers#2786] opened 2018-03-20 06:07 UTC
The robot.use() function (or useUp or useDown) function returns nil with an "unknown error" as cause

**Comment by payonel** [comment] 2018-03-20 07:55
for what block are you trying to active?
what OC version (Full version name)
does it repro in sp?
does it repro with OC only? (no other mods)

**Comment by rahul-pisharody** [comment] 2018-03-20 08:15
OpenComputers-MC1.12.2-1.7.2.67
This is in Single Player
Other mods being used:
Applied Energistics 2
Immersive Engineering
OpenBlocks
RFTools

It doesn't matter what block I try to activate. It gives the message every time I try, whether there is a block or isn't.
I was originally trying to get the robot to charge itself by going next to the charger and activating a Lever. 
It worked in OpenComputers-MC1.12.1-1.7.1.43, but broke in the latest version.

**Comment by rahul-pisharody** [comment] 2018-03-20 10:10
Checked it out by creating a new robot, opening lua interpreter in OpenOs and typing out robot.use()
Also tried it with the Creatix robot. Same response.

**Comment by payonel** [comment] 2018-03-20 20:27
thanks for the help

This was caused by a change between minecraft 1.10 and 1.11 where ItemStack.EMPTY is used in place of nulls

The robot was still able to use objects, but the return value was reporting that an underlying exception was thrown during the comparisons

You should still be able to use the lever, the return of the `use()` function may return `false, "unknown error"`, but the use() should still work

Either way, I've pushed a fix for this, thank you

**Closed as completed by payonel** 2018-03-20 20:27 UTC
