### ISSUE TITLE
There were errors running the class transformer

### ISSUE THREAD

**Issue by prikkprikkprikk** [MightyPirates/OpenComputers#2098] opened 2016-10-17 08:26 UTC
Reporting this as requested.

Using HermitPack, if that means anything.

**Comment by Vexatos** [comment] 2016-11-14 18:34
You did not provide an `fml-client-latest.log` as requested. Considering you mentioned the Hermitpack, it is most likely that this is a duplicate of #2114 and therefore of #1998 and #2014.

**Closed as completed by Vexatos** 2016-11-14 18:34 UTC
